/* Begin CVS Header
   $Source: /Volumes/Home/Users/shoops/cvs/copasi_dev/copasi/clapackwrap.h,v $
   $Revision: 1.5 $
   $Name:  $
   $Author: shoops $ 
   $Date: 2005/08/16 16:22:10 $
   End CVS Header */

#ifdef min
# undef min
#endif // min

#ifdef max
# undef max
#endif // max

extern "C"
  {
#ifdef USE_MKL
# define cbdsqr_ cbdsqr
# define cgbbrd_ cgbbrd
# define cgbcon_ cgbcon
# define cgbequ_ cgbequ
# define cgbrfs_ cgbrfs
# define cgbsv_ cgbsv
# define cgbsvx_ cgbsvx
# define cgbtf2_ cgbtf2
# define cgbtrf_ cgbtrf
# define cgbtrs_ cgbtrs
# define cgebak_ cgebak
# define cgebal_ cgebal
# define cgebd2_ cgebd2
# define cgebrd_ cgebrd
# define cgecon_ cgecon
# define cgeequ_ cgeequ
# define cgees_ cgees
# define cgeesx_ cgeesx
# define cgeev_ cgeev
# define cgeevx_ cgeevx
# define cgegs_ cgegs
# define cgegv_ cgegv
# define cgehd2_ cgehd2
# define cgehrd_ cgehrd
# define cgelq2_ cgelq2
# define cgelqf_ cgelqf
# define cgels_ cgels
# define cgelsx_ cgelsx
# define cgelsy_ cgelsy
# define cgeql2_ cgeql2
# define cgeqlf_ cgeqlf
# define cgeqp3_ cgeqp3
# define cgeqpf_ cgeqpf
# define cgeqr2_ cgeqr2
# define cgeqrf_ cgeqrf
# define cgerfs_ cgerfs
# define cgerq2_ cgerq2
# define cgerqf_ cgerqf
# define cgesc2_ cgesc2
# define cgesv_ cgesv
# define cgesvx_ cgesvx
# define cgetc2_ cgetc2
# define cgetf2_ cgetf2
# define cgetrf_ cgetrf
# define cgetri_ cgetri
# define cgetrs_ cgetrs
# define cggbak_ cggbak
# define cggbal_ cggbal
# define cgges_ cgges
# define cggesx_ cggesx
# define cggev_ cggev
# define cggevx_ cggevx
# define cggglm_ cggglm
# define cgghrd_ cgghrd
# define cgglse_ cgglse
# define cggqrf_ cggqrf
# define cggrqf_ cggrqf
# define cggsvd_ cggsvd
# define cggsvp_ cggsvp
# define cgtcon_ cgtcon
# define cgtrfs_ cgtrfs
# define cgtsv_ cgtsv
# define cgtsvx_ cgtsvx
# define cgttrf_ cgttrf
# define cgttrs_ cgttrs
# define cgtts2_ cgtts2
# define chbev_ chbev
# define chbevd_ chbevd
# define chbevx_ chbevx
# define chbgst_ chbgst
# define chbgv_ chbgv
# define chbgvx_ chbgvx
# define chbtrd_ chbtrd
# define checon_ checon
# define cheev_ cheev
# define cheevd_ cheevd
# define cheevr_ cheevr
# define cheevx_ cheevx
# define chegs2_ chegs2
# define chegst_ chegst
# define chegv_ chegv
# define chegvd_ chegvd
# define chegvx_ chegvx
# define cherfs_ cherfs
# define chesv_ chesv
# define chesvx_ chesvx
# define chetf2_ chetf2
# define chetrd_ chetrd
# define chetrf_ chetrf
# define chetri_ chetri
# define chetrs_ chetrs
# define chgeqz_ chgeqz
# define chpcon_ chpcon
# define chpev_ chpev
# define chpevd_ chpevd
# define chpevx_ chpevx
# define chpgst_ chpgst
# define chpgv_ chpgv
# define chpgvd_ chpgvd
# define chpgvx_ chpgvx
# define chprfs_ chprfs
# define chpsv_ chpsv
# define chpsvx_ chpsvx
# define chptrd_ chptrd
# define chptrf_ chptrf
# define chptri_ chptri
# define chptrs_ chptrs
# define chsein_ chsein
# define chseqr_ chseqr
# define clabrd_ clabrd
# define clacgv_ clacgv
# define clacon_ clacon
# define clacp2_ clacp2
# define clacpy_ clacpy
# define clacrm_ clacrm
# define clacrt_ clacrt
# define claed0_ claed0
# define claed7_ claed7
# define claed8_ claed8
# define claein_ claein
# define claesy_ claesy
# define claev2_ claev2
# define clags2_ clags2
# define clagtm_ clagtm
# define clahef_ clahef
# define clahqr_ clahqr
# define clahrd_ clahrd
# define claic1_ claic1
# define clals0_ clals0
# define clalsa_ clalsa
# define clapll_ clapll
# define clapmt_ clapmt
# define claqgb_ claqgb
# define claqge_ claqge
# define claqhb_ claqhb
# define claqhe_ claqhe
# define claqhp_ claqhp
# define claqp2_ claqp2
# define claqps_ claqps
# define claqsb_ claqsb
# define claqsp_ claqsp
# define claqsy_ claqsy
# define clar1v_ clar1v
# define clar2v_ clar2v
# define clarcm_ clarcm
# define clarf_ clarf
# define clarfb_ clarfb
# define clarfg_ clarfg
# define clarft_ clarft
# define clarfx_ clarfx
# define clargv_ clargv
# define clarnv_ clarnv
# define clarrv_ clarrv
# define clartg_ clartg
# define clartv_ clartv
# define clarz_ clarz
# define clarzb_ clarzb
# define clarzt_ clarzt
# define clascl_ clascl
# define claset_ claset
# define clasr_ clasr
# define classq_ classq
# define claswp_ claswp
# define clasyf_ clasyf
# define clatbs_ clatbs
# define clatdf_ clatdf
# define clatps_ clatps
# define clatrd_ clatrd
# define clatrs_ clatrs
# define clatrz_ clatrz
# define clatzm_ clatzm
# define clauu2_ clauu2
# define clauum_ clauum
# define cpbcon_ cpbcon
# define cpbequ_ cpbequ
# define cpbrfs_ cpbrfs
# define cpbstf_ cpbstf
# define cpbsv_ cpbsv
# define cpbsvx_ cpbsvx
# define cpbtf2_ cpbtf2
# define cpbtrf_ cpbtrf
# define cpbtrs_ cpbtrs
# define cpocon_ cpocon
# define cpoequ_ cpoequ
# define cporfs_ cporfs
# define cposv_ cposv
# define cposvx_ cposvx
# define cpotf2_ cpotf2
# define cpotrf_ cpotrf
# define cpotri_ cpotri
# define cpotrs_ cpotrs
# define cppcon_ cppcon
# define cppequ_ cppequ
# define cpprfs_ cpprfs
# define cppsv_ cppsv
# define cppsvx_ cppsvx
# define cpptrf_ cpptrf
# define cpptri_ cpptri
# define cpptrs_ cpptrs
# define cptcon_ cptcon
# define cptrfs_ cptrfs
# define cptsv_ cptsv
# define cptsvx_ cptsvx
# define cpttrf_ cpttrf
# define cpttrs_ cpttrs
# define cptts2_ cptts2
# define crot_ crot
# define cspcon_ cspcon
# define cspmv_ cspmv
# define cspr_ cspr
# define csprfs_ csprfs
# define cspsv_ cspsv
# define cspsvx_ cspsvx
# define csptrf_ csptrf
# define csptri_ csptri
# define csptrs_ csptrs
# define csrot_ csrot
# define csrscl_ csrscl
# define cstedc_ cstedc
# define cstein_ cstein
# define csteqr_ csteqr
# define csycon_ csycon
# define csymv_ csymv
# define csyr_ csyr
# define csyrfs_ csyrfs
# define csysv_ csysv
# define csysvx_ csysvx
# define csytf2_ csytf2
# define csytrf_ csytrf
# define csytri_ csytri
# define csytrs_ csytrs
# define ctbcon_ ctbcon
# define ctbrfs_ ctbrfs
# define ctbtrs_ ctbtrs
# define ctgevc_ ctgevc
# define ctgex2_ ctgex2
# define ctgexc_ ctgexc
# define ctgsen_ ctgsen
# define ctgsja_ ctgsja
# define ctgsna_ ctgsna
# define ctgsy2_ ctgsy2
# define ctgsyl_ ctgsyl
# define ctpcon_ ctpcon
# define ctprfs_ ctprfs
# define ctptri_ ctptri
# define ctptrs_ ctptrs
# define ctrcon_ ctrcon
# define ctrevc_ ctrevc
# define ctrexc_ ctrexc
# define ctrrfs_ ctrrfs
# define ctrsen_ ctrsen
# define ctrsna_ ctrsna
# define ctrsyl_ ctrsyl
# define ctrti2_ ctrti2
# define ctrtri_ ctrtri
# define ctrtrs_ ctrtrs
# define ctzrqf_ ctzrqf
# define ctzrzf_ ctzrzf
# define cung2l_ cung2l
# define cung2r_ cung2r
# define cungbr_ cungbr
# define cunghr_ cunghr
# define cungl2_ cungl2
# define cunglq_ cunglq
# define cungql_ cungql
# define cungqr_ cungqr
# define cungr2_ cungr2
# define cungrq_ cungrq
# define cungtr_ cungtr
# define cunm2l_ cunm2l
# define cunm2r_ cunm2r
# define cunmbr_ cunmbr
# define cunmhr_ cunmhr
# define cunml2_ cunml2
# define cunmlq_ cunmlq
# define cunmql_ cunmql
# define cunmqr_ cunmqr
# define cunmr2_ cunmr2
# define cunmr3_ cunmr3
# define cunmrq_ cunmrq
# define cunmrz_ cunmrz
# define cunmtr_ cunmtr
# define cupgtr_ cupgtr
# define cupmtr_ cupmtr
# define dbdsdc_ dbdsdc
# define dbdsqr_ dbdsqr
# define ddisna_ ddisna
# define dgbbrd_ dgbbrd
# define dgbcon_ dgbcon
# define dgbequ_ dgbequ
# define dgbrfs_ dgbrfs
# define dgbsv_ dgbsv
# define dgbsvx_ dgbsvx
# define dgbtf2_ dgbtf2
# define dgbtrf_ dgbtrf
# define dgbtrs_ dgbtrs
# define dgebak_ dgebak
# define dgebal_ dgebal
# define dgebd2_ dgebd2
# define dgebrd_ dgebrd
# define dgecon_ dgecon
# define dgeequ_ dgeequ
# define dgees_ dgees
# define dgeesx_ dgeesx
# define dgeev_ dgeev
# define dgeevx_ dgeevx
# define dgegs_ dgegs
# define dgegv_ dgegv
# define dgehd2_ dgehd2
# define dgehrd_ dgehrd
# define dgelq2_ dgelq2
# define dgelqf_ dgelqf
# define dgels_ dgels
# define dgelsd_ dgelsd
# define dgelss_ dgelss
# define dgelsx_ dgelsx
# define dgelsy_ dgelsy
# define dgeql2_ dgeql2
# define dgeqlf_ dgeqlf
# define dgeqp3_ dgeqp3
# define dgeqpf_ dgeqpf
# define dgeqr2_ dgeqr2
# define dgeqrf_ dgeqrf
# define dgerfs_ dgerfs
# define dgerq2_ dgerq2
# define dgerqf_ dgerqf
# define dgesc2_ dgesc2
# define dgesdd_ dgesdd
# define dgesv_ dgesv
# define dgesvd_ dgesvd
# define dgesvx_ dgesvx
# define dgetc2_ dgetc2
# define dgetf2_ dgetf2
# define dgetrf_ dgetrf
# define dgetri_ dgetri
# define dgetrs_ dgetrs
# define dggbak_ dggbak
# define dggbal_ dggbal
# define dgges_ dgges
# define dggesx_ dggesx
# define dggev_ dggev
# define dggevx_ dggevx
# define dggglm_ dggglm
# define dgghrd_ dgghrd
# define dgglse_ dgglse
# define dggqrf_ dggqrf
# define dggrqf_ dggrqf
# define dggsvd_ dggsvd
# define dggsvp_ dggsvp
# define dgtcon_ dgtcon
# define dgtrfs_ dgtrfs
# define dgtsv_ dgtsv
# define dgtsvx_ dgtsvx
# define dgttrf_ dgttrf
# define dgttrs_ dgttrs
# define dgtts2_ dgtts2
# define dhgeqz_ dhgeqz
# define dhsein_ dhsein
# define dhseqr_ dhseqr
# define dlabad_ dlabad
# define dlabrd_ dlabrd
# define dlacon_ dlacon
# define dlacpy_ dlacpy
# define dladiv_ dladiv
# define dlae2_ dlae2
# define dlaebz_ dlaebz
# define dlaed0_ dlaed0
# define dlaed1_ dlaed1
# define dlaed2_ dlaed2
# define dlaed3_ dlaed3
# define dlaed4_ dlaed4
# define dlaed5_ dlaed5
# define dlaed6_ dlaed6
# define dlaed7_ dlaed7
# define dlaed8_ dlaed8
# define dlaed9_ dlaed9
# define dlaeda_ dlaeda
# define dlaein_ dlaein
# define dlaev2_ dlaev2
# define dlaexc_ dlaexc
# define dlag2_ dlag2
# define dlags2_ dlags2
# define dlagtf_ dlagtf
# define dlagtm_ dlagtm
# define dlagts_ dlagts
# define dlagv2_ dlagv2
# define dlahqr_ dlahqr
# define dlahrd_ dlahrd
# define dlaic1_ dlaic1
# define dlaln2_ dlaln2
# define dlals0_ dlals0
# define dlalsa_ dlalsa
# define dlalsd_ dlalsd
# define dlamc1_ dlamc1
# define dlamc2_ dlamc2
# define dlamc4_ dlamc4
# define dlamc5_ dlamc5
# define dlamrg_ dlamrg
# define dlanv2_ dlanv2
# define dlapll_ dlapll
# define dlapmt_ dlapmt
# define dlaqgb_ dlaqgb
# define dlaqge_ dlaqge
# define dlaqp2_ dlaqp2
# define dlaqps_ dlaqps
# define dlaqsb_ dlaqsb
# define dlaqsp_ dlaqsp
# define dlaqsy_ dlaqsy
# define dlaqtr_ dlaqtr
# define dlar1v_ dlar1v
# define dlar2v_ dlar2v
# define dlarf_ dlarf
# define dlarfb_ dlarfb
# define dlarfg_ dlarfg
# define dlarft_ dlarft
# define dlarfx_ dlarfx
# define dlargv_ dlargv
# define dlarnv_ dlarnv
# define dlarrb_ dlarrb
# define dlarre_ dlarre
# define dlarrf_ dlarrf
# define dlarrv_ dlarrv
# define dlartg_ dlartg
# define dlartv_ dlartv
# define dlaruv_ dlaruv
# define dlarz_ dlarz
# define dlarzb_ dlarzb
# define dlarzt_ dlarzt
# define dlas2_ dlas2
# define dlascl_ dlascl
# define dlasd0_ dlasd0
# define dlasd1_ dlasd1
# define dlasd2_ dlasd2
# define dlasd3_ dlasd3
# define dlasd4_ dlasd4
# define dlasd5_ dlasd5
# define dlasd6_ dlasd6
# define dlasd7_ dlasd7
# define dlasd8_ dlasd8
# define dlasd9_ dlasd9
# define dlasda_ dlasda
# define dlasdq_ dlasdq
# define dlasdt_ dlasdt
# define dlaset_ dlaset
# define dlasq1_ dlasq1
# define dlasq2_ dlasq2
# define dlasq3_ dlasq3
# define dlasq4_ dlasq4
# define dlasq5_ dlasq5
# define dlasq6_ dlasq6
# define dlasr_ dlasr
# define dlasrt_ dlasrt
# define dlassq_ dlassq
# define dlasv2_ dlasv2
# define dlaswp_ dlaswp
# define dlasy2_ dlasy2
# define dlasyf_ dlasyf
# define dlatbs_ dlatbs
# define dlatdf_ dlatdf
# define dlatps_ dlatps
# define dlatrd_ dlatrd
# define dlatrs_ dlatrs
# define dlatrz_ dlatrz
# define dlatzm_ dlatzm
# define dlauu2_ dlauu2
# define dlauum_ dlauum
# define dopgtr_ dopgtr
# define dopmtr_ dopmtr
# define dorg2l_ dorg2l
# define dorg2r_ dorg2r
# define dorgbr_ dorgbr
# define dorghr_ dorghr
# define dorgl2_ dorgl2
# define dorglq_ dorglq
# define dorgql_ dorgql
# define dorgqr_ dorgqr
# define dorgr2_ dorgr2
# define dorgrq_ dorgrq
# define dorgtr_ dorgtr
# define dorm2l_ dorm2l
# define dorm2r_ dorm2r
# define dormbr_ dormbr
# define dormhr_ dormhr
# define dorml2_ dorml2
# define dormlq_ dormlq
# define dormql_ dormql
# define dormqr_ dormqr
# define dormr2_ dormr2
# define dormr3_ dormr3
# define dormrq_ dormrq
# define dormrz_ dormrz
# define dormtr_ dormtr
# define dpbcon_ dpbcon
# define dpbequ_ dpbequ
# define dpbrfs_ dpbrfs
# define dpbstf_ dpbstf
# define dpbsv_ dpbsv
# define dpbsvx_ dpbsvx
# define dpbtf2_ dpbtf2
# define dpbtrf_ dpbtrf
# define dpbtrs_ dpbtrs
# define dpocon_ dpocon
# define dpoequ_ dpoequ
# define dporfs_ dporfs
# define dposv_ dposv
# define dposvx_ dposvx
# define dpotf2_ dpotf2
# define dpotrf_ dpotrf
# define dpotri_ dpotri
# define dpotrs_ dpotrs
# define dppcon_ dppcon
# define dppequ_ dppequ
# define dpprfs_ dpprfs
# define dppsv_ dppsv
# define dppsvx_ dppsvx
# define dpptrf_ dpptrf
# define dpptri_ dpptri
# define dpptrs_ dpptrs
# define dptcon_ dptcon
# define dpteqr_ dpteqr
# define dptrfs_ dptrfs
# define dptsv_ dptsv
# define dptsvx_ dptsvx
# define dpttrf_ dpttrf
# define dpttrs_ dpttrs
# define dptts2_ dptts2
# define drscl_ drscl
# define dsbev_ dsbev
# define dsbevd_ dsbevd
# define dsbevx_ dsbevx
# define dsbgst_ dsbgst
# define dsbgv_ dsbgv
# define dsbgvd_ dsbgvd
# define dsbgvx_ dsbgvx
# define dsbtrd_ dsbtrd
# define dspcon_ dspcon
# define dspev_ dspev
# define dspevd_ dspevd
# define dspevx_ dspevx
# define dspgst_ dspgst
# define dspgv_ dspgv
# define dspgvd_ dspgvd
# define dspgvx_ dspgvx
# define dsprfs_ dsprfs
# define dspsv_ dspsv
# define dspsvx_ dspsvx
# define dsptrd_ dsptrd
# define dsptrf_ dsptrf
# define dsptri_ dsptri
# define dsptrs_ dsptrs
# define dstebz_ dstebz
# define dstedc_ dstedc
# define dstegr_ dstegr
# define dstein_ dstein
# define dsteqr_ dsteqr
# define dsterf_ dsterf
# define dstev_ dstev
# define dstevd_ dstevd
# define dstevr_ dstevr
# define dstevx_ dstevx
# define dsycon_ dsycon
# define dsyev_ dsyev
# define dsyevd_ dsyevd
# define dsyevr_ dsyevr
# define dsyevx_ dsyevx
# define dsygs2_ dsygs2
# define dsygst_ dsygst
# define dsygv_ dsygv
# define dsygvd_ dsygvd
# define dsygvx_ dsygvx
# define dsyrfs_ dsyrfs
# define dsysv_ dsysv
# define dsysvx_ dsysvx
# define dsytd2_ dsytd2
# define dsytf2_ dsytf2
# define dsytrd_ dsytrd
# define dsytrf_ dsytrf
# define dsytri_ dsytri
# define dsytrs_ dsytrs
# define dtbcon_ dtbcon
# define dtbrfs_ dtbrfs
# define dtbtrs_ dtbtrs
# define dtgevc_ dtgevc
# define dtgex2_ dtgex2
# define dtgexc_ dtgexc
# define dtgsen_ dtgsen
# define dtgsja_ dtgsja
# define dtgsna_ dtgsna
# define dtgsy2_ dtgsy2
# define dtgsyl_ dtgsyl
# define dtpcon_ dtpcon
# define dtprfs_ dtprfs
# define dtptri_ dtptri
# define dtptrs_ dtptrs
# define dtrcon_ dtrcon
# define dtrevc_ dtrevc
# define dtrexc_ dtrexc
# define dtrrfs_ dtrrfs
# define dtrsen_ dtrsen
# define dtrsna_ dtrsna
# define dtrsyl_ dtrsyl
# define dtrti2_ dtrti2
# define dtrtri_ dtrtri
# define dtrtrs_ dtrtrs
# define dtzrqf_ dtzrqf
# define dtzrzf_ dtzrzf
    integer icmax1_
    integer ieeeck_
    integer ilaenv_
    integer izmax1_
# define sbdsdc_ sbdsdc
# define sbdsqr_ sbdsqr
# define sdisna_ sdisna
# define sgbbrd_ sgbbrd
# define sgbcon_ sgbcon
# define sgbequ_ sgbequ
# define sgbrfs_ sgbrfs
# define sgbsv_ sgbsv
# define sgbsvx_ sgbsvx
# define sgbtf2_ sgbtf2
# define sgbtrf_ sgbtrf
# define sgbtrs_ sgbtrs
# define sgebak_ sgebak
# define sgebal_ sgebal
# define sgebd2_ sgebd2
# define sgebrd_ sgebrd
# define sgecon_ sgecon
# define sgeequ_ sgeequ
# define sgees_ sgees
# define sgeesx_ sgeesx
# define sgeev_ sgeev
# define sgeevx_ sgeevx
# define sgegs_ sgegs
# define sgegv_ sgegv
# define sgehd2_ sgehd2
# define sgehrd_ sgehrd
# define sgelq2_ sgelq2
# define sgelqf_ sgelqf
# define sgels_ sgels
# define sgelsd_ sgelsd
# define sgelss_ sgelss
# define sgelsx_ sgelsx
# define sgelsy_ sgelsy
# define sgeql2_ sgeql2
# define sgeqlf_ sgeqlf
# define sgeqp3_ sgeqp3
# define sgeqpf_ sgeqpf
# define sgeqr2_ sgeqr2
# define sgeqrf_ sgeqrf
# define sgerfs_ sgerfs
# define sgerq2_ sgerq2
# define sgerqf_ sgerqf
# define sgesc2_ sgesc2
# define sgesdd_ sgesdd
# define sgesv_ sgesv
# define sgesvd_ sgesvd
# define sgesvx_ sgesvx
# define sgetc2_ sgetc2
# define sgetf2_ sgetf2
# define sgetrf_ sgetrf
# define sgetri_ sgetri
# define sgetrs_ sgetrs
# define sggbak_ sggbak
# define sggbal_ sggbal
# define sgges_ sgges
# define sggesx_ sggesx
# define sggev_ sggev
# define sggevx_ sggevx
# define sggglm_ sggglm
# define sgghrd_ sgghrd
# define sgglse_ sgglse
# define sggqrf_ sggqrf
# define sggrqf_ sggrqf
# define sggsvd_ sggsvd
# define sggsvp_ sggsvp
# define sgtcon_ sgtcon
# define sgtrfs_ sgtrfs
# define sgtsv_ sgtsv
# define sgtsvx_ sgtsvx
# define sgttrf_ sgttrf
# define sgttrs_ sgttrs
# define sgtts2_ sgtts2
# define shgeqz_ shgeqz
# define shsein_ shsein
# define shseqr_ shseqr
# define slabad_ slabad
# define slabrd_ slabrd
# define slacon_ slacon
# define slacpy_ slacpy
# define sladiv_ sladiv
# define slae2_ slae2
# define slaebz_ slaebz
# define slaed0_ slaed0
# define slaed1_ slaed1
# define slaed2_ slaed2
# define slaed3_ slaed3
# define slaed4_ slaed4
# define slaed5_ slaed5
# define slaed6_ slaed6
# define slaed7_ slaed7
# define slaed8_ slaed8
# define slaed9_ slaed9
# define slaeda_ slaeda
# define slaein_ slaein
# define slaev2_ slaev2
# define slaexc_ slaexc
# define slag2_ slag2
# define slags2_ slags2
# define slagtf_ slagtf
# define slagtm_ slagtm
# define slagts_ slagts
# define slagv2_ slagv2
# define slahqr_ slahqr
# define slahrd_ slahrd
# define slaic1_ slaic1
# define slaln2_ slaln2
# define slals0_ slals0
# define slalsa_ slalsa
# define slalsd_ slalsd
# define slamc1_ slamc1
# define slamc2_ slamc2
# define slamc4_ slamc4
# define slamc5_ slamc5
# define slamrg_ slamrg
# define slanv2_ slanv2
# define slapll_ slapll
# define slapmt_ slapmt
# define slaqgb_ slaqgb
# define slaqge_ slaqge
# define slaqp2_ slaqp2
# define slaqps_ slaqps
# define slaqsb_ slaqsb
# define slaqsp_ slaqsp
# define slaqsy_ slaqsy
# define slaqtr_ slaqtr
# define slar1v_ slar1v
# define slar2v_ slar2v
# define slarf_ slarf
# define slarfb_ slarfb
# define slarfg_ slarfg
# define slarft_ slarft
# define slarfx_ slarfx
# define slargv_ slargv
# define slarnv_ slarnv
# define slarrb_ slarrb
# define slarre_ slarre
# define slarrf_ slarrf
# define slarrv_ slarrv
# define slartg_ slartg
# define slartv_ slartv
# define slaruv_ slaruv
# define slarz_ slarz
# define slarzb_ slarzb
# define slarzt_ slarzt
# define slas2_ slas2
# define slascl_ slascl
# define slasd0_ slasd0
# define slasd1_ slasd1
# define slasd2_ slasd2
# define slasd3_ slasd3
# define slasd4_ slasd4
# define slasd5_ slasd5
# define slasd6_ slasd6
# define slasd7_ slasd7
# define slasd8_ slasd8
# define slasd9_ slasd9
# define slasda_ slasda
# define slasdq_ slasdq
# define slasdt_ slasdt
# define slaset_ slaset
# define slasq1_ slasq1
# define slasq2_ slasq2
# define slasq3_ slasq3
# define slasq4_ slasq4
# define slasq5_ slasq5
# define slasq6_ slasq6
# define slasr_ slasr
# define slasrt_ slasrt
# define slassq_ slassq
# define slasv2_ slasv2
# define slaswp_ slaswp
# define slasy2_ slasy2
# define slasyf_ slasyf
# define slatbs_ slatbs
# define slatdf_ slatdf
# define slatps_ slatps
# define slatrd_ slatrd
# define slatrs_ slatrs
# define slatrz_ slatrz
# define slatzm_ slatzm
# define slauu2_ slauu2
# define slauum_ slauum
# define sopgtr_ sopgtr
# define sopmtr_ sopmtr
# define sorg2l_ sorg2l
# define sorg2r_ sorg2r
# define sorgbr_ sorgbr
# define sorghr_ sorghr
# define sorgl2_ sorgl2
# define sorglq_ sorglq
# define sorgql_ sorgql
# define sorgqr_ sorgqr
# define sorgr2_ sorgr2
# define sorgrq_ sorgrq
# define sorgtr_ sorgtr
# define sorm2l_ sorm2l
# define sorm2r_ sorm2r
# define sormbr_ sormbr
# define sormhr_ sormhr
# define sorml2_ sorml2
# define sormlq_ sormlq
# define sormql_ sormql
# define sormqr_ sormqr
# define sormr2_ sormr2
# define sormr3_ sormr3
# define sormrq_ sormrq
# define sormrz_ sormrz
# define sormtr_ sormtr
# define spbcon_ spbcon
# define spbequ_ spbequ
# define spbrfs_ spbrfs
# define spbstf_ spbstf
# define spbsv_ spbsv
# define spbsvx_ spbsvx
# define spbtf2_ spbtf2
# define spbtrf_ spbtrf
# define spbtrs_ spbtrs
# define spocon_ spocon
# define spoequ_ spoequ
# define sporfs_ sporfs
# define sposv_ sposv
# define sposvx_ sposvx
# define spotf2_ spotf2
# define spotrf_ spotrf
# define spotri_ spotri
# define spotrs_ spotrs
# define sppcon_ sppcon
# define sppequ_ sppequ
# define spprfs_ spprfs
# define sppsv_ sppsv
# define sppsvx_ sppsvx
# define spptrf_ spptrf
# define spptri_ spptri
# define spptrs_ spptrs
# define sptcon_ sptcon
# define spteqr_ spteqr
# define sptrfs_ sptrfs
# define sptsv_ sptsv
# define sptsvx_ sptsvx
# define spttrf_ spttrf
# define spttrs_ spttrs
# define sptts2_ sptts2
# define srscl_ srscl
# define ssbev_ ssbev
# define ssbevd_ ssbevd
# define ssbevx_ ssbevx
# define ssbgst_ ssbgst
# define ssbgv_ ssbgv
# define ssbgvd_ ssbgvd
# define ssbgvx_ ssbgvx
# define ssbtrd_ ssbtrd
# define sspcon_ sspcon
# define sspev_ sspev
# define sspevd_ sspevd
# define sspevx_ sspevx
# define sspgst_ sspgst
# define sspgv_ sspgv
# define sspgvd_ sspgvd
# define sspgvx_ sspgvx
# define ssprfs_ ssprfs
# define sspsv_ sspsv
# define sspsvx_ sspsvx
# define ssptrd_ ssptrd
# define ssptrf_ ssptrf
# define ssptri_ ssptri
# define ssptrs_ ssptrs
# define sstebz_ sstebz
# define sstedc_ sstedc
# define sstegr_ sstegr
# define sstein_ sstein
# define ssteqr_ ssteqr
# define ssterf_ ssterf
# define sstev_ sstev
# define sstevd_ sstevd
# define sstevr_ sstevr
# define sstevx_ sstevx
# define ssycon_ ssycon
# define ssyev_ ssyev
# define ssyevd_ ssyevd
# define ssyevr_ ssyevr
# define ssyevx_ ssyevx
# define ssygs2_ ssygs2
# define ssygst_ ssygst
# define ssygv_ ssygv
# define ssygvd_ ssygvd
# define ssygvx_ ssygvx
# define ssyrfs_ ssyrfs
# define ssysv_ ssysv
# define ssysvx_ ssysvx
# define ssytd2_ ssytd2
# define ssytf2_ ssytf2
# define ssytrd_ ssytrd
# define ssytrf_ ssytrf
# define ssytri_ ssytri
# define ssytrs_ ssytrs
# define stbcon_ stbcon
# define stbrfs_ stbrfs
# define stbtrs_ stbtrs
# define stgevc_ stgevc
# define stgex2_ stgex2
# define stgexc_ stgexc
# define stgsen_ stgsen
# define stgsja_ stgsja
# define stgsna_ stgsna
# define stgsy2_ stgsy2
# define stgsyl_ stgsyl
# define stpcon_ stpcon
# define stprfs_ stprfs
# define stptri_ stptri
# define stptrs_ stptrs
# define strcon_ strcon
# define strevc_ strevc
# define strexc_ strexc
# define strrfs_ strrfs
# define strsen_ strsen
# define strsna_ strsna
# define strsyl_ strsyl
# define strti2_ strti2
# define strtri_ strtri
# define strtrs_ strtrs
# define stzrqf_ stzrqf
# define stzrzf_ stzrzf
# define xerbla_ xerbla
# define zbdsqr_ zbdsqr
# define zdrot_ zdrot
# define zdrscl_ zdrscl
# define zgbbrd_ zgbbrd
# define zgbcon_ zgbcon
# define zgbequ_ zgbequ
# define zgbrfs_ zgbrfs
# define zgbsv_ zgbsv
# define zgbsvx_ zgbsvx
# define zgbtf2_ zgbtf2
# define zgbtrf_ zgbtrf
# define zgbtrs_ zgbtrs
# define zgebak_ zgebak
# define zgebal_ zgebal
# define zgebd2_ zgebd2
# define zgebrd_ zgebrd
# define zgecon_ zgecon
# define zgeequ_ zgeequ
# define zgees_ zgees
# define zgeesx_ zgeesx
# define zgeev_ zgeev
# define zgeevx_ zgeevx
# define zgegs_ zgegs
# define zgegv_ zgegv
# define zgehd2_ zgehd2
# define zgehrd_ zgehrd
# define zgelq2_ zgelq2
# define zgelqf_ zgelqf
# define zgels_ zgels
# define zgelsx_ zgelsx
# define zgelsy_ zgelsy
# define zgeql2_ zgeql2
# define zgeqlf_ zgeqlf
# define zgeqp3_ zgeqp3
# define zgeqpf_ zgeqpf
# define zgeqr2_ zgeqr2
# define zgeqrf_ zgeqrf
# define zgerfs_ zgerfs
# define zgerq2_ zgerq2
# define zgerqf_ zgerqf
# define zgesc2_ zgesc2
# define zgesv_ zgesv
# define zgesvx_ zgesvx
# define zgetc2_ zgetc2
# define zgetf2_ zgetf2
# define zgetrf_ zgetrf
# define zgetri_ zgetri
# define zgetrs_ zgetrs
# define zggbak_ zggbak
# define zggbal_ zggbal
# define zgges_ zgges
# define zggesx_ zggesx
# define zggev_ zggev
# define zggevx_ zggevx
# define zggglm_ zggglm
# define zgghrd_ zgghrd
# define zgglse_ zgglse
# define zggqrf_ zggqrf
# define zggrqf_ zggrqf
# define zggsvd_ zggsvd
# define zggsvp_ zggsvp
# define zgtcon_ zgtcon
# define zgtrfs_ zgtrfs
# define zgtsv_ zgtsv
# define zgtsvx_ zgtsvx
# define zgttrf_ zgttrf
# define zgttrs_ zgttrs
# define zgtts2_ zgtts2
# define zhbev_ zhbev
# define zhbevd_ zhbevd
# define zhbevx_ zhbevx
# define zhbgst_ zhbgst
# define zhbgv_ zhbgv
# define zhbgvx_ zhbgvx
# define zhbtrd_ zhbtrd
# define zhecon_ zhecon
# define zheev_ zheev
# define zheevd_ zheevd
# define zheevr_ zheevr
# define zheevx_ zheevx
# define zhegs2_ zhegs2
# define zhegst_ zhegst
# define zhegv_ zhegv
# define zhegvd_ zhegvd
# define zhegvx_ zhegvx
# define zherfs_ zherfs
# define zhesv_ zhesv
# define zhesvx_ zhesvx
# define zhetf2_ zhetf2
# define zhetrd_ zhetrd
# define zhetrf_ zhetrf
# define zhetri_ zhetri
# define zhetrs_ zhetrs
# define zhgeqz_ zhgeqz
# define zhpcon_ zhpcon
# define zhpev_ zhpev
# define zhpevd_ zhpevd
# define zhpevx_ zhpevx
# define zhpgst_ zhpgst
# define zhpgv_ zhpgv
# define zhpgvd_ zhpgvd
# define zhpgvx_ zhpgvx
# define zhprfs_ zhprfs
# define zhpsv_ zhpsv
# define zhpsvx_ zhpsvx
# define zhptrd_ zhptrd
# define zhptrf_ zhptrf
# define zhptri_ zhptri
# define zhptrs_ zhptrs
# define zhsein_ zhsein
# define zhseqr_ zhseqr
# define zlabrd_ zlabrd
# define zlacgv_ zlacgv
# define zlacon_ zlacon
# define zlacp2_ zlacp2
# define zlacpy_ zlacpy
# define zlacrm_ zlacrm
# define zlacrt_ zlacrt
# define zlaed0_ zlaed0
# define zlaed7_ zlaed7
# define zlaed8_ zlaed8
# define zlaein_ zlaein
# define zlaesy_ zlaesy
# define zlaev2_ zlaev2
# define zlags2_ zlags2
# define zlagtm_ zlagtm
# define zlahef_ zlahef
# define zlahqr_ zlahqr
# define zlahrd_ zlahrd
# define zlaic1_ zlaic1
# define zlals0_ zlals0
# define zlalsa_ zlalsa
# define zlapll_ zlapll
# define zlapmt_ zlapmt
# define zlaqgb_ zlaqgb
# define zlaqge_ zlaqge
# define zlaqhb_ zlaqhb
# define zlaqhe_ zlaqhe
# define zlaqhp_ zlaqhp
# define zlaqp2_ zlaqp2
# define zlaqps_ zlaqps
# define zlaqsb_ zlaqsb
# define zlaqsp_ zlaqsp
# define zlaqsy_ zlaqsy
# define zlar1v_ zlar1v
# define zlar2v_ zlar2v
# define zlarcm_ zlarcm
# define zlarf_ zlarf
# define zlarfb_ zlarfb
# define zlarfg_ zlarfg
# define zlarft_ zlarft
# define zlarfx_ zlarfx
# define zlargv_ zlargv
# define zlarnv_ zlarnv
# define zlarrv_ zlarrv
# define zlartg_ zlartg
# define zlartv_ zlartv
# define zlarz_ zlarz
# define zlarzb_ zlarzb
# define zlarzt_ zlarzt
# define zlascl_ zlascl
# define zlaset_ zlaset
# define zlasr_ zlasr
# define zlassq_ zlassq
# define zlaswp_ zlaswp
# define zlasyf_ zlasyf
# define zlatbs_ zlatbs
# define zlatdf_ zlatdf
# define zlatps_ zlatps
# define zlatrd_ zlatrd
# define zlatrs_ zlatrs
# define zlatrz_ zlatrz
# define zlatzm_ zlatzm
# define zlauu2_ zlauu2
# define zlauum_ zlauum
# define zpbcon_ zpbcon
# define zpbequ_ zpbequ
# define zpbrfs_ zpbrfs
# define zpbstf_ zpbstf
# define zpbsv_ zpbsv
# define zpbsvx_ zpbsvx
# define zpbtf2_ zpbtf2
# define zpbtrf_ zpbtrf
# define zpbtrs_ zpbtrs
# define zpocon_ zpocon
# define zpoequ_ zpoequ
# define zporfs_ zporfs
# define zposv_ zposv
# define zposvx_ zposvx
# define zpotf2_ zpotf2
# define zpotrf_ zpotrf
# define zpotri_ zpotri
# define zpotrs_ zpotrs
# define zppcon_ zppcon
# define zppequ_ zppequ
# define zpprfs_ zpprfs
# define zppsv_ zppsv
# define zppsvx_ zppsvx
# define zpptrf_ zpptrf
# define zpptri_ zpptri
# define zpptrs_ zpptrs
# define zptcon_ zptcon
# define zptrfs_ zptrfs
# define zptsv_ zptsv
# define zptsvx_ zptsvx
# define zpttrf_ zpttrf
# define zpttrs_ zpttrs
# define zptts2_ zptts2
# define zrot_ zrot
# define zspcon_ zspcon
# define zspmv_ zspmv
# define zspr_ zspr
# define zsprfs_ zsprfs
# define zspsv_ zspsv
# define zspsvx_ zspsvx
# define zsptrf_ zsptrf
# define zsptri_ zsptri
# define zsptrs_ zsptrs
# define zstedc_ zstedc
# define zstein_ zstein
# define zsteqr_ zsteqr
# define zsycon_ zsycon
# define zsymv_ zsymv
# define zsyr_ zsyr
# define zsyrfs_ zsyrfs
# define zsysv_ zsysv
# define zsysvx_ zsysvx
# define zsytf2_ zsytf2
# define zsytrf_ zsytrf
# define zsytri_ zsytri
# define zsytrs_ zsytrs
# define ztbcon_ ztbcon
# define ztbrfs_ ztbrfs
# define ztbtrs_ ztbtrs
# define ztgevc_ ztgevc
# define ztgex2_ ztgex2
# define ztgexc_ ztgexc
# define ztgsen_ ztgsen
# define ztgsja_ ztgsja
# define ztgsna_ ztgsna
# define ztgsy2_ ztgsy2
# define ztgsyl_ ztgsyl
# define ztpcon_ ztpcon
# define ztprfs_ ztprfs
# define ztptri_ ztptri
# define ztptrs_ ztptrs
# define ztrcon_ ztrcon
# define ztrevc_ ztrevc
# define ztrexc_ ztrexc
# define ztrrfs_ ztrrfs
# define ztrsen_ ztrsen
# define ztrsna_ ztrsna
# define ztrsyl_ ztrsyl
# define ztrti2_ ztrti2
# define ztrtri_ ztrtri
# define ztrtrs_ ztrtrs
# define ztzrqf_ ztzrqf
# define ztzrzf_ ztzrzf
# define zung2l_ zung2l
# define zung2r_ zung2r
# define zungbr_ zungbr
# define zunghr_ zunghr
# define zungl2_ zungl2
# define zunglq_ zunglq
# define zungql_ zungql
# define zungqr_ zungqr
# define zungr2_ zungr2
# define zungrq_ zungrq
# define zungtr_ zungtr
# define zunm2l_ zunm2l
# define zunm2r_ zunm2r
# define zunmbr_ zunmbr
# define zunmhr_ zunmhr
# define zunml2_ zunml2
# define zunmlq_ zunmlq
# define zunmql_ zunmql
# define zunmqr_ zunmqr
# define zunmr2_ zunmr2
# define zunmr3_ zunmr3
# define zunmrq_ zunmrq
# define zunmrz_ zunmrz
# define zunmtr_ zunmtr
# define zupgtr_ zupgtr
# define zupmtr_ zupmtr
# include "mkl_lapack.h"
#else // else use lapack
# include "f2c.h"
# include "clapack.h"
#endif // USE_MKL
  }

#ifdef min
# undef min
#endif // min

#ifdef max
# undef max
#endif // max

#ifdef WIN32
# define min _cpp_min
# define max _cpp_max
#endif // WIN32
