/* Begin CVS Header
   $Source: /Volumes/Home/Users/shoops/cvs/copasi_dev/copasi/Attic/LicenseUS.txt.h,v $
   $Revision: 1.2 $
   $Name:  $
   $Author: shoops $ 
   $Date: 2006/02/14 14:35:19 $
   End CVS Header */

extern const char * CopasiLicense =
    "\n"
    "                        Non-Commercial Purpose License\n"
    "\n"
    "\n"
    "Copyright © 2005 by Pedro Mendes, Virginia Tech Intellectual\n"
    "Properties, Inc. and EML Research, gGmbH.\n"
    "All rights reserved.\n"
    "\n"
    "Virginia Tech Intellectual Properties, Inc (VTIP) and and EML\n"
    "Research, gGmbH (EML) Research own the COPASI software and its\n"
    "associated documentation (\"Software\").  You should carefully read the\n"
    "following terms and conditions before using this software.  Your use\n"
    "of this Software indicates your acceptance of this license agreement\n"
    "and all terms and conditions.\n"
    "\n"
    "The main authors of COPASI are Pedro Mendes, Stefan Hoops, Sven Sahle,\n"
    "Ralph Gauges, and Ursula Kummer. This software has been made possible\n"
    "with the dedicated support of a large number of graduate students at\n"
    "VBI and EML.\n"
    "\n"
    "You are hereby granted a non-exclusive and non-transferable license to\n"
    "use and distribute the Software in both source and binary form\n"
    "according to the following terms and conditions.  This license is to\n"
    "use the Software for Non-Commercial Purpose only.  Non-Commercial\n"
    "Purpose means the use of the Software solely for internal\n"
    "non-commercial research and academic purposes.  Non-Commercial Purpose\n"
    "excludes, without limitation, any use of the Software, as part of, or\n"
    "in any way in connection with a product or service which is sold,\n"
    "offered for sale, licensed, leased, loaned, or rented.  Permission to\n"
    "use, copy, modify, and distribute this compilation for Non- Commercial\n"
    "Purpose is hereby granted without fee, subject to the following terms\n"
    "of this license.  Only verbatim, complete, and unmodified versions of\n"
    "this software (in either binary or source code form) are permitted to\n"
    "be redistributed under this license.\n"
    "\n"
    "\n"
    "1) Copies and Modifications\n"
    "\n"
    "    You must include the above copyright notice and this license on\n"
    "    any copy or modification of this compilation.  Each time you\n"
    "    redistribute this Software, the recipient automatically receives a\n"
    "    license to copy, distribute or modify the Software subject to\n"
    "    these terms and conditions.  You may not impose any further\n"
    "    restrictions on this Software or any derivative works beyond those\n"
    "    restrictions herein.\n"
    "\n"
    "    Any inquiries and comments regarding bugs, bug fixes, enhancements,\n"
    "    modifications or any other similar issues should be directed to:\n"
    "    bugs@copasi.org.\n"
    "\n"
    "\n"
    "2) Commercial Use\n"
    "\n"
    "    If you desire to use the software for profit-making or commercial\n"
    "    purposes, you agree to negotiate in good faith a license with VTIP\n"
    "    and EML prior to such profit-making or commercial use.  VTIP and\n"
    "    EML shall have no obligation to grant such license to you, and may\n"
    "    grant exclusive or non-exclusive licenses to others. You agree to\n"
    "    notify VTIP and EML of any inquiries you have for commercial use\n"
    "    of the Software and/or its modifications. You may contact the\n"
    "    following email to discuss commercial use: license@copasi.org\n"
    "\n"
    "\n"
    "3) Governing Law\n"
    "\n"
    "    This agreement shall be governed by the laws of the Commonwealth of\n"
    "    Virginia.\n"
    "\n"
    "\n"
    "4) Disclaimer of Warranty\n"
    "\n"
    "    Because this software is licensed free of charge, there is no\n"
    "    warranty for the program.  VTIP and EML make no warranty or\n"
    "    representation that the operation of the software in this\n"
    "    compilation will be error-free, and VTIP and EML are under no\n"
    "    obligation to provide any services, by way of maintenance, update,\n"
    "    or otherwise.\n"
    "\n"
    "    THIS SOFTWARE AND THE ACCOMPANYING FILES ARE LICENSED \"AS IS\" AND\n"
    "    WITHOUT WARRANTIES AS TO PERFORMANCE OR MERCHANTABILITY OR ANY\n"
    "    OTHER WARRANTIES WHETHER EXPRESSED OR IMPLIED.  NO WARRANTY OF\n"
    "    FITNESS FOR A PARTICULAR PURPOSE IS OFFERED.  THE ENTIRE RISK AS\n"
    "    TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD\n"
    "    THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY\n"
    "    SERVICING, REPAIR OR CORRECTION.\n"
    "\n"
    "\n"
    "5) Limitation of Liability\n"
    "\n"
    "    IN NO EVENT WILL VTIP AND EML RESEARCH, OR ANY OTHER PARTY WHO MAY\n"
    "    MODIFY AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE\n"
    "    LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL,\n"
    "    INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR\n"
    "    INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF\n"
    "    DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU\n"
    "    OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY\n"
    "    OTHER PROGRAMS), EVEN IF VTIP AND EML RESEARCH OR OTHER PARTY HAS\n"
    "    BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n"
    "\n"
    "    Termination\n"
    "        This agreement is effective until terminated.  You may\n"
    "        terminate this agreement at any time by destroying all copies\n"
    "        of the software and other associated materials (e.g.,\n"
    "        documentation) in your possession.  This agreement will\n"
    "        terminate immediately without notice from VTIP and EML\n"
    "        Research if you fail to comply with any of the terms and\n"
    "        conditions of this license.  Upon termination, you must\n"
    "        destroy all copies of the software and other associated\n"
    "        materials.  This agreement will also terminate immediately\n"
    "        with out notice from VTIP and EML if it is found to implement\n"
    "        patented algorithms or contain copyrighted code not owned or\n"
    "        licensed to VTIP and EML for the purpose of its inclusion in\n"
    "        the COPASI software.  This agreement cannot be terminated by\n"
    "        any other mechanism or for any other reason than those stated\n"
    "        herein.\n"
    "\n"
    "    Use of Names\n"
    "        Users will not use the name of the Virginia Polytechnic\n"
    "        Institute and State University, Virginia Bioinformatics\n"
    "        Institute, Virginia Tech Intellectual Properties, Inc., EML\n"
    "        Research, and COPASI nor any adaptation thereof in any\n"
    "        publicity or advertising, without the prior written consent\n"
    "        from VTIP and EML Research, gGmbH in each case.\n"
    "\n"
    "\n"
    "6) Export License\n"
    "\n"
    "    Export of this software from the United States may require a\n"
    "    specific license from the United States Government.  It is the\n"
    "    responsibility of any person or organization contemplating export\n"
    "    to obtain such a license before exporting.\n"
    "\n"
    "\n"
    "7) END OF TERMS AND CONDITIONS\n"
    "\n"
    "    Address all correspondence regarding this license to electronic mail\n"
    "    address:  license@copasi.org\n"
;
