/* Begin CVS Header
   $Source: /Volumes/Home/Users/shoops/cvs/copasi_dev/copasi/Attic/LicenseCOM.txt.h,v $
   $Revision: 1.1 $
   $Name:  $
   $Author: shoops $
   $Date: 2006/12/08 17:23:33 $
   End CVS Header */

// Copyright © 2006 by Pedro Mendes, Virginia Tech Intellectual
// Properties, Inc. and EML Research, gGmbH.
// All rights reserved.

extern const char * CopasiLicense =
    "\n"
    "           Non-Exclusive Software License Agreement\n"
    "\n"
    "\n"
    "Virginia Tech Intellectual Properties, Inc (VTIP) and EML Research\n"
    "gGmbH (EML) (referred to collectively as \"Owners\") own the COPASI\n"
    "software and its associated documentation (\"Software\"). For the\n"
    "purpose of this license VTIP functions as the point of contact to the\n"
    "Owners. You should carefully read the following terms and conditions\n"
    "before using this Software. Your use of this Software indicates your\n"
    "acceptance of this license agreement and all terms and conditions.\n"
    "\n"
    "1) Background\n"
    "\n"
    "    The Owners desire to distribute research software in furtherance\n"
    "    of their public interest mission.  Licensee desires to use the\n"
    "    Software only at its own company or at its facilities for internal\n"
    "    business purposes or for performing its own - including commercial\n"
    "    - research. In particular, Licensee shall not allow any third\n"
    "    party access to the Software for business or research purposes of\n"
    "    third parties.  The Software is licensed, not sold.\n"
    "\n"
    "2) Definitions\n"
    "\n"
    "    \"Agreement\" means this Non-Exclusive Software License Agreement\n"
    "    and attachments.\n"
    "\n"
    "    \"Effective Date\" means the latest date upon which this Agreement\n"
    "    is executed.\n"
    "\n"
    "    \"License Fee\" means the amounts due by Licensee to owners under\n"
    "    Attachment A.\n"
    "\n"
    "    \"Modifications\" mean any changes or extensions introduced into the\n"
    "    Software or otherwise based on or derived from the Software source\n"
    "    statements. Modifications may include, but are not limited to,\n"
    "    corrections of program errors, translations and stylistic\n"
    "    restructuring of the Software, addition or deletion of functions\n"
    "    or enhancement of existing functions of the Software, and changes\n"
    "    or additions required to integrate the Software into other\n"
    "    applications.\n"
    "\n"
    "    \"Technical Contact\" means the individual authorized by Licensee to\n"
    "    receive the Software and conduct all technical correspondence with\n"
    "    the Owners.\n"
    "\n"
    "2) Grant\n"
    "\n"
    "    Commencing on the Effective Date, and subject to the provisions\n"
    "    herein, the Owners hereby grants to Licensee, and Licensee\n"
    "    accepts, a limited, non-exclusive license to install and use the\n"
    "    software on any single computer, provided the Software is in use\n"
    "    on only one computer at any time. If the Software is permanently\n"
    "    installed on the hard disk or other storage device of a computer\n"
    "    (other than a network server) and one person uses that computer\n"
    "    more than 80% of the time, then that person may also use the\n"
    "    Software on a portable or home computer.  In the event the\n"
    "    Software is loaded into a server computer, a separate license must\n"
    "    be acquired for each user of the server who has access to the\n"
    "    software, whether or not the server has been programmed or\n"
    "    otherwise set up to only allow access to one or other limited\n"
    "    numbers of users at a time. The license granted herein allows the\n"
    "    Licensee access to enhancements or updates of the Software by the\n"
    "    Owners for a period of 12 month starting at the Effective.  All\n"
    "    rights not expressly granted herein are reserved by the Owners.\n"
    "    Licensee shall not distribute or otherwise transfer or allow to be\n"
    "    transferred, the Software or any Modifications or copies thereof,\n"
    "    in whole or in part, without prior written permission of the\n"
    "    Owners.\n"
    "\n"
    "3) Use of Names\n"
    "\n"
    "    Users will not use the name of the Virginia Polytechnic Institute\n"
    "    and State University, Virginia Bioinformatics Institute, Virginia\n"
    "    Tech Intellectual Properties, Inc., EML Research, and COPASI nor\n"
    "    any adaptation thereof in any publicity or advertising, without\n"
    "    the prior written consent from the Owners in each case.\n"
    "\n"
    "4) Attribution\n"
    "\n"
    "    Licensee shall cite the COPASI program when Licensee publishes\n"
    "    research utilizing or based on the Software.\n"
    "\n"
    "5) Payment\n"
    "\n"
    "    Licensee shall pay to Owners the License Fee, due and payable upon\n"
    "    execution of this Agreement\n"
    "\n"
    "6) Delivery\n"
    "\n"
    "    Owners shall provide Licensee access to the Software by means of\n"
    "    internet transmission following execution of this Agreement and\n"
    "    receipt of payment specified herein.\n"
    "\n"
    "7) Term\n"
    "\n"
    "    This Agreement shall remain effective until terminated as set\n"
    "    forth herein.\n"
    "\n"
    "8) Termination\n"
    "\n"
    "    Licensee may terminate this Agreement at any time upon written\n"
    "    notice to the Owners. The Owners may terminate this Agreement upon\n"
    "    notice if Licensee is in material breach of this Agreement and\n"
    "    fails within thirty (30) days of a written demand for performance\n"
    "    to cure such breach.  The provisions under which this Agreement\n"
    "    may be terminated will be in addition to any and all other legal\n"
    "    remedies which either party may have for the enforcement of any\n"
    "    and all terms hereof, and do not in any way limit any other legal\n"
    "    remedy such party may have.  Termination of this Agreement will\n"
    "    terminate all rights and licenses granted to Licensee relating to\n"
    "    the Software and Restricted Patent Rights. Licensee shall certify\n"
    "    in writing to the Owners within ten (10) days after termination\n"
    "    that the Software and all copies thereof have been destroyed.\n"
    "\n"
    "9) Disclaimers\n"
    "\n"
    "    The Software has been developed as part of research conducted at\n"
    "    the Virginia Polytechnic Institute and State University and EML\n"
    "    Research and is provided as a research courtesy. The Software is\n"
    "    experimental in nature and is available \"AS IS\", without\n"
    "    obligation by the Owners to provide Licensee services or support\n"
    "    except as specified in this Agreement. The entire risk as to the\n"
    "    quality and performance of the Software is with Licensee.\n"
    "\n"
    "    THE OWNERS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES, WHETHER\n"
    "    EXPRESS OR IMPLIED, PERTAINING TO THE MERCHANTABILITY,\n"
    "    NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE OF THE\n"
    "    SOFTWARE DISCLOSED OR OTHERWISE PROVIDED TO LICENSEE UNDER THIS\n"
    "    AGREEMENT.\n"
    "\n"
    "10) Indemnification\n"
    "\n"
    "    Licensee shall indemnify and hold harmless the Owners, and their\n"
    "    officers, Software developers, employees, students and agents,\n"
    "    against any and all claims, suits, losses, damages, costs, fees\n"
    "    and expenses resulting from Licensee’s possession and/or use of\n"
    "    the Software, including but not limited to any damages, losses or\n"
    "    liabilities whatsoever with respect to death or injury to any\n"
    "    person and damage to any property. This indemnification clause\n"
    "    shall survive the termination of this Agreement.\n"
    "\n"
    "11) General\n"
    "\n"
    "    This agreement shall be governed by the laws of the Commonwealth\n"
    "    of Virginia.\n"
    "\n"
    "    No omission or delay of either party hereto in requiring due and\n"
    "    punctual fulfillment of the obligations of any other party hereto\n"
    "    shall be deemed to constitute a waiver by such party of its rights\n"
    "    to require such due and punctual fulfillment, or of any other of\n"
    "    its remedies hereunder. Amendments to this Agreement must be in\n"
    "    writing, reference this Agreement, and must be signed by duly\n"
    "    authorized representatives of the Owners and Licensee.\n"
    "\n"
    "    If any provision of this Agreement shall be held to be invalid,\n"
    "    illegal or unenforceable, the validity, legality, and\n"
    "    enforceability of the remaining provisions will not be in any way\n"
    "    affected or impaired thereby.\n"
    "\n"
    "    This Agreement and the rights and benefits conferred upon Licensee\n"
    "    hereunder may not be assigned or otherwise transferred by Licensee\n"
    "    without the prior written consent of the Owners.  In the event\n"
    "    either party hereto is prevented from or delayed in the\n"
    "    performance of any of its obligations hereunder by reason of acts\n"
    "    of God, war, strikes, riots, storms, fires or any other cause\n"
    "    whatsoever beyond the reasonable control of the non-performing\n"
    "    party, the non-performing party shall be excused from the\n"
    "    performance of any such obligation to the extent and during the\n"
    "    period of such prevention or delay.\n"
    "\n"
    "    This Agreement embodies the entire understanding of the parties\n"
    "    and supersedes all previous communications, representations, or\n"
    "    understandings, either oral or written, between the parties\n"
    "    relating to the subject matter hereof.\n"
    "\n"
    "END OF TERMS AND CONDITIONS\n"
    "\n"
    "    Address all correspondence regarding this license to electronic\n"
    "    mail address: license@copasi.org\n"
;
