// Begin CVS Header
//   $Source: /Volumes/Home/Users/shoops/cvs/copasi_dev/copasi/report/ArtisticLicense.h,v $
//   $Revision: 1.1 $
//   $Name:  $
//   $Author: shoops $
//   $Date: 2010/09/22 13:21:10 $
// End CVS Header

// Copyright (C) 2010 by Pedro Mendes, Virginia Tech Intellectual
// Properties, Inc., University of Heidelberg, and The University
// of Manchester.
// All rights reserved.

#ifndef COPASI_LICENSE
#define COPASI_LICENSE

const char * CopasiLicenseTxt =
  "\n"
  "Artistic License 2.0\n"
  "\n"
  "\n"
  "Copyright (c) 2000-2006, The Perl Foundation.\n"
  "\n"
  "Everyone is permitted to copy and distribute verbatim copies of this\n"
  "license document, but changing it is not allowed.\n"
  "\n"
  "Preamble\n"
  "\n"
  "This license establishes the terms under which a given free software\n"
  "Package may be copied, modified, distributed, and/or\n"
  "redistributed. The intent is that the Copyright Holder maintains some\n"
  "artistic control over the development of that Package while still\n"
  "keeping the Package available as open source and free software.\n"
  "\n"
  "You are always permitted to make arrangements wholly outside of this\n"
  "license directly with the Copyright Holder of a given Package. If the\n"
  "terms of this license do not permit the full use that you propose to\n"
  "make of the Package, you should contact the Copyright Holder and seek\n"
  "a different licensing arrangement.\n"
  "\n"
  "Definitions\n"
  "\n"
  "\"Copyright Holder\" means the individual(s) or organization(s) named\n"
  "in the copyright notice for the entire Package.\n"
  "\n"
  "\"Contributor\" means any party that has contributed code or other\n"
  "material to the Package, in accordance with the Copyright Holder's\n"
  "procedures.\n"
  "\n"
  "\"You\" and \"your\" means any person who would like to copy,\n"
  "distribute, or modify the Package.\n"
  "\n"
  "\"Package\" means the collection of files distributed by the Copyright\n"
  "Holder, and derivatives of that collection and/or of those files. A\n"
  "given Package may consist of either the Standard Version, or a\n"
  "Modified Version.\n"
  "\n"
  "\"Distribute\" means providing a copy of the Package or making it\n"
  "accessible to anyone else, or in the case of a company or\n"
  "organization, to others outside of your company or organization.\n"
  "\n"
  "\"Distributor Fee\" means any fee that you charge for Distributing\n"
  "this Package or providing support for this Package to another\n"
  "party. It does not mean licensing fees.\n"
  "\n"
  "\"Standard Version\" refers to the Package if it has not been\n"
  "modified, or has been modified only in ways explicitly requested by\n"
  "the Copyright Holder.\n"
  "\n"
  "\"Modified Version\" means the Package, if it has been changed, and\n"
  "such changes were not explicitly requested by the Copyright Holder.\n"
  "\n"
  "\"Original License\" means this Artistic License as Distributed with\n"
  "the Standard Version of the Package, in its current version or as it\n"
  "may be modified by The Perl Foundation in the future.\n"
  "\n"
  "\"Source\" form means the source code, documentation source, and\n"
  "configuration files for the Package.\n"
  "\n"
  "\"Compiled\" form means the compiled bytecode, object code, binary, or\n"
  "any other form resulting from mechanical transformation or translation\n"
  "of the Source form.\n"
  "\n"
  "Permission for Use and Modification Without Distribution\n"
  "\n"
  "(1) You are permitted to use the Standard Version and create and use\n"
  "    Modified Versions for any purpose without restriction, provided\n"
  "    that you do not Distribute the Modified Version.\n"
  "\n"
  "Permissions for Redistribution of the Standard Version\n"
  "\n"
  "(2) You may Distribute verbatim copies of the Source form of the\n"
  "    Standard Version of this Package in any medium without\n"
  "    restriction, either gratis or for a Distributor Fee, provided that\n"
  "    you duplicate all of the original copyright notices and associated\n"
  "    disclaimers. At your discretion, such verbatim copies may or may\n"
  "    not include a Compiled form of the Package.\n"
  "\n"
  "(3) You may apply any bug fixes, portability changes, and other\n"
  "    modifications made available from the Copyright Holder. The\n"
  "    resulting Package will still be considered the Standard Version,\n"
  "    and as such be subject to the Original License.\n"
  "\n"
  "Distribution of Modified Versions of the Package as Source\n"
  "\n"
  "(4) You may Distribute your Modified Version as Source (either gratis\n"
  "    or for a Distributor Fee, and with or without a Compiled form of\n"
  "    the Modified Version) provided that you clearly document how it\n"
  "    differs from the Standard Version, including, but not limited to,\n"
  "    documenting any non-standard features, executables, or modules,\n"
  "    and provided that you do at least ONE of the following:\n"
  "\n"
  "    (a) make the Modified Version available to the Copyright Holder of\n"
  "        the Standard Version, under the Original License, so that the\n"
  "        Copyright Holder may include your modifications in the\n"
  "        Standard Version.\n"
  "\n"
  "    (b) ensure that installation of your Modified Version does not\n"
  "        prevent the user installing or running the Standard\n"
  "        Version. In addition, the Modified Version must bear a name\n"
  "        that is different from the name of the Standard Version.\n"
  "\n"
  "    (c) allow anyone who receives a copy of the Modified Version to\n"
  "        make the Source form of the Modified Version available to\n"
  "        others under\n"
  "\n"
  "        (i) the Original License or\n"
  "\n"
  "        (ii) a license that permits the licensee to freely copy,\n"
  "             modify and redistribute the Modified Version using the\n"
  "             same licensing terms that apply to the copy that the\n"
  "             licensee received, and requires that the Source form of\n"
  "             the Modified Version, and of any works derived from it,\n"
  "             be made freely available in that license fees are\n"
  "             prohibited but Distributor Fees are allowed.\n"
  "\n"
  "Distribution of Compiled Forms of the Standard Version or Modified\n"
  "Versions without the Source\n"
  "\n"
  "(5) You may Distribute Compiled forms of the Standard Version without\n"
  "    the Source, provided that you include complete instructions on how\n"
  "    to get the Source of the Standard Version. Such instructions must\n"
  "    be valid at the time of your distribution. If these instructions,\n"
  "    at any time while you are carrying out such distribution, become\n"
  "    invalid, you must provide new instructions on demand or cease\n"
  "    further distribution. If you provide valid instructions or cease\n"
  "    distribution within thirty days after you become aware that the\n"
  "    instructions are invalid, then you do not forfeit any of your\n"
  "    rights under this license.\n"
  "\n"
  "(6) You may Distribute a Modified Version in Compiled form without the\n"
  "    Source, provided that you comply with Section 4 with respect to the\n"
  "    Source of the Modified Version.\n"
  "\n"
  "Aggregating or Linking the Package\n"
  "\n"
  "(7) You may aggregate the Package (either the Standard Version or\n"
  "    Modified Version) with other packages and Distribute the resulting\n"
  "    aggregation provided that you do not charge a licensing fee for\n"
  "    the Package. Distributor Fees are permitted, and licensing fees\n"
  "    for other components in the aggregation are permitted. The terms\n"
  "    of this license apply to the use and Distribution of the Standard\n"
  "    or Modified Versions as included in the aggregation.\n"
  "\n"
  "(8) You are permitted to link Modified and Standard Versions with\n"
  "    other works, to embed the Package in a larger work of your own, or\n"
  "    to build stand-alone binary or bytecode versions of applications\n"
  "    that include the Package, and Distribute the result without\n"
  "    restriction, provided the result does not expose a direct\n"
  "    interface to the Package.\n"
  "\n"
  "Items That are Not Considered Part of a Modified Version\n"
  "\n"
  "(9) Works (including, but not limited to, modules and scripts) that\n"
  "    merely extend or make use of the Package, do not, by themselves,\n"
  "    cause the Package to be a Modified Version. In addition, such\n"
  "    works are not considered parts of the Package itself, and are not\n"
  "    subject to the terms of this license.\n"
  "\n"
  "General Provisions\n"
  "\n"
  "(10) Any use, modification, and distribution of the Standard or\n"
  "     Modified Versions is governed by this Artistic License. By using,\n"
  "     modifying or distributing the Package, you accept this\n"
  "     license. Do not use, modify, or distribute the Package, if you do\n"
  "     not accept this license.\n"
  "\n"
  "(11) If your Modified Version has been derived from a Modified Version\n"
  "     made by someone other than you, you are nevertheless required to\n"
  "     ensure that your Modified Version complies with the requirements\n"
  "     of this license.\n"
  "\n"
  "(12) This license does not grant you the right to use any trademark,\n"
  "     service mark, tradename, or logo of the Copyright Holder.\n"
  "\n"
  "(13) This license includes the non-exclusive, worldwide,\n"
  "     free-of-charge patent license to make, have made, use, offer to\n"
  "     sell, sell, import and otherwise transfer the Package with\n"
  "     respect to any patent claims licensable by the Copyright Holder\n"
  "     that are necessarily infringed by the Package. If you institute\n"
  "     patent litigation (including a cross-claim or counterclaim)\n"
  "     against any party alleging that the Package constitutes direct or\n"
  "     contributory patent infringement, then this Artistic License to\n"
  "     you shall terminate on the date that such litigation is filed.\n"
  "\n"
  "(14) Disclaimer of Warranty: THE PACKAGE IS PROVIDED BY THE COPYRIGHT\n"
  "     HOLDER AND CONTRIBUTORS \"AS IS\' AND WITHOUT ANY EXPRESS OR\n"
  "     IMPLIED WARRANTIES. THE IMPLIED WARRANTIES OF MERCHANTABILITY,\n"
  "     FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT ARE\n"
  "     DISCLAIMED TO THE EXTENT PERMITTED BY YOUR LOCAL LAW. UNLESS\n"
  "     REQUIRED BY LAW, NO COPYRIGHT HOLDER OR CONTRIBUTOR WILL BE\n"
  "     LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL\n"
  "     DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THE PACKAGE, EVEN IF\n"
  "     ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\"\n"
  "\n"
  ;

const char * CopasiLicenseHtml =
  "<h2>Artistic License 2.0</h2>"
  "<p>"
  "Copyright (c) 2000-2006, The Perl Foundation."
  "</p><p>"
  "Everyone is permitted to copy and distribute verbatim copies of this "
  "license document, but changing it is not allowed. "
  "</p>"
  "<h4>Preamble</h4>"
  "<p>"
  "This license establishes the terms under which a given free software "
  "Package may be copied, modified, distributed, and/or "
  "redistributed. The intent is that the Copyright Holder maintains some "
  "artistic control over the development of that Package while still "
  "keeping the Package available as open source and free software. "
  "</p><p>"
  "You are always permitted to make arrangements wholly outside of this "
  "license directly with the Copyright Holder of a given Package. If the "
  "terms of this license do not permit the full use that you propose to "
  "make of the Package, you should contact the Copyright Holder and seek "
  "a different licensing arrangement. "
  "</p>"
  "<h4>Definitions</h4>"
  "<p>"
  "&quot;Copyright Holder&quot; means the individual(s) or organization(s) named "
  "in the copyright notice for the entire Package. "
  "</p><p>"
  "&quot;Contributor&quot; means any party that has contributed code or other "
  "material to the Package, in accordance with the Copyright Holder's "
  "procedures. "
  "</p><p>"
  "&quot;You&quot; and &quot;your&quot; means any person who would like to copy, "
  "distribute, or modify the Package. "
  "</p><p>"
  "&quot;Package&quot; means the collection of files distributed by the Copyright "
  "Holder, and derivatives of that collection and/or of those files. A "
  "given Package may consist of either the Standard Version, or a "
  "Modified Version. "
  "</p><p>"
  "&quot;Distribute&quot; means providing a copy of the Package or making it "
  "accessible to anyone else, or in the case of a company or "
  "organization, to others outside of your company or organization. "
  "</p><p>"
  "&quot;Distributor Fee&quot; means any fee that you charge for Distributing "
  "this Package or providing support for this Package to another "
  "party. It does not mean licensing fees. "
  "</p><p>"
  "&quot;Standard Version&quot; refers to the Package if it has not been "
  "modified, or has been modified only in ways explicitly requested by "
  "the Copyright Holder. "
  "</p><p>"
  "&quot;Modified Version&quot; means the Package, if it has been changed, and "
  "such changes were not explicitly requested by the Copyright Holder. "
  "</p><p>"
  "&quot;Original License&quot; means this Artistic License as Distributed with "
  "the Standard Version of the Package, in its current version or as it "
  "may be modified by The Perl Foundation in the future. "
  "</p><p>"
  "&quot;Source&quot; form means the source code, documentation source, and "
  "configuration files for the Package. "
  "</p><p>"
  "&quot;Compiled&quot; form means the compiled bytecode, object code, binary, or "
  "any other form resulting from mechanical transformation or translation "
  "of the Source form. "
  "</p>"
  "<h4>Permission for Use and Modification Without Distribution</h4>"
  "<p>"
  "(1) You are permitted to use the Standard Version and create and use "
  "    Modified Versions for any purpose without restriction, provided "
  "    that you do not Distribute the Modified Version. "
  "</p>"
  "<h4>Permissions for Redistribution of the Standard Version</h4>"
  "<p>"
  "(2) You may Distribute verbatim copies of the Source form of the "
  "    Standard Version of this Package in any medium without "
  "    restriction, either gratis or for a Distributor Fee, provided that "
  "    you duplicate all of the original copyright notices and associated "
  "    disclaimers. At your discretion, such verbatim copies may or may "
  "    not include a Compiled form of the Package. "
  "</p><p>"
  "(3) You may apply any bug fixes, portability changes, and other "
  "    modifications made available from the Copyright Holder. The "
  "    resulting Package will still be considered the Standard Version, "
  "    and as such be subject to the Original License. "
  "</p>"
  "<h4>Distribution of Modified Versions of the Package as Source</h4>"
  "<p>"
  "(4) You may Distribute your Modified Version as Source (either gratis "
  "    or for a Distributor Fee, and with or without a Compiled form of "
  "    the Modified Version) provided that you clearly document how it "
  "    differs from the Standard Version, including, but not limited to, "
  "    documenting any non-standard features, executables, or modules, "
  "    and provided that you do at least ONE of the following: "
  "</p><p>"
  "    (a) make the Modified Version available to the Copyright Holder of "
  "        the Standard Version, under the Original License, so that the "
  "        Copyright Holder may include your modifications in the "
  "        Standard Version. "
  "</p><p>"
  "    (b) ensure that installation of your Modified Version does not "
  "        prevent the user installing or running the Standard "
  "        Version. In addition, the Modified Version must bear a name "
  "        that is different from the name of the Standard Version. "
  "</p><p>"
  "    (c) allow anyone who receives a copy of the Modified Version to "
  "        make the Source form of the Modified Version available to "
  "        others under "
  "</p><p>"
  "        (i) the Original License or "
  "</p><p>"
  "        (ii) a license that permits the licensee to freely copy, "
  "             modify and redistribute the Modified Version using the "
  "             same licensing terms that apply to the copy that the "
  "             licensee received, and requires that the Source form of "
  "             the Modified Version, and of any works derived from it, "
  "             be made freely available in that license fees are "
  "             prohibited but Distributor Fees are allowed. "
  "</p>"
  "<h4>Distribution of Compiled Forms of the Standard Version or Modified "
  "Versions without the Source</h4>"
  "<p>"
  "(5) You may Distribute Compiled forms of the Standard Version without "
  "    the Source, provided that you include complete instructions on how "
  "    to get the Source of the Standard Version. Such instructions must "
  "    be valid at the time of your distribution. If these instructions, "
  "    at any time while you are carrying out such distribution, become "
  "    invalid, you must provide new instructions on demand or cease "
  "    further distribution. If you provide valid instructions or cease "
  "    distribution within thirty days after you become aware that the "
  "    instructions are invalid, then you do not forfeit any of your "
  "    rights under this license. "
  "</p><p>"
  "(6) You may Distribute a Modified Version in Compiled form without the "
  "    Source, provided that you comply with Section 4 with respect to the "
  "    Source of the Modified Version. "
  "</p>"
  "<h4>Aggregating or Linking the Package</h4>"
  "<p>"
  "(7) You may aggregate the Package (either the Standard Version or "
  "    Modified Version) with other packages and Distribute the resulting "
  "    aggregation provided that you do not charge a licensing fee for "
  "    the Package. Distributor Fees are permitted, and licensing fees "
  "    for other components in the aggregation are permitted. The terms "
  "    of this license apply to the use and Distribution of the Standard "
  "    or Modified Versions as included in the aggregation. "
  "</p><p>"
  "(8) You are permitted to link Modified and Standard Versions with "
  "    other works, to embed the Package in a larger work of your own, or "
  "    to build stand-alone binary or bytecode versions of applications "
  "    that include the Package, and Distribute the result without "
  "    restriction, provided the result does not expose a direct "
  "    interface to the Package. "
  "</p>"
  "<h4>Items That are Not Considered Part of a Modified Version</h4>"
  "<p>"
  "(9) Works (including, but not limited to, modules and scripts) that "
  "    merely extend or make use of the Package, do not, by themselves, "
  "    cause the Package to be a Modified Version. In addition, such "
  "    works are not considered parts of the Package itself, and are not "
  "    subject to the terms of this license. "
  "</p>"
  "<h4>General Provisions</h4>"
  "<p>"
  "(10) Any use, modification, and distribution of the Standard or "
  "     Modified Versions is governed by this Artistic License. By using, "
  "     modifying or distributing the Package, you accept this "
  "     license. Do not use, modify, or distribute the Package, if you do "
  "     not accept this license. "
  "</p><p>"
  "(11) If your Modified Version has been derived from a Modified Version "
  "     made by someone other than you, you are nevertheless required to "
  "     ensure that your Modified Version complies with the requirements "
  "     of this license. "
  "</p><p>"
  "(12) This license does not grant you the right to use any trademark, "
  "     service mark, tradename, or logo of the Copyright Holder. "
  "</p><p>"
  "(13) This license includes the non-exclusive, worldwide, "
  "     free-of-charge patent license to make, have made, use, offer to "
  "     sell, sell, import and otherwise transfer the Package with "
  "     respect to any patent claims licensable by the Copyright Holder "
  "     that are necessarily infringed by the Package. If you institute "
  "     patent litigation (including a cross-claim or counterclaim) "
  "     against any party alleging that the Package constitutes direct or "
  "     contributory patent infringement, then this Artistic License to "
  "     you shall terminate on the date that such litigation is filed. "
  "</p><p>"
  "(14) Disclaimer of Warranty: THE PACKAGE IS PROVIDED BY THE COPYRIGHT "
  "     HOLDER AND CONTRIBUTORS &quot;AS IS\' AND WITHOUT ANY EXPRESS OR "
  "     IMPLIED WARRANTIES. THE IMPLIED WARRANTIES OF MERCHANTABILITY, "
  "     FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT ARE "
  "     DISCLAIMED TO THE EXTENT PERMITTED BY YOUR LOCAL LAW. UNLESS "
  "     REQUIRED BY LAW, NO COPYRIGHT HOLDER OR CONTRIBUTOR WILL BE "
  "     LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL "
  "     DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THE PACKAGE, EVEN IF "
  "     ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.&quot; "
  "</p>"
  ;
#endif // COPASI_LICENSE
