#!/bin/sh

LIBDIR="$(dirname "$(dirname "$(readlink -f "$0")")")/share/copasi/lib"

CopasiUI="${LIBDIR}/CopasiUI"

QT_MISSING=$(ldd -r "${CopasiUI}" 2>&1 | grep -q '\(undefined symbol:\|libQt.*\.so\.4 => not found\)' && echo true)

if [ _${QT_MISSING} = _true ]; then
  LD_LIBRARY_PATH="${LIBDIR}:${LD_LIBRARY_PATH}"
  export LD_LIBRARY_PATH
fi

"${CopasiUI}" "$@"
