#! /bin/sh
echo $$ called as: $0 $@ >> /home/shoops/projects/copasi_dev/cvs_admin/commit_script.out
my_dir="$1"
shift

for my_file in $@; do
  if [ "`basename $my_file`" != "`basename $my_file .h`" -o \
       "`basename $my_file`" != "`basename $my_file .c`" -o \
       "`basename $my_file`" != "`basename $my_file .cpp`" -o \
       "`basename $my_file`" != "`basename $my_file .hpp`" ]; then
    echo "  processing $my_file" >> /home/shoops/projects/copasi_dev/cvs_admin/commit_script.out

    if [ -e "`basename $my_file`" ]; then
      /home/shoops/projects/copasi_dev/cvs_admin/c++style $my_file
    fi
  fi
done

rm -f *.tmp
