/* Begin CVS Header
   $Source: /Volumes/Home/Users/shoops/cvs/copasi_dev/copasi/function/CEvaluationLexer_lex.cpp,v $
   $Revision: 1.13 $
   $Name:  $
   $Author: shoops $ 
   $Date: 2005/07/28 14:41:57 $
   End CVS Header */

#define yyFlexLexer CEvaluationFlexLexer

#line 4 "CEvaluationLexer_lex.cpp" 
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /Volumes/Home/Users/shoops/cvs/copasi_dev/copasi/function/CEvaluationLexer_lex.cpp,v 1.13 2005/07/28 14:41:57 shoops Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif

#ifdef __cplusplus

#include <stdlib.h>
#include <iostream>
using namespace std;
#ifndef _WIN32
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif /* __STDC__ */
#endif /* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin)

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *  if (condition_holds)
 *  yyless(5);
 * else
 *  do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
 do \
  {\
  /* Undo effects of setting up yytext. */ \
  *yy_cp = yy_hold_char; \
  YY_RESTORE_YY_MORE_OFFSET \
  yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
  YY_DO_BEFORE_ACTION; /* set up yytext again */ \
  } \
 while (0)

#define unput(c) yyunput(c, yytext_ptr)

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;

struct yy_buffer_state
  {
    istream* yy_input_file;

    char *yy_ch_buf;  /* input buffer */
    char *yy_buf_pos;  /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
  };

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer

static void *yy_flex_alloc YY_PROTO((yy_size_t));
static void *yy_flex_realloc YY_PROTO((void *, yy_size_t));
static void yy_flex_free YY_PROTO((void *));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
 {\
 if (! yy_current_buffer) \
  yy_current_buffer = yy_create_buffer(yyin, YY_BUF_SIZE); \
 yy_current_buffer->yy_is_interactive = is_interactive; \
 }

#define yy_set_bol(at_bol) \
 {\
 if (! yy_current_buffer) \
  yy_current_buffer = yy_create_buffer(yyin, YY_BUF_SIZE); \
 yy_current_buffer->yy_at_bol = at_bol; \
 }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include "FlexLexer.h"

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
 yytext_ptr = yy_bp; \
 yyleng = (int) (yy_cp - yy_bp); \
 yy_hold_char = *yy_cp; \
 *yy_cp = '\0'; \
 yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
static yyconst short int yy_accept[478] =
  {0,
    0, 0, 0, 0, 0, 0, 0, 0, 70, 68,
    67, 67, 58, 61, 64, 56, 54, 63, 53, 57,
    1, 68, 66, 66, 66, 66, 66, 66, 66, 66,
    66, 66, 66, 55, 66, 66, 66, 66, 66, 66,
    66, 66, 66, 66, 62, 65, 59, 60, 68, 68,
    68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
    68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
    68, 68, 68, 68, 68, 67, 1, 1, 0, 0,
    17, 0, 52, 66, 66, 66, 66, 66, 66, 66,
    66, 66, 66, 66, 66, 66, 66, 66, 66, 3,

    66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
    66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
    66, 66, 66, 66, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 13, 0, 0, 0, 10, 11,
    0, 0, 8, 0, 9, 12, 16, 3, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 1, 51, 66, 66,
    66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
    66, 50, 66, 66, 7, 66, 66, 66, 66, 66,

    66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
    66, 66, 66, 66, 66, 66, 66, 66, 66, 0,
    0, 14, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    15, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    46, 66, 66, 66, 66, 66, 66, 66, 22, 66,
    26, 66, 25, 66, 20, 66, 66, 66, 66, 66,
    18, 66, 24, 66, 21, 66, 66, 23, 66, 4,
    66, 66, 66, 66, 66, 66, 66, 66, 66, 0,

    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 4,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 34,
    66, 66, 66, 66, 66, 33, 35, 48, 28, 32,
    31, 66, 66, 5, 66, 66, 66, 30, 27, 45,
    29, 66, 66, 66, 66, 66, 66, 66, 66, 0,
    0, 0, 0, 0, 0, 0, 5, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 66, 66,
    66, 66, 66, 66, 66, 66, 47, 66, 19, 66,
    66, 66, 66, 66, 66, 66, 66, 66, 0, 0,

    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 66, 38, 66, 37,
    66, 36, 66, 66, 66, 66, 66, 66, 66, 66,
    66, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 40, 44, 43, 42, 39, 41, 66,
    66, 6, 66, 66, 0, 0, 6, 0, 0, 66,
    66, 66, 0, 0, 0, 66, 49, 66, 0, 0,
    66, 66, 0, 0, 2, 2, 0
  };

static yyconst int yy_ec[256] =
  {0,
    1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
    1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 2, 1, 1, 1, 1, 4, 1, 1, 5,
    6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
    15, 15, 15, 15, 15, 15, 15, 1, 1, 16,
    1, 17, 1, 1, 18, 19, 20, 21, 22, 23,
    24, 25, 26, 27, 27, 28, 27, 29, 30, 31,
    32, 33, 34, 35, 36, 27, 27, 37, 38, 27,
    1, 39, 1, 40, 27, 1, 41, 42, 43, 44,

    45, 46, 47, 48, 49, 27, 27, 50, 27, 51,
    52, 53, 54, 55, 56, 57, 58, 27, 27, 59,
    60, 27, 61, 1, 62, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1
  };

static yyconst int yy_meta[63] =
  {0,
    1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
    1, 1, 2, 2, 2, 1, 1, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    1, 1
  };

static yyconst short int yy_base[481] =
  {0,
    0, 0, 0, 0, 62, 0, 117, 118, 1037, 1038,
    127, 129, 1038, 1038, 1038, 1038, 1038, 1038, 1038, 1038,
    122, 117, 138, 1031, 140, 143, 133, 136, 134, 145,
    137, 155, 161, 1038, 147, 171, 148, 150, 173, 144,
    149, 135, 177, 180, 1038, 1038, 1038, 1038, 209, 1030,
    183, 178, 181, 190, 225, 215, 227, 201, 192, 231,
    228, 234, 235, 206, 193, 254, 236, 250, 255, 260,
    251, 261, 264, 262, 263, 190, 257, 308, 274, 258,
    1038, 1031, 1027, 1027, 280, 268, 306, 294, 311, 319,
    303, 320, 323, 322, 326, 1026, 271, 327, 328, 1025,

    329, 330, 331, 336, 334, 338, 339, 341, 343, 342,
    347, 350, 352, 355, 361, 353, 356, 362, 357, 367,
    364, 363, 366, 368, 1024, 369, 370, 372, 377, 373,
    371, 375, 385, 393, 1023, 381, 411, 416, 1022, 1021,
    1020, 417, 1019, 418, 1018, 1017, 1016, 1015, 423, 419,
    420, 422, 424, 425, 376, 382, 428, 430, 431, 433,
    432, 436, 439, 442, 440, 444, 445, 447, 454, 449,
    450, 451, 452, 456, 453, 449, 456, 1038, 1014, 472,
    479, 460, 474, 473, 482, 483, 499, 504, 480, 507,
    512, 1012, 511, 269, 1012, 513, 514, 515, 518, 522,

    516, 517, 481, 520, 525, 521, 528, 530, 531, 471,
    524, 535, 540, 374, 542, 543, 541, 544, 548, 1011,
    547, 1010, 550, 553, 557, 526, 552, 554, 563, 589,
    560, 562, 592, 594, 595, 596, 598, 597, 599, 603,
    1009, 551, 600, 559, 561, 556, 606, 610, 611, 608,
    609, 612, 613, 621, 622, 623, 624, 625, 626, 628,
    1007, 1007, 633, 629, 630, 1006, 1005, 1004, 1002, 1002,
    1000, 1000, 998, 998, 996, 632, 634, 640, 636, 647,
    995, 637, 994, 994, 992, 992, 991, 989, 989, 988,
    635, 639, 642, 641, 644, 648, 670, 672, 673, 987,

    674, 675, 676, 986, 985, 984, 983, 982, 981, 680,
    684, 685, 693, 690, 697, 980, 979, 978, 977, 976,
    694, 695, 698, 700, 701, 707, 706, 708, 711, 974,
    713, 710, 712, 716, 726, 973, 972, 971, 970, 969,
    968, 715, 723, 968, 967, 717, 966, 964, 963, 962,
    961, 722, 724, 728, 729, 730, 731, 733, 736, 749,
    737, 744, 753, 757, 755, 758, 961, 960, 761, 959,
    760, 763, 764, 767, 768, 765, 769, 784, 770, 787,
    788, 789, 795, 796, 793, 785, 957, 791, 956, 792,
    794, 797, 798, 799, 800, 803, 804, 810, 818, 824,

    825, 826, 827, 830, 829, 831, 833, 822, 823, 832,
    834, 836, 839, 851, 820, 854, 956, 954, 954, 949,
    949, 946, 946, 944, 942, 855, 856, 857, 858, 859,
    860, 941, 940, 939, 938, 937, 936, 861, 867, 868,
    870, 871, 872, 934, 933, 932, 930, 929, 919, 873,
    876, 919, 874, 878, 881, 886, 917, 884, 887, 883,
    914, 888, 892, 913, 889, 893, 557, 898, 903, 900,
    904, 908, 912, 911, 546, 380, 1038, 956, 278, 206
  };

static yyconst short int yy_def[481] =
  {0,
    477, 1, 1, 1, 477, 5, 1, 1, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 478, 479, 479, 479, 479, 479, 479, 479, 479,
    479, 479, 479, 477, 479, 479, 479, 479, 479, 479,
    479, 479, 479, 479, 477, 477, 477, 477, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 477, 477, 477, 477, 478,
    477, 478, 477, 479, 479, 479, 479, 479, 479, 479,
    479, 479, 479, 479, 479, 479, 479, 479, 479, 479,

    479, 479, 479, 479, 479, 479, 479, 479, 479, 479,
    479, 479, 479, 479, 479, 479, 479, 479, 479, 479,
    479, 479, 479, 479, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 477, 477, 477, 477, 479, 479,
    479, 479, 479, 479, 479, 479, 479, 479, 479, 479,
    479, 477, 479, 479, 479, 479, 479, 479, 479, 479,

    479, 479, 479, 479, 479, 479, 479, 479, 479, 479,
    479, 479, 479, 479, 479, 479, 479, 479, 479, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    477, 479, 479, 479, 479, 479, 479, 479, 477, 479,
    477, 479, 477, 479, 477, 479, 479, 479, 479, 479,
    477, 479, 477, 479, 477, 479, 479, 477, 479, 479,
    479, 479, 479, 479, 479, 479, 479, 479, 479, 480,

    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 477,
    479, 479, 479, 479, 479, 477, 477, 477, 477, 477,
    477, 479, 479, 479, 479, 479, 479, 477, 477, 477,
    477, 479, 479, 479, 479, 479, 479, 479, 479, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 480, 480, 479, 479,
    479, 479, 479, 479, 479, 479, 477, 479, 477, 479,
    479, 479, 479, 479, 479, 479, 479, 479, 480, 480,

    480, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 480, 480, 480, 479, 477, 479, 477,
    479, 477, 479, 479, 479, 479, 479, 479, 479, 479,
    479, 480, 480, 480, 480, 480, 480, 480, 480, 480,
    480, 480, 480, 477, 477, 477, 477, 477, 477, 479,
    479, 479, 479, 479, 480, 480, 480, 480, 480, 479,
    479, 479, 480, 480, 480, 479, 477, 479, 480, 480,
    479, 479, 480, 480, 479, 480, 0, 477, 477, 477
  };

static yyconst short int yy_nxt[1101] =
  {0,
    10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
    10, 20, 21, 21, 21, 22, 10, 23, 24, 25,
    24, 26, 27, 24, 24, 28, 24, 29, 30, 24,
    31, 24, 24, 32, 33, 24, 24, 24, 10, 34,
    35, 24, 36, 24, 37, 38, 24, 24, 39, 40,
    41, 24, 42, 24, 24, 43, 44, 24, 24, 24,
    45, 46, 10, 11, 12, 13, 14, 15, 16, 47,
    18, 48, 10, 20, 21, 21, 21, 22, 10, 49,
    50, 51, 50, 52, 53, 54, 50, 55, 50, 56,
    57, 58, 59, 50, 50, 60, 61, 50, 62, 50,

    10, 34, 63, 50, 64, 50, 65, 66, 67, 50,
    68, 69, 70, 71, 72, 50, 50, 73, 74, 50,
    75, 50, 45, 46, 10, 10, 10, 10, 76, 76,
    76, 76, 77, 81, 78, 78, 78, 83, 83, 83,
    83, 83, 83, 79, 83, 24, 24, 83, 83, 83,
    94, 83, 83, 83, 83, 82, 85, 86, 96, 83,
    95, 90, 100, 98, 97, 83, 79, 24, 24, 91,
    87, 88, 89, 92, 99, 83, 101, 83, 104, 93,
    102, 83, 83, 100, 83, 83, 103, 83, 106, 107,
    115, 76, 76, 105, 83, 118, 83, 83, 137, 116,

    119, 108, 109, 110, 132, 83, 114, 125, 138, 135,
    83, 139, 133, 83, 136, 111, 134, 148, 96, 83,
    123, 120, 112, 117, 140, 121, 113, 126, 127, 83,
    122, 83, 83, 147, 124, 83, 143, 128, 83, 83,
    83, 129, 130, 131, 144, 152, 135, 141, 146, 145,
    161, 164, 149, 142, 83, 83, 150, 162, 83, 83,
    153, 163, 151, 154, 83, 83, 83, 83, 83, 175,
    175, 175, 83, 281, 81, 83, 155, 156, 79, 84,
    139, 176, 282, 176, 83, 157, 177, 177, 177, 158,
    159, 160, 140, 193, 165, 141, 82, 180, 83, 143,

    167, 79, 172, 166, 146, 147, 168, 83, 169, 148,
    83, 145, 170, 179, 174, 83, 173, 171, 77, 182,
    78, 78, 78, 83, 83, 181, 83, 83, 183, 79,
    83, 83, 83, 83, 83, 83, 185, 186, 83, 187,
    83, 189, 83, 83, 184, 83, 83, 83, 196, 190,
    194, 83, 79, 188, 83, 191, 83, 83, 197, 83,
    83, 83, 195, 198, 199, 83, 83, 83, 83, 200,
    83, 83, 83, 83, 83, 83, 83, 83, 281, 83,
    83, 83, 204, 202, 83, 83, 83, 299, 225, 83,
    201, 203, 222, 179, 208, 205, 223, 83, 224, 221,

    226, 213, 220, 210, 212, 206, 207, 209, 214, 215,
    211, 230, 229, 195, 216, 83, 218, 217, 227, 228,
    83, 83, 83, 83, 83, 219, 83, 83, 83, 83,
    231, 220, 83, 242, 83, 83, 83, 83, 232, 234,
    83, 235, 236, 83, 83, 233, 83, 237, 83, 83,
    239, 83, 238, 83, 83, 83, 83, 241, 83, 240,
    83, 177, 177, 177, 83, 175, 175, 175, 177, 177,
    177, 222, 243, 245, 79, 83, 83, 83, 83, 244,
    246, 249, 251, 83, 83, 83, 269, 271, 266, 252,
    254, 247, 248, 255, 250, 253, 256, 79, 263, 257,

    268, 259, 267, 273, 258, 262, 270, 272, 275, 260,
    241, 83, 264, 265, 277, 83, 83, 283, 285, 83,
    83, 83, 288, 274, 83, 269, 83, 295, 83, 83,
    83, 266, 271, 276, 273, 275, 280, 284, 286, 83,
    278, 279, 289, 290, 83, 83, 283, 285, 288, 287,
    83, 83, 83, 306, 83, 83, 269, 83, 271, 291,
    83, 83, 178, 83, 83, 83, 83, 273, 270, 301,
    267, 262, 292, 293, 268, 272, 307, 274, 308, 296,
    300, 304, 294, 302, 303, 305, 297, 309, 298, 284,
    286, 289, 290, 275, 311, 312, 83, 287, 83, 281,

    283, 83, 285, 288, 83, 306, 300, 83, 315, 304,
    269, 305, 275, 83, 271, 273, 83, 83, 310, 314,
    316, 313, 317, 319, 320, 83, 281, 283, 285, 83,
    288, 318, 83, 83, 83, 329, 83, 83, 83, 83,
    83, 83, 321, 83, 83, 83, 83, 335, 83, 347,
    333, 83, 83, 307, 334, 322, 323, 308, 309, 324,
    342, 344, 331, 343, 327, 325, 332, 326, 345, 328,
    316, 317, 320, 319, 83, 346, 83, 83, 83, 83,
    83, 318, 356, 354, 83, 347, 352, 355, 83, 83,
    353, 357, 344, 364, 83, 358, 362, 83, 83, 83,

    363, 83, 83, 360, 83, 83, 367, 361, 365, 370,
    83, 83, 83, 366, 83, 83, 83, 83, 369, 83,
    83, 83, 359, 370, 345, 368, 83, 83, 83, 381,
    83, 382, 83, 83, 83, 83, 385, 83, 375, 373,
    83, 83, 388, 374, 383, 371, 379, 380, 83, 372,
    376, 367, 377, 83, 384, 386, 401, 83, 378, 83,
    368, 83, 83, 402, 83, 83, 392, 83, 83, 83,
    393, 83, 83, 83, 83, 396, 405, 390, 391, 394,
    395, 403, 399, 400, 398, 404, 407, 397, 83, 83,
    406, 418, 420, 422, 417, 83, 83, 83, 418, 83,

    83, 420, 422, 83, 83, 410, 411, 83, 83, 414,
    427, 419, 421, 423, 83, 408, 409, 412, 413, 424,
    425, 426, 83, 415, 83, 428, 83, 418, 418, 420,
    422, 83, 416, 83, 83, 83, 420, 83, 422, 417,
    83, 419, 432, 83, 421, 423, 424, 425, 433, 434,
    435, 436, 430, 429, 437, 83, 439, 438, 83, 83,
    83, 83, 83, 83, 83, 83, 431, 440, 442, 432,
    433, 83, 83, 451, 83, 83, 83, 83, 83, 434,
    83, 435, 83, 436, 456, 83, 437, 83, 83, 450,
    83, 83, 83, 83, 452, 455, 83, 83, 460, 454,

    466, 441, 83, 461, 83, 457, 463, 83, 83, 469,
    443, 459, 83, 464, 453, 83, 83, 467, 467, 452,
    471, 83, 462, 83, 178, 475, 458, 461, 468, 470,
    473, 457, 465, 476, 178, 178, 464, 178, 178, 178,
    449, 448, 447, 446, 445, 444, 449, 472, 448, 474,
    447, 178, 475, 446, 178, 476, 80, 80, 445, 178,
    444, 178, 178, 389, 387, 83, 178, 178, 178, 178,
    389, 387, 83, 178, 178, 178, 178, 178, 178, 178,
    83, 351, 350, 349, 348, 341, 340, 339, 338, 337,
    336, 330, 83, 351, 178, 350, 349, 178, 348, 178,

    178, 178, 341, 178, 340, 178, 339, 178, 338, 337,
    336, 330, 178, 83, 83, 261, 83, 178, 261, 83,
    83, 83, 83, 83, 192, 83, 83, 83, 83, 83,
    192, 83, 178, 477, 83, 83, 477, 9, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477
  };

static yyconst short int yy_chk[1101] =
  {0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,

    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 7, 8, 7, 8, 11, 11,
    12, 12, 21, 22, 21, 21, 21, 27, 29, 42,
    28, 31, 23, 21, 25, 7, 8, 26, 40, 30,
    27, 35, 37, 41, 38, 22, 23, 23, 28, 32,
    27, 25, 31, 29, 28, 33, 21, 7, 8, 25,
    23, 23, 23, 25, 30, 36, 32, 39, 33, 26,
    32, 43, 52, 42, 44, 53, 32, 51, 35, 35,
    38, 76, 76, 33, 54, 40, 59, 65, 53, 38,

    41, 35, 35, 35, 51, 58, 37, 480, 53, 52,
    64, 54, 51, 49, 52, 36, 51, 59, 39, 56,
    44, 43, 36, 39, 54, 43, 36, 49, 49, 55,
    43, 57, 61, 58, 44, 60, 56, 49, 62, 63,
    67, 49, 49, 49, 56, 61, 65, 55, 57, 56,
    64, 65, 60, 55, 68, 71, 60, 64, 66, 69,
    61, 64, 60, 62, 70, 72, 74, 75, 73, 77,
    77, 77, 86, 194, 80, 97, 63, 63, 77, 479,
    67, 79, 194, 79, 85, 63, 79, 79, 79, 63,
    63, 63, 67, 97, 66, 68, 80, 86, 88, 69,

    68, 77, 74, 66, 70, 71, 69, 91, 73, 72,
    87, 69, 73, 85, 75, 89, 74, 73, 78, 88,
    78, 78, 78, 90, 92, 87, 94, 93, 89, 78,
    95, 98, 99, 101, 102, 103, 91, 91, 105, 92,
    104, 94, 106, 107, 90, 108, 110, 109, 101, 94,
    98, 111, 78, 93, 112, 95, 113, 116, 102, 114,
    117, 119, 99, 103, 104, 115, 118, 122, 121, 105,
    123, 120, 124, 126, 127, 131, 128, 130, 214, 132,
    155, 129, 110, 108, 476, 136, 156, 214, 131, 133,
    107, 109, 128, 106, 113, 111, 129, 134, 130, 127,

    132, 117, 126, 115, 116, 112, 112, 114, 118, 120,
    115, 136, 134, 119, 121, 137, 123, 122, 133, 133,
    138, 142, 144, 150, 151, 124, 152, 149, 153, 154,
    137, 155, 157, 156, 158, 159, 161, 160, 137, 142,
    162, 144, 149, 163, 165, 138, 164, 150, 166, 167,
    152, 168, 151, 170, 171, 172, 173, 154, 169, 153,
    174, 176, 176, 176, 182, 175, 175, 175, 177, 177,
    177, 157, 158, 160, 175, 210, 180, 184, 183, 159,
    161, 163, 165, 181, 189, 203, 185, 186, 182, 165,
    167, 162, 162, 168, 164, 166, 169, 175, 181, 170,

    184, 172, 183, 187, 171, 180, 185, 186, 188, 173,
    174, 190, 181, 181, 189, 193, 191, 196, 197, 198,
    201, 202, 199, 187, 204, 206, 200, 210, 211, 205,
    226, 203, 207, 188, 208, 209, 193, 196, 197, 212,
    190, 191, 199, 200, 213, 217, 215, 216, 218, 198,
    475, 221, 219, 226, 223, 242, 227, 224, 228, 202,
    246, 225, 467, 244, 231, 245, 232, 229, 206, 223,
    204, 201, 202, 202, 205, 207, 227, 208, 228, 211,
    221, 224, 209, 223, 223, 225, 212, 229, 213, 215,
    216, 218, 219, 230, 231, 232, 233, 217, 234, 235,

    236, 238, 237, 239, 243, 246, 242, 240, 235, 244,
    247, 245, 250, 251, 248, 249, 252, 253, 230, 234,
    236, 233, 237, 239, 240, 254, 255, 256, 257, 258,
    259, 238, 260, 264, 265, 255, 276, 263, 277, 291,
    279, 282, 243, 292, 278, 294, 293, 265, 295, 282,
    264, 280, 296, 247, 264, 243, 243, 248, 249, 250,
    276, 278, 263, 277, 253, 251, 263, 252, 279, 254,
    256, 257, 260, 259, 297, 280, 298, 299, 301, 302,
    303, 258, 293, 292, 310, 299, 291, 292, 311, 312,
    291, 294, 296, 303, 314, 295, 302, 313, 321, 322,

    302, 315, 323, 301, 324, 325, 312, 301, 310, 315,
    327, 326, 328, 311, 332, 329, 333, 331, 314, 342,
    334, 346, 298, 329, 297, 313, 352, 343, 353, 332,
    335, 333, 354, 355, 356, 357, 342, 358, 323, 322,
    359, 361, 346, 322, 334, 321, 331, 331, 362, 321,
    324, 326, 325, 360, 335, 343, 361, 363, 328, 365,
    327, 364, 366, 362, 371, 369, 353, 372, 373, 376,
    354, 374, 375, 377, 379, 357, 365, 352, 352, 355,
    356, 363, 360, 360, 359, 364, 369, 358, 378, 386,
    366, 380, 381, 382, 379, 388, 390, 385, 391, 383,

    384, 392, 393, 394, 395, 372, 373, 396, 397, 376,
    386, 380, 381, 382, 398, 371, 371, 374, 375, 383,
    384, 385, 399, 377, 415, 388, 408, 409, 400, 401,
    402, 403, 378, 405, 404, 406, 410, 407, 411, 390,
    412, 391, 399, 413, 392, 393, 394, 395, 400, 401,
    402, 403, 397, 396, 404, 414, 406, 405, 416, 426,
    427, 428, 429, 430, 431, 438, 398, 407, 415, 408,
    409, 439, 440, 427, 441, 442, 443, 450, 453, 410,
    451, 411, 454, 412, 439, 455, 413, 460, 458, 426,
    456, 459, 462, 465, 428, 438, 463, 466, 450, 430,

    460, 414, 468, 451, 470, 440, 455, 469, 471, 463,
    416, 442, 472, 456, 429, 474, 473, 464, 461, 431,
    466, 457, 453, 452, 449, 471, 441, 454, 462, 465,
    469, 443, 458, 473, 448, 447, 459, 446, 445, 444,
    437, 436, 435, 434, 433, 432, 425, 468, 424, 470,
    423, 422, 472, 421, 420, 474, 478, 478, 419, 418,
    417, 389, 387, 370, 368, 367, 351, 350, 349, 348,
    347, 345, 344, 341, 340, 339, 338, 337, 336, 330,
    320, 319, 318, 317, 316, 309, 308, 307, 306, 305,
    304, 300, 290, 289, 288, 287, 286, 285, 284, 283,

    281, 275, 274, 273, 272, 271, 270, 269, 268, 267,
    266, 262, 261, 241, 222, 220, 195, 192, 179, 148,
    147, 146, 145, 143, 141, 140, 139, 135, 125, 100,
    96, 84, 83, 82, 50, 24, 9, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477,
    477, 477, 477, 477, 477, 477, 477, 477, 477, 477
  };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "CEvaluationLexer.lpp"
#define INITIAL 0 
/* scanner for kinetic functions */
#define YY_NEVER_INTERACTIVE 1
#define sSIGN 1
#define sOPERATOR 2
#define sID 3

#line 12 "CEvaluationLexer.lpp"
#include <vector>

#include "copasi.h"
#include "CEvaluationNode.h"
#include "CEvaluationLexer.h"
#include "CEvaluationParser_yacc.h"

#ifndef YYERRCODE
#define YYERRCODE 256
#endif

#define YY_USER_INIT \
    mpNode = NULL;\
    mPosition = 0;\
    mpNodeList = new std::vector< CEvaluationNode * >;

#define COMMON_ACTION \
    mPosition += yyleng;\
    mpNodeList->push_back(mpNode);

#line 758 "CEvaluationLexer_lex.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO((void));
#else
extern int yywrap YY_PROTO((void));
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO((char *, yyconst char *, int));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO((yyconst char *));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO((int new_state));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO((void));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO((void));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else 
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput(yytext, yyleng)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
 if ((result = LexerInput((char *) buf, max_size)) < 0) \
  YY_FATAL_ERROR("input in flex scanner failed");
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError(msg)
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
 YY_USER_ACTION

YY_DECL
{
  register yy_state_type yy_current_state;
  register char *yy_cp, *yy_bp;
  register int yy_act;

#line 37 "CEvaluationLexer.lpp"

#line 887 "CEvaluationLexer_lex.cpp"

  if (yy_init)
  {
    yy_init = 0;

#ifdef YY_USER_INIT
    YY_USER_INIT;
#endif

    if (! yy_start)
        yy_start = 1; /* first start state */

      if (! yyin)
        yyin = &cin;

      if (! yyout)
        yyout = &cout;

      if (! yy_current_buffer)
        yy_current_buffer =
          yy_create_buffer(yyin, YY_BUF_SIZE);

      yy_load_buffer_state();
    }

  while (1)  /* loops until end-of-file is reached */
  {
    yy_cp = yy_c_buf_p;

    /* Support of yytext. */
    *yy_cp = yy_hold_char;

    /* yy_bp points to the position in yy_ch_buf of the start of
     * the current run.
     */
    yy_bp = yy_cp;

    yy_current_state = yy_start;
  yy_match:
    do
      {
        register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
          if (yy_accept[yy_current_state])
            {
              yy_last_accepting_state = yy_current_state;
              yy_last_accepting_cpos = yy_cp;
            }
          while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
            {
              yy_current_state = (int) yy_def[yy_current_state];
              if (yy_current_state >= 478)
                yy_c = yy_meta[(unsigned int) yy_c];
            }
          yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
          ++yy_cp;
        }
      while (yy_base[yy_current_state] != 1038);

  yy_find_action:
      yy_act = yy_accept[yy_current_state];
      if (yy_act == 0)
        {/* have to back up */
          yy_cp = yy_last_accepting_cpos;
          yy_current_state = yy_last_accepting_state;
          yy_act = yy_accept[yy_current_state];
        }

      YY_DO_BEFORE_ACTION;

  do_action:  /* This label is used only to access EOF actions. */

      switch (yy_act)
        {/* beginning of action switch */
        case 0:  /* must back up */
          /* undo the effects of YY_DO_BEFORE_ACTION */
          *yy_cp = yy_hold_char;
          yy_cp = yy_last_accepting_cpos;
          yy_current_state = yy_last_accepting_state;
          goto yy_find_action;

        case 1:
          YY_RULE_SETUP
#line 38 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE,
                                             yytext);
          COMMON_ACTION;
          return TOKEN_NUMBER;

          YY_BREAK
        case 2:
          YY_RULE_SETUP
#line 46 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeConstant(CEvaluationNodeConstant::EXPONENTIALE,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_NUMBER;

          YY_BREAK
        case 3:
          YY_RULE_SETUP
#line 54 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeConstant(CEvaluationNodeConstant::PI,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_NUMBER;

          YY_BREAK
        case 4:
          YY_RULE_SETUP
#line 62 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeConstant(CEvaluationNodeConstant::TRUE,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_NUMBER;

          YY_BREAK
        case 5:
          YY_RULE_SETUP
#line 70 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeConstant(CEvaluationNodeConstant::FALSE,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_NUMBER;

          YY_BREAK
        case 6:
          YY_RULE_SETUP
#line 78 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeConstant(CEvaluationNodeConstant::_INFINITY,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_NUMBER;

          YY_BREAK
        case 7:
          YY_RULE_SETUP
#line 86 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::NOT,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_NOT;

          YY_BREAK
        case 8:
          YY_RULE_SETUP
#line 94 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::LE,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_LE;

          YY_BREAK
        case 9:
          YY_RULE_SETUP
#line 102 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::LT,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_LT;

          YY_BREAK
        case 10:
          YY_RULE_SETUP
#line 110 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::GE,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_GE;

          YY_BREAK
        case 11:
          YY_RULE_SETUP
#line 118 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::GT,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_GT;

          YY_BREAK
        case 12:
          YY_RULE_SETUP
#line 126 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::NE,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_NE;

          YY_BREAK
        case 13:
          YY_RULE_SETUP
#line 134 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::EQ,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_EQ;

          YY_BREAK
        case 14:
          YY_RULE_SETUP
#line 142 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::AND,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_AND;

          YY_BREAK
        case 15:
          YY_RULE_SETUP
#line 150 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::XOR,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_XOR;

          YY_BREAK
        case 16:
          YY_RULE_SETUP
#line 158 "CEvaluationLexer.lpp"

          mpNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::OR,
                                              yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_OR;

          YY_BREAK
        case 17:
          YY_RULE_SETUP
#line 165 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeObject(CEvaluationNodeObject::ANY,
                                             yytext);
          COMMON_ACTION;
          return TOKEN_NUMBER;

          YY_BREAK
        case 18:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 173 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::LOG,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 19:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 181 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::LOG10,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 20:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 189 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::EXP,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 21:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 197 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::SIN,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 22:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 205 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::COS,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 23:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 213 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::TAN,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 24:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 221 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::SEC,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 25:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 229 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::CSC,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 26:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 237 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::COT,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 27:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 245 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::SINH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 28:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 253 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::COSH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 29:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 261 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::TANH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 30:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 269 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::SECH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 31:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 277 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::CSCH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 32:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 285 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::COTH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 33:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 293 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCSIN,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 34:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 301 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCCOS,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 35:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 309 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCTAN,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 36:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 317 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCSEC,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 37:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 325 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCCSC,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 38:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 333 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCCOT,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 39:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 341 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCSINH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 40:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 349 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCCOSH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 41:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 357 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCTANH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 42:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 365 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCSECH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 43:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 373 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCCSCH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 44:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 381 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ARCCOTH,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 45:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 389 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::SQRT,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 46:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 397 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::ABS,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 47:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 405 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::FLOOR,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 48:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 413 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::CEIL,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 49:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 421 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::FACTORIAL,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_FUNCTION;

          YY_BREAK
        case 50:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 429 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeChoice(CEvaluationNodeChoice::IF,
                                             yytext);
          COMMON_ACTION;
          return TOKEN_LOGICAL_CHOICE;

          YY_BREAK
        case 51:
          *yy_cp = yy_hold_char; /* undo effects of setting up yytext */
          yy_c_buf_p = yy_cp -= 1;
          YY_DO_BEFORE_ACTION; /* set up yytext again */
          YY_RULE_SETUP
#line 437 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          {
            std::string tmp(yytext);
            mpNode = new CEvaluationNodeCall(CEvaluationNodeCall::EXPRESSION,
                                             tmp.substr(0, tmp.length() - 1));
          }
          COMMON_ACTION;
          return TOKEN_CALL;

          YY_BREAK
        case 52:
          YY_RULE_SETUP
#line 448 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          {
            std::string tmp(yytext);
            mpNode = new CEvaluationNodeCall(CEvaluationNodeCall::FUNCTION,
                                             tmp.substr(0, tmp.length() - 1));
          }
          COMMON_ACTION;
          return TOKEN_CALL;

          YY_BREAK
        case 53:
          YY_RULE_SETUP
#line 459 "CEvaluationLexer.lpp"

          BEGIN(sID);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::MINUS,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_SIGN;

          YY_BREAK
        case 54:
          YY_RULE_SETUP
#line 467 "CEvaluationLexer.lpp"

          BEGIN(sID);
          mpNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::PLUS,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_SIGN;

          YY_BREAK
        case 55:
          YY_RULE_SETUP
#line 475 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::POWER,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_OPERATOR_POWER;

          YY_BREAK
        case 56:
          YY_RULE_SETUP
#line 483 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_OPERATOR_MULTIPLY;

          YY_BREAK
        case 57:
          YY_RULE_SETUP
#line 491 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::DIVIDE,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_OPERATOR_MULTIPLY;

          YY_BREAK
        case 58:
          YY_RULE_SETUP
#line 499 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::MODULUS,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_OPERATOR_MODULUS;

          YY_BREAK
        case 59:
          YY_RULE_SETUP
#line 507 "CEvaluationLexer.lpp"

          BEGIN(sID);
          mpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::PLUS,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_OPERATOR_PLUS;

          YY_BREAK
        case 60:
          YY_RULE_SETUP
#line 515 "CEvaluationLexer.lpp"

          BEGIN(sID);
          mpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::MINUS,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_OPERATOR_PLUS;

          YY_BREAK
        case 61:
          YY_RULE_SETUP
#line 523 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeStructure(CEvaluationNodeStructure::OPEN,
                                                yytext);
          COMMON_ACTION;
          return TOKEN_STRUCTURE_OPEN;

          YY_BREAK
        case 62:
          YY_RULE_SETUP
#line 531 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeStructure(CEvaluationNodeStructure::VECTOR_OPEN,
                                                yytext);
          COMMON_ACTION;
          return TOKEN_STRUCTURE_VECTOR_OPEN;

          YY_BREAK
        case 63:
          YY_RULE_SETUP
#line 539 "CEvaluationLexer.lpp"

          BEGIN(sSIGN);
          mpNode = new CEvaluationNodeStructure(CEvaluationNodeStructure::COMMA,
                                                yytext);
          COMMON_ACTION;
          return TOKEN_STRUCTURE_COMMA;

          YY_BREAK
        case 64:
          YY_RULE_SETUP
#line 547 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeStructure(CEvaluationNodeStructure::CLOSE,
                                                yytext);
          COMMON_ACTION;
          return TOKEN_STRUCTURE_CLOSE;

          YY_BREAK
        case 65:
          YY_RULE_SETUP
#line 555 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeStructure(CEvaluationNodeStructure::VECTOR_CLOSE,
                                                yytext);
          COMMON_ACTION;
          return TOKEN_STRUCTURE_VECTOR_CLOSE;

          YY_BREAK
        case 66:
          YY_RULE_SETUP
#line 563 "CEvaluationLexer.lpp"

          BEGIN(sOPERATOR);
          mpNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY,
                                               yytext);
          COMMON_ACTION;
          return TOKEN_VARIABLE;

          YY_BREAK
        case 67:
          YY_RULE_SETUP
#line 571 "CEvaluationLexer.lpp"

          mpNode = new CEvaluationNodeWhiteSpace(CEvaluationNodeWhiteSpace::ANY,
                                                 yytext);
          COMMON_ACTION;

          YY_BREAK
        case YY_STATE_EOF(INITIAL):
              case YY_STATE_EOF(sSIGN):
                case YY_STATE_EOF(sOPERATOR):
                  case YY_STATE_EOF(sID):
#line 577 "CEvaluationLexer.lpp"
                      return 0;
          YY_BREAK
        case 68:
          YY_RULE_SETUP
#line 579 "CEvaluationLexer.lpp"

          CCopasiMessage(CCopasiMessage::ERROR, MCFunction + 2, mPosition);
          return YYERRCODE;

          YY_BREAK
        case 69:
          YY_RULE_SETUP
#line 584 "CEvaluationLexer.lpp"
          ECHO;
          YY_BREAK
#line 1832 "CEvaluationLexer_lex.cpp"

        case YY_END_OF_BUFFER:
      {
            /* Amount of text matched not including the EOB char. */
            int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

            /* Undo the effects of YY_DO_BEFORE_ACTION. */
            *yy_cp = yy_hold_char;
            YY_RESTORE_YY_MORE_OFFSET

            if (yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW)
              {
                /* We're scanning a new file or input source.  It's
                 * possible that this happened because the user
                 * just pointed yyin at a new source and called
                 * yylex().  If so, then we have to assure
                 * consistency between yy_current_buffer and our
                 * globals.  Here is the right place to do so, because
                 * this is the first action (other than possibly a
                 * back-up) that will match for the new input source.
                 */
                yy_n_chars = yy_current_buffer->yy_n_chars;
                yy_current_buffer->yy_input_file = yyin;
                yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
              }

            /* Note that here we test for yy_c_buf_p "<=" to the position
             * of the first EOB in the buffer, since yy_c_buf_p will
             * already have been incremented past the NUL character
             * (since all states make transitions on EOB to the
             * end-of-buffer state).  Contrast this with the test
             * in input().
             */
            if (yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars])
              {/* This was really a NUL. */
                yy_state_type yy_next_state;

                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

                /* Okay, we're now positioned to make the NUL
                 * transition.  We couldn't have
                 * yy_get_previous_state() go ahead and do it
                 * for us because it doesn't know how to deal
                 * with the possibility of jamming (and we don't
                 * want to build jamming into it because then it
                 * will run more slowly).
                 */

                yy_next_state = yy_try_NUL_trans(yy_current_state);

                yy_bp = yytext_ptr + YY_MORE_ADJ;

                if (yy_next_state)
                  {
                    /* Consume the NUL. */
                    yy_cp = ++yy_c_buf_p;
                    yy_current_state = yy_next_state;
                    goto yy_match;
                  }

                else
                  {
                    yy_cp = yy_c_buf_p;
                    goto yy_find_action;
                  }
              }

            else switch (yy_get_next_buffer())
                {
                case EOB_ACT_END_OF_FILE:
                  {
                    yy_did_buffer_switch_on_eof = 0;

                    if (yywrap())
                      {
                        /* Note: because we've taken care in
                         * yy_get_next_buffer() to have set up
                         * yytext, we can now set up
                         * yy_c_buf_p so that if some total
                         * hoser (like flex itself) wants to
                         * call the scanner after we return the
                         * YY_NULL, it'll still work - another
                         * YY_NULL will get returned.
                         */
                        yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

                        yy_act = YY_STATE_EOF(YY_START);
                        goto do_action;
                      }

                    else
                      {
                        if (! yy_did_buffer_switch_on_eof)
                          YY_NEW_FILE;
                      }
                    break;
                  }

                case EOB_ACT_CONTINUE_SCAN:
                  yy_c_buf_p =
                    yytext_ptr + yy_amount_of_matched_text;

                  yy_current_state = yy_get_previous_state();

                  yy_cp = yy_c_buf_p;
                  yy_bp = yytext_ptr + YY_MORE_ADJ;
                  goto yy_match;

                case EOB_ACT_LAST_MATCH:
                  yy_c_buf_p =
                    &yy_current_buffer->yy_ch_buf[yy_n_chars];

                  yy_current_state = yy_get_previous_state();

                  yy_cp = yy_c_buf_p;
                  yy_bp = yytext_ptr + YY_MORE_ADJ;
                  goto yy_find_action;
                }
            break;
          }

        default:
          YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found");
        } /* end of action switch */
    } /* end of scanning one token */
} /* end of yylex */

yyFlexLexer::yyFlexLexer(istream* arg_yyin, ostream* arg_yyout)
{
  yyin = arg_yyin;
  yyout = arg_yyout;
  yy_c_buf_p = 0;
  yy_init = 1;
  yy_start = 0;
  yy_flex_debug = 0;
  yylineno = 1; // this will only get updated if %option yylineno

  yy_did_buffer_switch_on_eof = 0;

  yy_looking_for_trail_begin = 0;
  yy_more_flag = 0;
  yy_more_len = 0;
  yy_more_offset = yy_prev_more_offset = 0;

  yy_start_stack_ptr = yy_start_stack_depth = 0;
  yy_start_stack = 0;

  yy_current_buffer = 0;

#ifdef YY_USES_REJECT
  yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
  yy_state_buf = 0;
#endif
}

yyFlexLexer::~yyFlexLexer()
{
  delete yy_state_buf;
  yy_delete_buffer(yy_current_buffer);
}

void yyFlexLexer::switch_streams(istream* new_in, ostream* new_out)
{
  if (new_in)
    {
      yy_delete_buffer(yy_current_buffer);
      yy_switch_to_buffer(yy_create_buffer(new_in, YY_BUF_SIZE));
    }

  if (new_out)
    yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput(char* buf, int /* max_size */)
#else
int yyFlexLexer::LexerInput(char* buf, int max_size)
#endif
{
  if (yyin->eof() || yyin->fail())
    return 0;

#ifdef YY_INTERACTIVE
  yyin->get(buf[0]);

  if (yyin->eof())
    return 0;

  if (yyin->bad())
    return - 1;

  return 1;

#else
  (void) yyin->read(buf, max_size);

  if (yyin->bad())
    return - 1;
  else
    return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput(const char* buf, int size)
{
  (void) yyout->write(buf, size);
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 * EOB_ACT_LAST_MATCH -
 * EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 * EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
{
  register char *dest = yy_current_buffer->yy_ch_buf;
  register char *source = yytext_ptr;
  register int number_to_move, i;
  int ret_val;

  if (yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1])
    YY_FATAL_ERROR(
      "fatal flex scanner internal error--end of buffer missed");

  if (yy_current_buffer->yy_fill_buffer == 0)
    {/* Don't try to fill the buffer, so this is an EOF. */
      if (yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1)
        {
          /* We matched a single character, the EOB, so
           * treat this as a final EOF.
           */
          return EOB_ACT_END_OF_FILE;
        }

      else
        {
          /* We matched some text prior to the EOB, first
           * process it.
           */
          return EOB_ACT_LAST_MATCH;
        }
    }

  /* Try to read more data. */

  /* First move last chars to start of buffer. */
  number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

  for (i = 0; i < number_to_move; ++i)
    *(dest++) = *(source++);

  if (yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING)
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
    yy_current_buffer->yy_n_chars = yy_n_chars = 0;

  else
    {
      int num_to_read =
        yy_current_buffer->yy_buf_size - number_to_move - 1;

      while (num_to_read <= 0)
        {/* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
          YY_FATAL_ERROR(
            "input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else

          /* just a shorter name for the current buffer */
          YY_BUFFER_STATE b = yy_current_buffer;

          int yy_c_buf_p_offset =
            (int) (yy_c_buf_p - b->yy_ch_buf);

          if (b->yy_is_our_buffer)
            {
              int new_size = b->yy_buf_size * 2;

              if (new_size <= 0)
                b->yy_buf_size += b->yy_buf_size / 8;
              else
                b->yy_buf_size *= 2;

              b->yy_ch_buf = (char *)
                             /* Include room in for 2 EOB chars. */
                             yy_flex_realloc((void *) b->yy_ch_buf,
                                              b->yy_buf_size + 2);
            }
          else
            /* Can't grow it, we don't own it. */
            b->yy_ch_buf = 0;

          if (! b->yy_ch_buf)
            YY_FATAL_ERROR(
              "fatal error - scanner input buffer overflow");

          yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

          num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
#endif
        }

      if (num_to_read > YY_READ_BUF_SIZE)
        num_to_read = YY_READ_BUF_SIZE;

      /* Read in more data. */
      YY_INPUT((&yy_current_buffer->yy_ch_buf[number_to_move]),
                yy_n_chars, num_to_read);

      yy_current_buffer->yy_n_chars = yy_n_chars;
    }

  if (yy_n_chars == 0)
    {
      if (number_to_move == YY_MORE_ADJ)
        {
          ret_val = EOB_ACT_END_OF_FILE;
          yyrestart(yyin);
        }

      else
        {
          ret_val = EOB_ACT_LAST_MATCH;
          yy_current_buffer->yy_buffer_status =
            YY_BUFFER_EOF_PENDING;
        }
    }

  else
    ret_val = EOB_ACT_CONTINUE_SCAN;

  yy_n_chars += number_to_move;
  yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
  yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

  yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

  return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
{
  register yy_state_type yy_current_state;
  register char *yy_cp;

  yy_current_state = yy_start;

  for (yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp)
    {
      register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
      if (yy_accept[yy_current_state])
        {
          yy_last_accepting_state = yy_current_state;
          yy_last_accepting_cpos = yy_cp;
        }
      while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
        {
          yy_current_state = (int) yy_def[yy_current_state];
          if (yy_current_state >= 478)
            yy_c = yy_meta[(unsigned int) yy_c];
        }
      yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    }

  return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 * next_state = yy_try_NUL_trans(current_state);
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans(yy_state_type yy_current_state)
{
  register int yy_is_jam;
  register char *yy_cp = yy_c_buf_p;

  register YY_CHAR yy_c = 1;
  if (yy_accept[yy_current_state])
    {
      yy_last_accepting_state = yy_current_state;
      yy_last_accepting_cpos = yy_cp;
    }
  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
    {
      yy_current_state = (int) yy_def[yy_current_state];
      if (yy_current_state >= 478)
        yy_c = yy_meta[(unsigned int) yy_c];
    }
  yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
  yy_is_jam = (yy_current_state == 477);

  return yy_is_jam ? 0 : yy_current_state;
}

void yyFlexLexer::yyunput(int c, register char* yy_bp)
{
  register char *yy_cp = yy_c_buf_p;

  /* undo effects of setting up yytext */
  *yy_cp = yy_hold_char;

  if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
    {/* need to shift things up to make room */
      /* +2 for EOB chars. */
      register int number_to_move = yy_n_chars + 2;
      register char *dest = &yy_current_buffer->yy_ch_buf[
                              yy_current_buffer->yy_buf_size + 2];
      register char *source =
        &yy_current_buffer->yy_ch_buf[number_to_move];

      while (source > yy_current_buffer->yy_ch_buf)
        *--dest = *--source;

      yy_cp += (int) (dest - source);
      yy_bp += (int) (dest - source);
      yy_current_buffer->yy_n_chars =
        yy_n_chars = yy_current_buffer->yy_buf_size;

      if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
        YY_FATAL_ERROR("flex scanner push-back overflow");
    }

  *--yy_cp = (char) c;

  yytext_ptr = yy_bp;
  yy_hold_char = *yy_cp;
  yy_c_buf_p = yy_cp;
}

int yyFlexLexer::yyinput()
{
  int c;

  *yy_c_buf_p = yy_hold_char;

  if (*yy_c_buf_p == YY_END_OF_BUFFER_CHAR)
    {
      /* yy_c_buf_p now points to the character we want to return.
       * If this occurs *before* the EOB characters, then it's a
       * valid NUL; if not, then we've hit the end of the buffer.
       */
      if (yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars])
        /* This was really a NUL. */
        *yy_c_buf_p = '\0';

      else
        {/* need more input */
          int offset = yy_c_buf_p - yytext_ptr;
          ++yy_c_buf_p;

          switch (yy_get_next_buffer())
            {
            case EOB_ACT_LAST_MATCH:
              /* This happens because yy_g_n_b()
               * sees that we've accumulated a
               * token and flags that we need to
               * try matching the token before
               * proceeding.  But for input(),
               * there's no matching to consider.
               * So convert the EOB_ACT_LAST_MATCH
               * to EOB_ACT_END_OF_FILE.
               */

              /* Reset buffer status. */
              yyrestart(yyin);

              /* fall through */

            case EOB_ACT_END_OF_FILE:
              {
                if (yywrap())
                  return EOF;

                if (! yy_did_buffer_switch_on_eof)
                  YY_NEW_FILE;
#ifdef __cplusplus
                return yyinput();
#else
                return input();
#endif
              }

            case EOB_ACT_CONTINUE_SCAN:
              yy_c_buf_p = yytext_ptr + offset;
              break;
            }
        }
    }

  c = *(unsigned char *) yy_c_buf_p; /* cast for 8-bit char's */
  *yy_c_buf_p = '\0'; /* preserve yytext */
  yy_hold_char = *++yy_c_buf_p;

  return c;
}

void yyFlexLexer::yyrestart(istream* input_file)
{
  if (! yy_current_buffer)
    yy_current_buffer = yy_create_buffer(yyin, YY_BUF_SIZE);

  yy_init_buffer(yy_current_buffer, input_file);
  yy_load_buffer_state();
}

void yyFlexLexer::yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
{
  if (yy_current_buffer == new_buffer)
    return;

  if (yy_current_buffer)
    {
      /* Flush out information for old buffer. */
      *yy_c_buf_p = yy_hold_char;
      yy_current_buffer->yy_buf_pos = yy_c_buf_p;
      yy_current_buffer->yy_n_chars = yy_n_chars;
    }

  yy_current_buffer = new_buffer;
  yy_load_buffer_state();

  /* We don't actually know whether we did this switch during
   * EOF (yywrap()) processing, but the only time this flag
   * is looked at is after yywrap() is called, so it's safe
   * to go ahead and always set it.
   */
  yy_did_buffer_switch_on_eof = 1;
}

void yyFlexLexer::yy_load_buffer_state()
{
  yy_n_chars = yy_current_buffer->yy_n_chars;
  yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
  yyin = yy_current_buffer->yy_input_file;
  yy_hold_char = *yy_c_buf_p;
}

YY_BUFFER_STATE yyFlexLexer::yy_create_buffer(istream* file, int size)
{
  YY_BUFFER_STATE b;

  b = (YY_BUFFER_STATE) yy_flex_alloc(sizeof(struct yy_buffer_state));
  if (! b)
    YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

  b->yy_buf_size = size;

  /* yy_ch_buf has to be 2 characters longer than the size given because
   * we need to put in 2 end-of-buffer characters.
   */
  b->yy_ch_buf = (char *) yy_flex_alloc(b->yy_buf_size + 2);
  if (! b->yy_ch_buf)
    YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

  b->yy_is_our_buffer = 1;

  yy_init_buffer(b, file);

  return b;
}

void yyFlexLexer::yy_delete_buffer(YY_BUFFER_STATE b)
{
  if (! b)
    return;

  if (b == yy_current_buffer)
    yy_current_buffer = (YY_BUFFER_STATE) 0;

  if (b->yy_is_our_buffer)
    yy_flex_free((void *) b->yy_ch_buf);

  yy_flex_free((void *) b);
}

void yyFlexLexer::yy_init_buffer(YY_BUFFER_STATE b, istream* file)

{
  yy_flush_buffer(b);

  b->yy_input_file = file;
  b->yy_fill_buffer = 1;

  b->yy_is_interactive = 0;
}

void yyFlexLexer::yy_flush_buffer(YY_BUFFER_STATE b)
{
  if (! b)
    return;

  b->yy_n_chars = 0;

  /* We always need two end-of-buffer characters.  The first causes
   * a transition to the end-of-buffer state.  The second causes
   * a jam in that state.
   */
  b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
  b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

  b->yy_buf_pos = &b->yy_ch_buf[0];

  b->yy_at_bol = 1;
  b->yy_buffer_status = YY_BUFFER_NEW;

  if (b == yy_current_buffer)
    yy_load_buffer_state();
}

#ifndef YY_NO_SCAN_BUFFER
#endif

#ifndef YY_NO_SCAN_STRING
#endif

#ifndef YY_NO_SCAN_BYTES
#endif

#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state(int new_state)
{
  if (yy_start_stack_ptr >= yy_start_stack_depth)
    {
      yy_size_t new_size;

      yy_start_stack_depth += YY_START_STACK_INCR;
      new_size = yy_start_stack_depth * sizeof(int);

      if (! yy_start_stack)
        yy_start_stack = (int *) yy_flex_alloc(new_size);

      else
        yy_start_stack = (int *) yy_flex_realloc(
                           (void *) yy_start_stack, new_size);

      if (! yy_start_stack)
        YY_FATAL_ERROR(
          "out of memory expanding start-condition stack");
    }

  yy_start_stack[yy_start_stack_ptr++] = YY_START;

  BEGIN(new_state);
}
#endif

#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
{
  if (--yy_start_stack_ptr < 0)
    YY_FATAL_ERROR("start-condition stack underflow");

  BEGIN(yy_start_stack[yy_start_stack_ptr]);
}
#endif

#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
{
  return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError(yyconst char msg[])
{
  cerr << msg << '\n';
  exit(YY_EXIT_FAILURE);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
 do \
  {\
  /* Undo effects of setting up yytext. */ \
  yytext[yyleng] = yy_hold_char; \
  yy_c_buf_p = yytext + n; \
  yy_hold_char = *yy_c_buf_p; \
  *yy_c_buf_p = '\0'; \
  yyleng = n; \
  } \
 while (0)

/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy(char *s1, yyconst char *s2, int n)
#else
static void yy_flex_strncpy(s1, s2, n)
char *s1;
yyconst char *s2;
int n;
#endif
{
  register int i;
  for (i = 0; i < n; ++i)
    s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen(yyconst char *s)
#else
static int yy_flex_strlen(s)
yyconst char *s;
#endif
{
  register int n;
  for (n = 0; s[n]; ++n)
;

  return n;
}
#endif

#ifdef YY_USE_PROTOS
static void *yy_flex_alloc(yy_size_t size)
#else
static void *yy_flex_alloc(size)
yy_size_t size;
#endif
{
  return (void *) malloc(size);
}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc(void *ptr, yy_size_t size)
#else
static void *yy_flex_realloc(ptr, size)
void *ptr;
yy_size_t size;
#endif
{
  /* The cast to (char *) in the following accommodates both
   * implementations that use char* generic pointers, and those
   * that use void* generic pointers.  It works with the latter
   * because both ANSI C and C++ allow castless assignment from
   * any pointer type to void*, and deal with argument conversions
   * as though doing an assignment.
   */
  return (void *) realloc((char *) ptr, size);
}

#ifdef YY_USE_PROTOS
static void yy_flex_free(void *ptr)
#else
static void yy_flex_free(ptr)
void *ptr;
#endif
{
  free(ptr);
}

#if YY_MAIN
int main()
{
  yylex();
  return 0;
}
#endif
#line 584 "CEvaluationLexer.lpp"
