#ifndef YYERRCODE
 #define YYERRCODE 256
 #endif

#define TOKEN_NUMBER 257
 #define TOKEN_VARIABLE 258
 #define TOKEN_CALL 259
 #define TOKEN_FUNCTION 260
 #define TOKEN_SIGN 261
 #define TOKEN_OPERATOR_POWER 262
 #define TOKEN_OPERATOR_MULTIPLY 263
 #define TOKEN_OPERATOR_MODULUS 264
 #define TOKEN_OPERATOR_PLUS 265
 #define TOKEN_LOGICAL_CHOICE 266
 #define TOKEN_LOGICAL_VALUE 267
 #define TOKEN_LOGICAL_NOT 268
 #define TOKEN_LOGICAL_OR 269
 #define TOKEN_LOGICAL_XOR 270
 #define TOKEN_LOGICAL_AND 271
 #define TOKEN_LOGICAL_EQ 272
 #define TOKEN_LOGICAL_NE 273
 #define TOKEN_LOGICAL_GT 274
 #define TOKEN_LOGICAL_GE 275
 #define TOKEN_LOGICAL_LT 276
 #define TOKEN_LOGICAL_LE 277
 #define TOKEN_STRUCTURE_OPEN 278
 #define TOKEN_STRUCTURE_VECTOR_OPEN 279
 #define TOKEN_STRUCTURE_COMMA 280
 #define TOKEN_STRUCTURE_CLOSE 281
 #define TOKEN_STRUCTURE_VECTOR_CLOSE 282
