/* Begin CVS Header
   $Source: /Volumes/Home/Users/shoops/cvs/copasi_dev/copasi/function/Attic/CKinFunctionFlexLexer.cpp,v $
   $Revision: 1.17 $
   $Name:  $
   $Author: shoops $ 
   $Date: 2004/06/08 17:48:22 $
   End CVS Header */

#define yyFlexLexer CKinFunctionFlexLexer
#define yyalloc CKinFunctionalloc
#define yyrealloc CKinFunctionrealloc
#define yyfree CKinFunctionfree
#define yylineno CKinFunctionlineno

#line 8 "CKinFunctionFlexLexer.cpp"
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 27
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <stdlib.h> 
/* end standard C++ headers. */

#ifdef __cplusplus

/* C++ compilers don't understand traditional function definitions. */
#ifdef YY_TRADITIONAL_FUNC_DEFS
#undef YY_TRADITIONAL_FUNC_DEFS
#endif

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else /* ! __cplusplus */

/* We're not in a C++ compiler, so by default,
we generate C99 function defs, unless you explicitly ask
for traditional defs by defining YY_TRADITIONAL_FUNC_DEFS */

#if __STDC__

#define YY_USE_CONST

#endif /* __STDC__ */
#endif /* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* For compilers that can't handle prototypes.
 * e.g.,
 * The function prototype
 *    int foo(int x, char* y);
 *
 * ...should be written as
 *    int foo YY_PARAMS((int x, char* y));
 *
 * ...which could possibly generate
 *    int foo ();
 */
#ifdef YY_NO_PROTOS
#define YY_PARAMS(proto) ()
#else
#define YY_PARAMS(proto) proto
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Define these macros to be no-ops. */
#define YY_G(var) (var)
#define YY_PROTO_LAST_ARG
#define YY_PROTO_ONLY_ARG void
#define YY_DEF_LAST_ARG
#ifdef YY_TRADITIONAL_FUNC_DEFS
#define YY_DEF_ONLY_ARG
#else
#define YY_DEF_ONLY_ARG void
#endif
#define YY_DECL_LAST_ARG
#define YY_CALL_LAST_ARG
#define YY_CALL_ONLY_ARG

/* For compilers that need traditional function definitions.
 * e.g.,
 * The function prototype taking 2 arguments
 *    int foo (int x, char* y)
 *
 * ...should be written as
 *    int foo YYFARGS2(int,x, char*,y)
 *
 * ...which could possibly generate
 *    int foo (x,y,yyscanner)
 *        int x;
 *        char * y;
 *        yyscan_t yyscanner;
 */
#ifdef YY_TRADITIONAL_FUNC_DEFS 
/* Generate traditional function defs */
#define YYFARGS0(v) (YY_DEF_ONLY_ARG) YY_DECL_LAST_ARG
#define YYFARGS1(t1,n1) (n1 YY_DEF_LAST_ARG) t1 n1; YY_DECL_LAST_ARG
#define YYFARGS2(t1,n1,t2,n2) (n1,n2 YY_DEF_LAST_ARG) t1 n1; t2 n2; YY_DECL_LAST_ARG
#define YYFARGS3(t1,n1,t2,n2,t3,n3) (n1,n2,n3 YY_DEF_LAST_ARG) t1 n1; t2 n2; t3 n3; YY_DECL_LAST_ARG
#else 
/* Generate C99 function defs. */
#define YYFARGS0(v) (YY_DEF_ONLY_ARG)
#define YYFARGS1(t1,n1) (t1 n1 YY_DEF_LAST_ARG)
#define YYFARGS2(t1,n1,t2,n2) (t1 n1,t2 n2 YY_DEF_LAST_ARG)
#define YYFARGS3(t1,n1,t2,n2,t3,n3) (t1 n1,t2 n2,t3 n3 YY_DEF_LAST_ARG)
#endif

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN YY_G(yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((YY_G(yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin YY_CALL_LAST_ARG)

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#ifdef YY_USE_LINENO 
/* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
 *       access to the local variable yy_act. Since yyless() is a macro, it would break
 *       existing scanners that call yyless() from OUTSIDE yylex. 
 *       One obvious solution it to make yy_act a global. I tried that, and saw
 *       a 5% performance hit in a non-yylineno scanner, because yy_act is
 *       normally declared as a register variable-- so it's not worth it.
 */
#define  YY_LESS_LINENO(n) \
        do {\
   int yyl;\
   for (yyl = n; yyl < yyleng; ++yyl)\
    if (yytext[yyl] == '\n')\
     --yylineno;\
        }while(0)
#else
#define YY_LESS_LINENO(n)
#endif

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *  if (condition_holds)
 *  yyless(5);
 * else
 *  do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
 do \
  {\
  /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
  *yy_cp = YY_G(yy_hold_char); \
  YY_RESTORE_YY_MORE_OFFSET \
  YY_G(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
  YY_DO_BEFORE_ACTION; /* set up yytext again */ \
  } \
 while (0)

#define unput(c) yyunput(c, YY_G(yytext_ptr) YY_CALL_LAST_ARG)

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
  {
    std::istream* yy_input_file;

    char *yy_ch_buf;  /* input buffer */
    char *yy_buf_pos;  /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
  };
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

void *yyalloc YY_PARAMS((yy_size_t YY_PROTO_LAST_ARG));
void *yyrealloc YY_PARAMS((void *, yy_size_t YY_PROTO_LAST_ARG));
void yyfree YY_PARAMS((void * YY_PROTO_LAST_ARG));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
 {\
 if (! YY_G(yy_current_buffer)) \
  YY_G(yy_current_buffer) =    \
            yy_create_buffer(yyin, YY_BUF_SIZE YY_CALL_LAST_ARG); \
 YY_G(yy_current_buffer)->yy_is_interactive = is_interactive; \
 }

#define yy_set_bol(at_bol) \
 {\
 if (! YY_G(yy_current_buffer)) \
  YY_G(yy_current_buffer) =    \
            yy_create_buffer(yyin, YY_BUF_SIZE YY_CALL_LAST_ARG); \
 YY_G(yy_current_buffer)->yy_at_bol = at_bol; \
 }

#define YY_AT_BOL() (YY_G(yy_current_buffer)->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP
#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
typedef unsigned char YY_CHAR;
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */
#define yytext_ptr yytext
#define YY_INTERACTIVE
#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

#include "FlexLexer.h"

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
 YY_G(yytext_ptr) = yy_bp; \
 yyleng = (size_t) (yy_cp - yy_bp); \
 YY_G(yy_hold_char) = *yy_cp; \
 *yy_cp = '\0'; \
 YY_G(yy_c_buf_p) = yy_cp;

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#define YY_NUM_RULES 23
#define YY_END_OF_BUFFER 24 
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
  {
    flex_int32_t yy_verify;
    flex_int32_t yy_nxt;
  };
static yyconst flex_int16_t yy_accept[56] =
  {0,
    0, 0, 24, 22, 21, 21, 17, 18, 14, 12,
    13, 15, 1, 22, 19, 19, 19, 19, 19, 16,
    19, 19, 19, 19, 21, 1, 1, 0, 0, 20,
    19, 19, 19, 19, 19, 19, 19, 19, 19, 1,
    0, 1, 11, 7, 3, 9, 10, 6, 2, 8,
    19, 19, 5, 4, 0
  };

static yyconst flex_int32_t yy_ec[256] =
  {0,
    1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
    1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 2, 1, 1, 1, 1, 1, 1, 1, 4,
    5, 6, 7, 1, 8, 9, 10, 11, 12, 13,
    13, 13, 13, 13, 13, 13, 13, 1, 1, 14,
    1, 15, 1, 1, 16, 16, 17, 16, 18, 16,
    19, 16, 20, 16, 16, 21, 16, 22, 23, 24,
    16, 16, 25, 16, 16, 16, 16, 26, 16, 16,
    1, 1, 1, 27, 16, 1, 16, 16, 28, 16,

    29, 16, 30, 16, 31, 16, 16, 32, 16, 33,
    34, 35, 16, 16, 36, 16, 16, 16, 16, 37,
    16, 16, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1
  };

static yyconst flex_int32_t yy_meta[38] =
  {0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    2, 2, 2, 1, 1, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2
  };

static yyconst flex_int16_t yy_base[57] =
  {0,
    0, 0, 100, 101, 36, 38, 101, 101, 101, 101,
    101, 101, 33, 37, 0, 76, 72, 74, 76, 101,
    61, 57, 58, 60, 51, 45, 0, 53, 56, 101,
    0, 65, 65, 69, 65, 50, 46, 43, 39, 64,
    67, 72, 0, 0, 58, 0, 0, 0, 47, 0,
    44, 36, 0, 0, 101, 41
  };

static yyconst flex_int16_t yy_def[57] =
  {0,
    55, 1, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 56, 56, 56, 56, 56, 55,
    56, 56, 56, 56, 55, 55, 13, 55, 55, 55,
    56, 56, 56, 56, 56, 56, 56, 56, 56, 55,
    55, 55, 56, 56, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 0, 55
  };

static yyconst flex_int16_t yy_nxt[139] =
  {0,
    4, 5, 6, 7, 8, 9, 10, 11, 4, 12,
    13, 13, 13, 14, 4, 15, 16, 17, 15, 15,
    18, 15, 15, 15, 19, 15, 20, 21, 22, 15,
    15, 23, 15, 15, 15, 24, 15, 25, 25, 25,
    25, 26, 31, 27, 27, 27, 54, 29, 29, 29,
    28, 30, 25, 25, 53, 40, 40, 40, 52, 41,
    41, 28, 28, 42, 42, 42, 29, 29, 29, 51,
    30, 50, 49, 28, 40, 40, 40, 42, 42, 42,
    48, 28, 42, 42, 42, 47, 46, 45, 44, 43,
    39, 38, 28, 37, 36, 35, 34, 33, 32, 55,

    3, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55
  };

static yyconst flex_int16_t yy_chk[139] =
  {0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 5, 5, 6,
    6, 13, 56, 13, 13, 13, 52, 14, 14, 14,
    13, 14, 25, 25, 51, 26, 26, 26, 49, 28,
    28, 13, 26, 28, 28, 28, 29, 29, 29, 45,
    29, 39, 38, 26, 40, 40, 40, 41, 41, 41,
    37, 40, 42, 42, 42, 36, 35, 34, 33, 32,
    24, 23, 40, 22, 21, 19, 18, 17, 16, 3,

    55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55
  };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "CKinFunctionFlexLexer.lpp"
#define INITIAL 0 
/* scanner for kinetic functions */
#define YY_NEVER_INTERACTIVE 1
#line 10 "CKinFunctionFlexLexer.lpp"
#include "CNodeK.h"
#line 549 "CKinFunctionFlexLexer.cpp"
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#ifndef YY_NO_UNISTD_H
using namespace std;
#endif /* !YY_NO_UNISTD_H */

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */
#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */
#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */
#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PARAMS((char *, yyconst char *, int YY_PROTO_LAST_ARG));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PARAMS((yyconst char * YY_PROTO_LAST_ARG));
#endif

#ifndef YY_NO_INPUT
#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */
#endif

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput(yytext, yyleng)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
 if ((result = LexerInput((char *) buf, max_size)) < 0) \
  YY_FATAL_ERROR("input in flex scanner failed");
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError(msg)
#endif

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */
#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */ 
/* end tables serialization structures and prototypes */

#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
 YY_USER_ACTION

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
YY_DECL
{
  register yy_state_type yy_current_state;
  register char *yy_cp, *yy_bp;
  register int yy_act;

#line 16 "CKinFunctionFlexLexer.lpp"
#define YY_TABLES_VERIFY 0

#line 670 "CKinFunctionFlexLexer.cpp"

  if (YY_G(yy_init))
  {
    YY_G(yy_init) = 0;

#ifdef YY_USER_INIT
      YY_USER_INIT;
#endif

#ifdef YY_USES_REJECT
      if (! YY_G(yy_state_buf))
        YY_G(yy_state_buf) = (yy_state_type *)yyalloc(YY_BUF_SIZE + 2 YY_CALL_LAST_ARG);
#endif

      if (! YY_G(yy_start))
        YY_G(yy_start) = 1; /* first start state */

      if (! yyin)
        yyin = & std::cin;

      if (! yyout)
        yyout = & std::cout;

      if (! YY_G(yy_current_buffer))
        YY_G(yy_current_buffer) =
          yy_create_buffer(yyin, YY_BUF_SIZE YY_CALL_LAST_ARG);

      yy_load_buffer_state(YY_CALL_ONLY_ARG);
    }

  while (1)  /* loops until end-of-file is reached */
  {
    yy_cp = YY_G(yy_c_buf_p);

      /* Support of yytext. */
      *yy_cp = YY_G(yy_hold_char);

      /* yy_bp points to the position in yy_ch_buf of the start of
       * the current run.
       */
      yy_bp = yy_cp;

      yy_current_state = YY_G(yy_start);
  yy_match:
      do
        {
          register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
          if (yy_accept[yy_current_state])
            {
              YY_G(yy_last_accepting_state) = yy_current_state;
              YY_G(yy_last_accepting_cpos) = yy_cp;
            }
          while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
            {
              yy_current_state = (int) yy_def[yy_current_state];
              if (yy_current_state >= 56)
                yy_c = yy_meta[(unsigned int) yy_c];
            }
          yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
          ++yy_cp;
        }
      while (yy_base[yy_current_state] != 101);

  yy_find_action:
      yy_act = yy_accept[yy_current_state];
      if (yy_act == 0)
        {/* have to back up */
          yy_cp = YY_G(yy_last_accepting_cpos);
          yy_current_state = YY_G(yy_last_accepting_state);
          yy_act = yy_accept[yy_current_state];
        }

      YY_DO_BEFORE_ACTION;

#ifdef YY_USE_LINENO
      if (yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act])
        {
          int yyl;
          for (yyl = 0; yyl < yyleng; ++yyl)
            if (yytext[yyl] == '\n')
              ++yylineno;
        }
#endif

  do_action:  /* This label is used only to access EOF actions. */

      switch (yy_act)
        {/* beginning of action switch */
        case 0:  /* must back up */
          /* undo the effects of YY_DO_BEFORE_ACTION */
          *yy_cp = YY_G(yy_hold_char);
          yy_cp = YY_G(yy_last_accepting_cpos);
          yy_current_state = YY_G(yy_last_accepting_state);
          goto yy_find_action;

        case 1:
          YY_RULE_SETUP
#line 18 "CKinFunctionFlexLexer.lpp"
          return N_NUMBER;
          YY_BREAK
        case 2:
#line 21 "CKinFunctionFlexLexer.lpp"
        case 3:
          YY_RULE_SETUP
#line 21 "CKinFunctionFlexLexer.lpp"
          return N_LOG;
          YY_BREAK
        case 4:
#line 24 "CKinFunctionFlexLexer.lpp"
        case 5:
          YY_RULE_SETUP
#line 24 "CKinFunctionFlexLexer.lpp"
          return N_LOG10;
          YY_BREAK
        case 6:
#line 27 "CKinFunctionFlexLexer.lpp"
        case 7:
          YY_RULE_SETUP
#line 27 "CKinFunctionFlexLexer.lpp"
          return N_EXP;
          YY_BREAK
        case 8:
#line 30 "CKinFunctionFlexLexer.lpp"
        case 9:
          YY_RULE_SETUP
#line 30 "CKinFunctionFlexLexer.lpp"
          return N_SIN;
          YY_BREAK
        case 10:
#line 33 "CKinFunctionFlexLexer.lpp"
        case 11:
          YY_RULE_SETUP
#line 33 "CKinFunctionFlexLexer.lpp"
          return N_COS;
          YY_BREAK
        case 12:
          YY_RULE_SETUP
#line 35 "CKinFunctionFlexLexer.lpp"
          return '+';
          YY_BREAK
        case 13:
          YY_RULE_SETUP
#line 36 "CKinFunctionFlexLexer.lpp"
          return '-';
          YY_BREAK
        case 14:
          YY_RULE_SETUP
#line 37 "CKinFunctionFlexLexer.lpp"
          return '*';
          YY_BREAK
        case 15:
          YY_RULE_SETUP
#line 38 "CKinFunctionFlexLexer.lpp"
          return '/';
          YY_BREAK
        case 16:
          YY_RULE_SETUP
#line 39 "CKinFunctionFlexLexer.lpp"
          return '^';
          YY_BREAK
        case 17:
          YY_RULE_SETUP
#line 40 "CKinFunctionFlexLexer.lpp"
          return '(';
          YY_BREAK
        case 18:
          YY_RULE_SETUP
#line 41 "CKinFunctionFlexLexer.lpp"
          return ')';
          YY_BREAK
        case 19:
          YY_RULE_SETUP
#line 43 "CKinFunctionFlexLexer.lpp"
          return N_IDENTIFIER;
          YY_BREAK
        case 20:
          YY_RULE_SETUP
#line 45 "CKinFunctionFlexLexer.lpp"
          return N_OBJECT;
          YY_BREAK
        case 21:
          /* rule 21 can match eol */
          YY_RULE_SETUP
#line 47 "CKinFunctionFlexLexer.lpp" 
          /* eat up whitespace */
          YY_BREAK
        case 22:
          YY_RULE_SETUP
#line 49 "CKinFunctionFlexLexer.lpp"
          return N_NOP;
          YY_BREAK
        case 23:
          YY_RULE_SETUP
#line 51 "CKinFunctionFlexLexer.lpp"
          ECHO;
          YY_BREAK
#line 869 "CKinFunctionFlexLexer.cpp"
        case YY_STATE_EOF(INITIAL):
                yyterminate();

        case YY_END_OF_BUFFER:
      {
            /* Amount of text matched not including the EOB char. */
            int yy_amount_of_matched_text = (int) (yy_cp - YY_G(yytext_ptr)) - 1;

            /* Undo the effects of YY_DO_BEFORE_ACTION. */
            *yy_cp = YY_G(yy_hold_char);
            YY_RESTORE_YY_MORE_OFFSET

            if (YY_G(yy_current_buffer)->yy_buffer_status == YY_BUFFER_NEW)
              {
                /* We're scanning a new file or input source.  It's
                 * possible that this happened because the user
                 * just pointed yyin at a new source and called
                 * yylex().  If so, then we have to assure
                 * consistency between yy_current_buffer and our
                 * globals.  Here is the right place to do so, because
                 * this is the first action (other than possibly a
                 * back-up) that will match for the new input source.
                 */
                YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_n_chars;
                YY_G(yy_current_buffer)->yy_input_file = yyin;
                YY_G(yy_current_buffer)->yy_buffer_status = YY_BUFFER_NORMAL;
              }

            /* Note that here we test for yy_c_buf_p "<=" to the position
             * of the first EOB in the buffer, since yy_c_buf_p will
             * already have been incremented past the NUL character
             * (since all states make transitions on EOB to the
             * end-of-buffer state).  Contrast this with the test
             * in input().
             */
            if (YY_G(yy_c_buf_p) <= &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)])
              {/* This was really a NUL. */
                yy_state_type yy_next_state;

                YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state(YY_CALL_ONLY_ARG);

                /* Okay, we're now positioned to make the NUL
                 * transition.  We couldn't have
                 * yy_get_previous_state() go ahead and do it
                 * for us because it doesn't know how to deal
                 * with the possibility of jamming (and we don't
                 * want to build jamming into it because then it
                 * will run more slowly).
                 */

                yy_next_state = yy_try_NUL_trans(yy_current_state YY_CALL_LAST_ARG);

                yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;

                if (yy_next_state)
                  {
                    /* Consume the NUL. */
                    yy_cp = ++YY_G(yy_c_buf_p);
                    yy_current_state = yy_next_state;
                    goto yy_match;
                  }

                else
                  {
                    yy_cp = YY_G(yy_c_buf_p);
                    goto yy_find_action;
                  }
              }

            else switch (yy_get_next_buffer(YY_CALL_ONLY_ARG))
                {
                case EOB_ACT_END_OF_FILE:
                  {
                    YY_G(yy_did_buffer_switch_on_eof) = 0;

                    if (yywrap(YY_CALL_ONLY_ARG))
                      {
                        /* Note: because we've taken care in
                         * yy_get_next_buffer() to have set up
                         * yytext, we can now set up
                         * yy_c_buf_p so that if some total
                         * hoser (like flex itself) wants to
                         * call the scanner after we return the
                         * YY_NULL, it'll still work - another
                         * YY_NULL will get returned.
                         */
                        YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + YY_MORE_ADJ;

                        yy_act = YY_STATE_EOF(YY_START);
                        goto do_action;
                      }

                    else
                      {
                        if (! YY_G(yy_did_buffer_switch_on_eof))
                          YY_NEW_FILE;
                      }
                    break;
                  }

                case EOB_ACT_CONTINUE_SCAN:
                  YY_G(yy_c_buf_p) =
                    YY_G(yytext_ptr) + yy_amount_of_matched_text;

                  yy_current_state = yy_get_previous_state(YY_CALL_ONLY_ARG);

                  yy_cp = YY_G(yy_c_buf_p);
                  yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;
                  goto yy_match;

                case EOB_ACT_LAST_MATCH:
                  YY_G(yy_c_buf_p) =
                    &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)];

                  yy_current_state = yy_get_previous_state(YY_CALL_ONLY_ARG);

                  yy_cp = YY_G(yy_c_buf_p);
                  yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;
                  goto yy_find_action;
                }
            break;
          }

        default:
          YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found");
        } /* end of action switch */
    } /* end of scanning one token */
} /* end of yylex */
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
yyFlexLexer::yyFlexLexer(std::istream* arg_yyin, std::ostream* arg_yyout)
{
  yyin = arg_yyin;
  yyout = arg_yyout;
  yy_c_buf_p = 0;
  yy_init = 1;
  yy_start = 0;
  yy_flex_debug = 0;
  yylineno = 1; // this will only get updated if %option yylineno

  yy_did_buffer_switch_on_eof = 0;

  yy_looking_for_trail_begin = 0;
  yy_more_flag = 0;
  yy_more_len = 0;
  yy_more_offset = yy_prev_more_offset = 0;

  yy_start_stack_ptr = yy_start_stack_depth = 0;
  yy_start_stack = 0;

  yy_current_buffer = 0;

#ifdef YY_USES_REJECT
  yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
  yy_state_buf = 0;
#endif
}

yyFlexLexer::~yyFlexLexer()
{
  delete [] yy_state_buf;
  yyfree(yy_start_stack YY_CALL_LAST_ARG);
  yy_delete_buffer(yy_current_buffer YY_CALL_LAST_ARG);
}

void yyFlexLexer::switch_streams(std::istream* new_in, std::ostream* new_out)
{
  if (new_in)
    {
      yy_delete_buffer(yy_current_buffer YY_CALL_LAST_ARG);
      yy_switch_to_buffer(yy_create_buffer(new_in, YY_BUF_SIZE YY_CALL_LAST_ARG) YY_CALL_LAST_ARG);
    }

  if (new_out)
    yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput(char* buf, int /* max_size */)
#else
int yyFlexLexer::LexerInput(char* buf, int max_size)
#endif
{
  if (yyin->eof() || yyin->fail())
    return 0;

#ifdef YY_INTERACTIVE
  yyin->get(buf[0]);

  if (yyin->eof())
    return 0;

  if (yyin->bad())
    return - 1;

  return 1;

#else
  (void) yyin->read(buf, max_size);

  if (yyin->bad())
    return - 1;
  else
    return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput(const char* buf, int size)
{
  (void) yyout->write(buf, size);
}
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 * EOB_ACT_LAST_MATCH -
 * EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 * EOB_ACT_END_OF_FILE - end of file
 */

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
int yyFlexLexer::yy_get_next_buffer()
{
  register char *dest = YY_G(yy_current_buffer)->yy_ch_buf;
  register char *source = YY_G(yytext_ptr);
  register int number_to_move, i;
  int ret_val;

  if (YY_G(yy_c_buf_p) > &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars) + 1])
    YY_FATAL_ERROR(
      "fatal flex scanner internal error--end of buffer missed");

  if (YY_G(yy_current_buffer)->yy_fill_buffer == 0)
    {/* Don't try to fill the buffer, so this is an EOF. */
      if (YY_G(yy_c_buf_p) - YY_G(yytext_ptr) - YY_MORE_ADJ == 1)
        {
          /* We matched a single character, the EOB, so
           * treat this as a final EOF.
           */
          return EOB_ACT_END_OF_FILE;
        }

      else
        {
          /* We matched some text prior to the EOB, first
           * process it.
           */
          return EOB_ACT_LAST_MATCH;
        }
    }

  /* Try to read more data. */

  /* First move last chars to start of buffer. */
  number_to_move = (int) (YY_G(yy_c_buf_p) - YY_G(yytext_ptr)) - 1;

  for (i = 0; i < number_to_move; ++i)
    *(dest++) = *(source++);

  if (YY_G(yy_current_buffer)->yy_buffer_status == YY_BUFFER_EOF_PENDING)
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
    YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars) = 0;

  else
    {
      size_t num_to_read =
        YY_G(yy_current_buffer)->yy_buf_size - number_to_move - 1;

      while (num_to_read <= 0)
        {/* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
          YY_FATAL_ERROR(
            "input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else

          /* just a shorter name for the current buffer */
          YY_BUFFER_STATE b = YY_G(yy_current_buffer);

          int yy_c_buf_p_offset =
            (int) (YY_G(yy_c_buf_p) - b->yy_ch_buf);

          if (b->yy_is_our_buffer)
            {
              int new_size = b->yy_buf_size * 2;

              if (new_size <= 0)
                b->yy_buf_size += b->yy_buf_size / 8;
              else
                b->yy_buf_size *= 2;

              b->yy_ch_buf = (char *)
                             /* Include room in for 2 EOB chars. */
                             yyrealloc((void *) b->yy_ch_buf,
                                        b->yy_buf_size + 2 YY_CALL_LAST_ARG);
            }
          else
            /* Can't grow it, we don't own it. */
            b->yy_ch_buf = 0;

          if (! b->yy_ch_buf)
            YY_FATAL_ERROR(
              "fatal error - scanner input buffer overflow");

          YY_G(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

          num_to_read = YY_G(yy_current_buffer)->yy_buf_size -
                        number_to_move - 1;
#endif
        }

      if (num_to_read > YY_READ_BUF_SIZE)
        num_to_read = YY_READ_BUF_SIZE;

      /* Read in more data. */
      YY_INPUT((&YY_G(yy_current_buffer)->yy_ch_buf[number_to_move]),
                YY_G(yy_n_chars), num_to_read);

      YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars);
    }

  if (YY_G(yy_n_chars) == 0)
    {
      if (number_to_move == YY_MORE_ADJ)
        {
          ret_val = EOB_ACT_END_OF_FILE;
          yyrestart(yyin YY_CALL_LAST_ARG);
        }

      else
        {
          ret_val = EOB_ACT_LAST_MATCH;
          YY_G(yy_current_buffer)->yy_buffer_status =
            YY_BUFFER_EOF_PENDING;
        }
    }

  else
    ret_val = EOB_ACT_CONTINUE_SCAN;

  YY_G(yy_n_chars) += number_to_move;
  YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
  YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

  YY_G(yytext_ptr) = &YY_G(yy_current_buffer)->yy_ch_buf[0];

  return ret_val;
}
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* yy_get_previous_state - get the state just before the EOB char was reached */

#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */
yy_state_type yyFlexLexer::yy_get_previous_state()
{
  register yy_state_type yy_current_state;
  register char *yy_cp;

  yy_current_state = YY_G(yy_start);

  for (yy_cp = YY_G(yytext_ptr) + YY_MORE_ADJ; yy_cp < YY_G(yy_c_buf_p); ++yy_cp)
    {
      register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
      if (yy_accept[yy_current_state])
        {
          YY_G(yy_last_accepting_state) = yy_current_state;
          YY_G(yy_last_accepting_cpos) = yy_cp;
        }
      while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
        {
          yy_current_state = (int) yy_def[yy_current_state];
          if (yy_current_state >= 56)
            yy_c = yy_meta[(unsigned int) yy_c];
        }
      yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    }

  return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 * next_state = yy_try_NUL_trans(current_state);
 */
yy_state_type yyFlexLexer::yy_try_NUL_trans(yy_state_type yy_current_state)
{
  register int yy_is_jam;
  register char *yy_cp = YY_G(yy_c_buf_p);

  register YY_CHAR yy_c = 1;
  if (yy_accept[yy_current_state])
    {
      YY_G(yy_last_accepting_state) = yy_current_state;
      YY_G(yy_last_accepting_cpos) = yy_cp;
    }
  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
    {
      yy_current_state = (int) yy_def[yy_current_state];
      if (yy_current_state >= 56)
        yy_c = yy_meta[(unsigned int) yy_c];
    }
  yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
  yy_is_jam = (yy_current_state == 55);

  return yy_is_jam ? 0 : yy_current_state;
}

void yyFlexLexer::yyunput(int c, register char* yy_bp)
{
  register char *yy_cp = YY_G(yy_c_buf_p);

  /* undo effects of setting up yytext */
  *yy_cp = YY_G(yy_hold_char);

  if (yy_cp < YY_G(yy_current_buffer)->yy_ch_buf + 2)
    {/* need to shift things up to make room */
      /* +2 for EOB chars. */
      register int number_to_move = YY_G(yy_n_chars) + 2;
      register char *dest = &YY_G(yy_current_buffer)->yy_ch_buf[
                              YY_G(yy_current_buffer)->yy_buf_size + 2];
      register char *source =
        &YY_G(yy_current_buffer)->yy_ch_buf[number_to_move];

      while (source > YY_G(yy_current_buffer)->yy_ch_buf)
        *--dest = *--source;

      yy_cp += (int) (dest - source);
      yy_bp += (int) (dest - source);
      YY_G(yy_current_buffer)->yy_n_chars =
        YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_buf_size;

      if (yy_cp < YY_G(yy_current_buffer)->yy_ch_buf + 2)
        YY_FATAL_ERROR("flex scanner push-back overflow");
    }

  *--yy_cp = (char) c;

#ifdef YY_USE_LINENO
  if (c == '\n')
    --yylineno;
#endif
  YY_G(yytext_ptr) = yy_bp;
  YY_G(yy_hold_char) = *yy_cp;
  YY_G(yy_c_buf_p) = yy_cp;
}

int yyFlexLexer::yyinput()

{
  int c;

  *YY_G(yy_c_buf_p) = YY_G(yy_hold_char);

  if (*YY_G(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR)
    {
      /* yy_c_buf_p now points to the character we want to return.
       * If this occurs *before* the EOB characters, then it's a
       * valid NUL; if not, then we've hit the end of the buffer.
       */
      if (YY_G(yy_c_buf_p) < &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)])
        /* This was really a NUL. */
        *YY_G(yy_c_buf_p) = '\0';

      else
        {/* need more input */
          int offset = YY_G(yy_c_buf_p) - YY_G(yytext_ptr);
          ++YY_G(yy_c_buf_p);

          switch (yy_get_next_buffer(YY_CALL_ONLY_ARG))
            {
            case EOB_ACT_LAST_MATCH:
              /* This happens because yy_g_n_b()
               * sees that we've accumulated a
               * token and flags that we need to
               * try matching the token before
               * proceeding.  But for input(),
               * there's no matching to consider.
               * So convert the EOB_ACT_LAST_MATCH
               * to EOB_ACT_END_OF_FILE.
               */

              /* Reset buffer status. */
              yyrestart(yyin YY_CALL_LAST_ARG);

              /*FALLTHROUGH*/

            case EOB_ACT_END_OF_FILE:
              {
                if (yywrap(YY_CALL_ONLY_ARG))
                  return EOF;

                if (! YY_G(yy_did_buffer_switch_on_eof))
                  YY_NEW_FILE;
#ifdef __cplusplus
                return yyinput(YY_CALL_ONLY_ARG);
#else
                return input(YY_CALL_ONLY_ARG);
#endif
              }

            case EOB_ACT_CONTINUE_SCAN:
              YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + offset;
              break;
            }
        }
    }

  c = *(unsigned char *) YY_G(yy_c_buf_p); /* cast for 8-bit char's */
  *YY_G(yy_c_buf_p) = '\0'; /* preserve yytext */
  YY_G(yy_hold_char) = *++YY_G(yy_c_buf_p);

  return c;
}

void yyFlexLexer::yyrestart(std::istream* input_file)
{
  if (! YY_G(yy_current_buffer))
    YY_G(yy_current_buffer) =
      yy_create_buffer(yyin, YY_BUF_SIZE YY_CALL_LAST_ARG);

  yy_init_buffer(YY_G(yy_current_buffer), input_file YY_CALL_LAST_ARG);
  yy_load_buffer_state(YY_CALL_ONLY_ARG);
}

void yyFlexLexer::yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
{
  if (YY_G(yy_current_buffer) == new_buffer)
    return;

  if (YY_G(yy_current_buffer))
    {
      /* Flush out information for old buffer. */
      *YY_G(yy_c_buf_p) = YY_G(yy_hold_char);
      YY_G(yy_current_buffer)->yy_buf_pos = YY_G(yy_c_buf_p);
      YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars);
    }

  YY_G(yy_current_buffer) = new_buffer;
  yy_load_buffer_state(YY_CALL_ONLY_ARG);

  /* We don't actually know whether we did this switch during
   * EOF (yywrap()) processing, but the only time this flag
   * is looked at is after yywrap() is called, so it's safe
   * to go ahead and always set it.
   */
  YY_G(yy_did_buffer_switch_on_eof) = 1;
}

void yyFlexLexer::yy_load_buffer_state()
{
  YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_n_chars;
  YY_G(yytext_ptr) = YY_G(yy_c_buf_p) = YY_G(yy_current_buffer)->yy_buf_pos;
  yyin = YY_G(yy_current_buffer)->yy_input_file;
  YY_G(yy_hold_char) = *YY_G(yy_c_buf_p);
}

YY_BUFFER_STATE yyFlexLexer::yy_create_buffer(std::istream* file, int size)
{
  YY_BUFFER_STATE b;

  b = (YY_BUFFER_STATE) yyalloc(sizeof(struct yy_buffer_state) YY_CALL_LAST_ARG);
  if (! b)
    YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

  b->yy_buf_size = size;

  /* yy_ch_buf has to be 2 characters longer than the size given because
   * we need to put in 2 end-of-buffer characters.
   */
  b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 YY_CALL_LAST_ARG);
  if (! b->yy_ch_buf)
    YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

  b->yy_is_our_buffer = 1;

  yy_init_buffer(b, file YY_CALL_LAST_ARG);

  return b;
}

void yyFlexLexer::yy_delete_buffer(YY_BUFFER_STATE b)
{
  if (! b)
    return;

  if (b == YY_G(yy_current_buffer))
    YY_G(yy_current_buffer) = (YY_BUFFER_STATE) 0;

  if (b->yy_is_our_buffer)
    yyfree((void *) b->yy_ch_buf YY_CALL_LAST_ARG);

  yyfree((void *) b YY_CALL_LAST_ARG);
}

#ifndef YY_NEVER_INTERACTIVE
extern "C" int isatty YY_PARAMS((int));
#endif
void yyFlexLexer::yy_init_buffer(YY_BUFFER_STATE b, std::istream* file)

{
  int oerrno = errno;

  yy_flush_buffer(b YY_CALL_LAST_ARG);

  b->yy_input_file = file;
  b->yy_fill_buffer = 1;

  b->yy_is_interactive = 0;
  errno = oerrno;
}

void yyFlexLexer::yy_flush_buffer(YY_BUFFER_STATE b)
{
  if (! b)
    return;

  b->yy_n_chars = 0;

  /* We always need two end-of-buffer characters.  The first causes
   * a transition to the end-of-buffer state.  The second causes
   * a jam in that state.
   */
  b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
  b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

  b->yy_buf_pos = &b->yy_ch_buf[0];

  b->yy_at_bol = 1;
  b->yy_buffer_status = YY_BUFFER_NEW;

  if (b == YY_G(yy_current_buffer))
    yy_load_buffer_state(YY_CALL_ONLY_ARG);
}

#ifndef YY_NO_SCAN_BUFFER
#endif

#ifndef YY_NO_SCAN_STRING
#endif

#ifndef YY_NO_SCAN_BYTES
#endif

#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state(int new_state)
{
  if (YY_G(yy_start_stack_ptr) >= YY_G(yy_start_stack_depth))
    {
      yy_size_t new_size;

      YY_G(yy_start_stack_depth) += YY_START_STACK_INCR;
      new_size = YY_G(yy_start_stack_depth) * sizeof(int);

      if (! YY_G(yy_start_stack))
        YY_G(yy_start_stack) = (int *) yyalloc(new_size YY_CALL_LAST_ARG);

      else
        YY_G(yy_start_stack) = (int *) yyrealloc(
                                 (void *) YY_G(yy_start_stack), new_size YY_CALL_LAST_ARG);

      if (! YY_G(yy_start_stack))
        YY_FATAL_ERROR(
          "out of memory expanding start-condition stack");
    }

  YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr)++] = YY_START;

  BEGIN(new_state);
}
#endif

#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
{
  if (--YY_G(yy_start_stack_ptr) < 0)
    YY_FATAL_ERROR("start-condition stack underflow");

  BEGIN(YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr)]);
}
#endif

#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
{
  return YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr) - 1];
}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError(yyconst char msg[])
{
  std::cerr << msg << std::endl;
  exit(YY_EXIT_FAILURE);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
 do \
  {\
  /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
  yytext[yyleng] = YY_G(yy_hold_char); \
  YY_G(yy_c_buf_p) = yytext + yyless_macro_arg; \
  YY_G(yy_hold_char) = *YY_G(yy_c_buf_p); \
  *YY_G(yy_c_buf_p) = '\0'; \
  yyleng = yyless_macro_arg; \
  } \
 while (0)

/* Accessor  methods (get/set functions) to struct members. */

/* Internal utility routines. */

#ifndef yytext_ptr
static void yy_flex_strncpy YYFARGS3(char*, s1, yyconst char *, s2, int, n)
{
  register int i;
  for (i = 0; i < n; ++i)
    s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YYFARGS1(yyconst char *, s)
{
  register int n;
  for (n = 0; s[n]; ++n)
;

  return n;
}
#endif

/* You may override yyalloc by defining YY_NO_FLEX_ALLOC and linking to
 * your own version */
#ifndef YY_NO_FLEX_ALLOC
void *yyalloc YYFARGS1(yy_size_t , size)
{
  return (void *) malloc(size);
}
#endif

/* You may override yyrealloc by defining YY_NO_FLEX_REALLOC and linking
 * to your own version. */
#ifndef YY_NO_FLEX_REALLOC
void *yyrealloc YYFARGS2(void *, ptr, yy_size_t , size)
{
  /* The cast to (char *) in the following accommodates both
   * implementations that use char* generic pointers, and those
   * that use void* generic pointers.  It works with the latter
   * because both ANSI C and C++ allow castless assignment from
   * any pointer type to void*, and deal with argument conversions
   * as though doing an assignment.
   */
  return (void *) realloc((char *) ptr, size);
}
#endif

/* You may override yyfree by defining YY_NO_FLEX_FREE and linking to
 * your own version.*/
#ifndef YY_NO_FLEX_FREE
void yyfree YYFARGS1(void *, ptr)
{
  free((char *) ptr); /* see yyrealloc() for (char *) cast */
}
#endif

#define YYTABLES_NAME "yytables"

#if YY_MAIN
int main YY_PARAMS((void));

int main ()
{
  yylex();

  return 0;
}
#endif
#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */
#line 51 "CKinFunctionFlexLexer.lpp"
#ifndef CKinFunctionIN_HEADER /* YY-DISCARD-FROM-HEADER */

#endif /* !CKinFunctionIN_HEADER YY-END-DISCARD-FROM-HEADER */
