// Copyright (C) 2019 - 2026 by Pedro Mendes, Rector and Visitors of the
// University of Virginia, University of Heidelberg, and University
// of Connecticut School of Medicine.
// All rights reserved.

// Copyright (C) 2017 - 2018 by Pedro Mendes, Virginia Tech Intellectual
// Properties, Inc., University of Heidelberg, and University of
// of Connecticut School of Medicine.
// All rights reserved.

// Copyright (C) 2012 - 2016 by Pedro Mendes, Virginia Tech Intellectual
// Properties, Inc., University of Heidelberg, and The University
// of Manchester.
// All rights reserved.

#ifndef COPASI_CQIconResource
#define COPASI_CQIconResource

#include <QtCore/QVector>
#include <QIcon>
#include <QStyle>

#include "copasi/core/CEnumAnnotation.h"

class CQIconResource
{
public:
  enum IconID
  {
    bars = 0,
    captureImage,
    checkMark,
    copasi,
    edit,
    editAdd,
    editCopy,
    editDelete,
    error,
    fileAdd,
    fileExport,
    fileNew,
    fileOpen,
    filePrint,
    fileSave,
    fileSaveas,
    information,
    isToS,
    locked,
    miriam,
    moveDown,
    moveUp,
    warning,
    parameterMissing,
    parameterModified,
    parameterObsolete,
    playerKill,
    playerPause,
    playerStart,
    playerStop,
    preferences,
    reactionModifier,
    reactionProduct,
    reactionSubstrate,
    renderMarkup,
    renderMathML,
    separator,
    slider,
    sToIs,
    table,
    tool,
    unlocked,
    zoomOut,
    play,
    pause,
    stop,
    backward,
    forward,
    skipBackward,
    skipForward,
    roll,
    viewmagMinus,
    viewmagPlus,
    viewmag1,
    viewmagfit,
    _reset,
    animation,
    dialog_error,
    dialog_information,
    dialog_warning,
    dialog_question,
    unknown // This is the default icon which is empty
  };

  static const QIcon & icon(const IconID & id);

private:
  static void init();
  static void load(IconID iconID, QIcon::Mode mode = QIcon::Normal, QIcon::State state = QIcon::Off);

  static QVector< QIcon > Icons;
  static bool needInit;

  constexpr static CEnumAnnotation BackupName{
    IconID::unknown,
    MapNode{IconID::bars, "bars.png"},
    MapNode{IconID::captureImage, "captureImage.png"},
    MapNode{IconID::checkMark, "checkMark.png"},
    MapNode{IconID::copasi, "copasi.png"},
    MapNode{IconID::edit, "edit.png"},
    MapNode{IconID::editAdd, "editAdd.png"},
    MapNode{IconID::editCopy, "editCopy.png"},
    MapNode{IconID::editDelete, "editDelete.png"},
    MapNode{IconID::error, "error.png"},
    MapNode{IconID::fileAdd, "fileAdd.png"},
    MapNode{IconID::fileExport, "fileExport.png"},
    MapNode{IconID::fileNew, "fileNew.png"},
    MapNode{IconID::fileOpen, "fileOpen.png"},
    MapNode{IconID::filePrint, "filePrint.png"},
    MapNode{IconID::fileSave, "fileSave.png"},
    MapNode{IconID::fileSaveas, "fileSaveas.png"},
    MapNode{IconID::information, "information.png"},
    MapNode{IconID::isToS, "isToS_128.png"},
    MapNode{IconID::locked, "locked.png"},
    MapNode{IconID::miriam, "miriam.png"},
    MapNode{IconID::moveDown, "moveDown.png"},
    MapNode{IconID::moveUp, "moveUp.png"},
    MapNode{IconID::warning, "warning.png"},
    MapNode{IconID::parameterMissing, "parameterMissing.png"},
    MapNode{IconID::parameterModified, "parameterModified.png"},
    MapNode{IconID::parameterObsolete, "parameterObsolete.png"},
    MapNode{IconID::playerKill, "playerKill.png"},
    MapNode{IconID::playerPause, "playerPause.png"},
    MapNode{IconID::playerStart, "playerStart.png"},
    MapNode{IconID::playerStop, "playerStop.png"},
    MapNode{IconID::preferences, "preferences.png"},
    MapNode{IconID::reactionModifier, "reactionModifier.png"},
    MapNode{IconID::reactionProduct, "reactionProduct.png"},
    MapNode{IconID::reactionSubstrate, "reactionSubstrate.png"},
    MapNode{IconID::renderMarkup, "renderMarkup.png"},
    MapNode{IconID::renderMathML, "renderMathML.png"},
    MapNode{IconID::separator, "separator.png"},
    MapNode{IconID::slider, "slider.png"},
    MapNode{IconID::sToIs, "sToIs_128.png"},
    MapNode{IconID::table, "table.png"},
    MapNode{IconID::tool, "tool.png"},
    MapNode{IconID::unlocked, "unlocked.png"},
    MapNode{IconID::zoomOut, "zoomOut.png"},
    MapNode{IconID::play, "media-playback-start.png"},
    MapNode{IconID::pause, "media-playback-pause.png"},
    MapNode{IconID::stop, "media-playback-stop.png"},
    MapNode{IconID::backward, "media-seek-backward.png"},
    MapNode{IconID::forward, "media-seek-forward.png"},
    MapNode{IconID::skipBackward, "media-skip-backward.png"},
    MapNode{IconID::skipForward, "media-skip-forward.png"},
    MapNode{IconID::roll, "roll.png"},
    MapNode{IconID::viewmagMinus, "viewmagMinus.png"},
    MapNode{IconID::viewmagPlus, "viewmagPlus.png"},
    MapNode{IconID::viewmag1, "viewmag1.png"},
    MapNode{IconID::viewmagfit, "viewmagfit.png"},
    MapNode{IconID::_reset, "reset.png"},
    MapNode{IconID::animation, "animation.png"},
    MapNode{IconID::dialog_error, "dialog_error.png"},
    MapNode{IconID::dialog_information, "dialog_information.png"},
    MapNode{IconID::dialog_warning, "dialog_warning.png"},
    MapNode{IconID::dialog_question, "dialog_question.png"},
    MapNode{IconID::unknown, ""},
  };

  constexpr static CEnumAnnotation ThemeName{
    IconID::unknown,
    MapNode{IconID::bars, "bars"},
    MapNode{IconID::captureImage, "captureImage"},
    MapNode{IconID::checkMark, "checkMark"},
    MapNode{IconID::copasi, "copasi"},
    MapNode{IconID::edit, "document-open"},
    MapNode{IconID::editAdd, "document-new"},
    MapNode{IconID::editCopy, "edit-copy"},
    MapNode{IconID::editDelete, "edit-delete"},
    MapNode{IconID::error, "error"},
    MapNode{IconID::fileAdd, "list-add"},
    MapNode{IconID::fileExport, "document-save-as"},
    MapNode{IconID::fileNew, "document-new"},
    MapNode{IconID::fileOpen, "document-open"},
    MapNode{IconID::filePrint, "document-print"},
    MapNode{IconID::fileSave, "document-save"},
    MapNode{IconID::fileSaveas, "document-save-as"},
    MapNode{IconID::information, "information"},
    MapNode{IconID::isToS, "isToS"},
    MapNode{IconID::locked, "locked"},
    MapNode{IconID::miriam, "miriam"},
    MapNode{IconID::moveDown, "go-down"},
    MapNode{IconID::moveUp, "go-up"},
    MapNode{IconID::warning, "warning"},
    MapNode{IconID::parameterMissing, "parameterMissing"},
    MapNode{IconID::parameterModified, "parameterModified"},
    MapNode{IconID::parameterObsolete, "parameterObsolete"},
    MapNode{IconID::playerKill, "playerKill"},
    MapNode{IconID::playerPause, "media-playback-pause"},
    MapNode{IconID::playerStart, "media-playback-start"},
    MapNode{IconID::playerStop, "media-playback-stop"},
    MapNode{IconID::preferences, "preferences"},
    MapNode{IconID::reactionModifier, "reactionModifier"},
    MapNode{IconID::reactionProduct, "reactionProduct"},
    MapNode{IconID::reactionSubstrate, "reactionSubstrate"},
    MapNode{IconID::renderMarkup, "renderMarkup"},
    MapNode{IconID::renderMathML, "renderMathML"},
    MapNode{IconID::separator, "separator"},
    MapNode{IconID::slider, "slider"},
    MapNode{IconID::sToIs, "sToIs"},
    MapNode{IconID::table, "table"},
    MapNode{IconID::tool, "tool"},
    MapNode{IconID::unlocked, "unlocked"},
    MapNode{IconID::zoomOut, "zoom-out"},
    MapNode{IconID::play, "media-playback-start"},
    MapNode{IconID::pause, "media-playback-pause"},
    MapNode{IconID::stop, "media-playback-stop"},
    MapNode{IconID::backward, "media-seek-backward"},
    MapNode{IconID::forward, "media-seek-forward"},
    MapNode{IconID::skipBackward, "media-skip-backward"},
    MapNode{IconID::skipForward, "media-skip-forward"},
    MapNode{IconID::roll, "roll"},
    MapNode{IconID::viewmagMinus, "zoom-out"},
    MapNode{IconID::viewmagPlus, "zoom-in"},
    MapNode{IconID::viewmag1, "zoom-original"},
    MapNode{IconID::viewmagfit, "zoom-fit-best"},
    MapNode{IconID::_reset, "reset"},
    MapNode{IconID::animation, "animation"},
    MapNode{IconID::dialog_error, "dialog_error"},
    MapNode{IconID::dialog_information, "dialog_information"},
    MapNode{IconID::dialog_warning, "dialog_warning"},
    MapNode{IconID::dialog_question, "dialog_question"},
    MapNode{IconID::unknown, "unknown"}};

  constexpr static CEnumAnnotation StandardIcon{
    IconID::unknown,
    MapNode{IconID::bars, QStyle::SP_CustomBase},
    MapNode{IconID::captureImage, QStyle::SP_CustomBase},
    MapNode{IconID::checkMark, QStyle::SP_CustomBase},
    MapNode{IconID::copasi, QStyle::SP_CustomBase},
    MapNode{IconID::edit, QStyle::SP_CustomBase},
    MapNode{IconID::editAdd, QStyle::SP_CustomBase},
    MapNode{IconID::editCopy, QStyle::SP_CustomBase},
    MapNode{IconID::editDelete, QStyle::SP_CustomBase},
    MapNode{IconID::error, QStyle::SP_MessageBoxCritical},
    MapNode{IconID::fileAdd, QStyle::SP_CustomBase},
    MapNode{IconID::fileExport, QStyle::SP_CustomBase},
    MapNode{IconID::fileNew, QStyle::SP_CustomBase},
    MapNode{IconID::fileOpen, QStyle::SP_CustomBase},
    MapNode{IconID::filePrint, QStyle::SP_CustomBase},
    MapNode{IconID::fileSave, QStyle::SP_CustomBase},
    MapNode{IconID::fileSaveas, QStyle::SP_CustomBase},
    MapNode{IconID::information, QStyle::SP_MessageBoxInformation},
    MapNode{IconID::isToS, QStyle::SP_CustomBase},
    MapNode{IconID::locked, QStyle::SP_CustomBase},
    MapNode{IconID::miriam, QStyle::SP_CustomBase},
    MapNode{IconID::moveDown, QStyle::SP_ArrowDown},
    MapNode{IconID::moveUp, QStyle::SP_ArrowUp},
    MapNode{IconID::warning, QStyle::SP_MessageBoxWarning},
    MapNode{IconID::parameterMissing, QStyle::SP_CustomBase},
    MapNode{IconID::parameterModified, QStyle::SP_CustomBase},
    MapNode{IconID::parameterObsolete, QStyle::SP_CustomBase},
    MapNode{IconID::playerKill, QStyle::SP_CustomBase},
    MapNode{IconID::playerPause, QStyle::SP_MediaPause},
    MapNode{IconID::playerStart, QStyle::SP_MediaPlay},
    MapNode{IconID::playerStop, QStyle::SP_MediaStop},
    MapNode{IconID::preferences, QStyle::SP_CustomBase},
    MapNode{IconID::reactionModifier, QStyle::SP_CustomBase},
    MapNode{IconID::reactionProduct, QStyle::SP_CustomBase},
    MapNode{IconID::reactionSubstrate, QStyle::SP_CustomBase},
    MapNode{IconID::renderMarkup, QStyle::SP_CustomBase},
    MapNode{IconID::renderMathML, QStyle::SP_CustomBase},
    MapNode{IconID::separator, QStyle::SP_CustomBase},
    MapNode{IconID::slider, QStyle::SP_CustomBase},
    MapNode{IconID::sToIs, QStyle::SP_CustomBase},
    MapNode{IconID::table, QStyle::SP_CustomBase},
    MapNode{IconID::tool, QStyle::SP_CustomBase},
    MapNode{IconID::unlocked, QStyle::SP_CustomBase},
    MapNode{IconID::zoomOut, QStyle::SP_CustomBase},
    MapNode{IconID::play, QStyle::SP_MediaPlay},
    MapNode{IconID::pause, QStyle::SP_MediaPause},
    MapNode{IconID::stop, QStyle::SP_MediaStop},
    MapNode{IconID::backward, QStyle::SP_MediaSeekBackward},
    MapNode{IconID::forward, QStyle::SP_MediaSeekForward},
    MapNode{IconID::skipBackward, QStyle::SP_MediaSkipBackward},
    MapNode{IconID::skipForward, QStyle::SP_MediaSkipForward},
    MapNode{IconID::roll, QStyle::SP_CustomBase},
    MapNode{IconID::viewmagMinus, QStyle::SP_CustomBase},
    MapNode{IconID::viewmagPlus, QStyle::SP_CustomBase},
    MapNode{IconID::viewmag1, QStyle::SP_CustomBase},
    MapNode{IconID::viewmagfit, QStyle::SP_CustomBase},
    MapNode{IconID::_reset, QStyle::SP_CustomBase},
    MapNode{IconID::animation, QStyle::SP_CustomBase},
    MapNode{IconID::dialog_error, QStyle::SP_MessageBoxCritical},
    MapNode{IconID::dialog_information, QStyle::SP_MessageBoxInformation},
    MapNode{IconID::dialog_warning, QStyle::SP_MessageBoxWarning},
    MapNode{IconID::dialog_question, QStyle::SP_MessageBoxQuestion},
    MapNode{IconID::unknown, QStyle::SP_CustomBase}};
};

#endif // COPASI_CQIconResource
