// Copyright (C) 2019 by Pedro Mendes, Rector and Visitors of the
// University of Virginia, University of Heidelberg, and University
// of Connecticut School of Medicine.
// All rights reserved.


static const char* shinyServerString = "\n"
                                       "## server file\n"
                                       "server <- function(input, output, session) {\n"
                                       "  \n"
                                       "  ## limit for the input file size\n"
                                       "  options(shiny.maxRequestSize=30*1024^2) \n"
                                       "  \n"
                                       "  ## to store the current selection\n"
                                       "  selection <- renderText({\n"
                                       "    selectedText <- unlist(get_selected(input$taskSelection))\n"
                                       "    return(selectedText)\n"
                                       "  })\n"
                                       "  \n"
                                       "  ## to store the error encountered\n"
                                       "  error <- renderText({\n"
                                       "    if (is.null(inputFile$dataPaths))\n"
                                       "      error <- c('No model file loaded !!')\n"
                                       "    else if (is.null(inputFile$modelData))\n"
                                       "      error <- c('Please load a valid model file!!')\n"
                                       "    else if (exists('message', where=resTask()))\n"
                                       "      error <- c(resTask()$message)\n"
                                       "    else\n"
                                       "      error <- ''\n"
                                       "    \n"
                                       "    return(error)\n"
                                       "  })\n"
                                       "  \n"
                                       "  ## to display the error \n"
                                       "  output$errorOut <- renderText({\n"
                                       "    textOutput('error')\n"
                                       "    return(error())\n"
                                       "  })\n"
                                       "  \n"
                                       "  ## To store the information of input model\n"
                                       "  inputFile <- reactiveValues()\n"
                                       "  observe({\n"
                                       "\n"
                                       "    inputFile$fileNames <- dir('copasi')\n"
                                       "    inputFile$dataPaths <- paste0('copasi/',inputFile$fileNames)\n"
                                       "    # \n"
                                       "    inputFile$dirName <- dirname(inputFile$dataPaths)\n"
                                       "    inputFile$modelData <- NULL\n"
                                       "    inputFile$rootnode <- NULL\n"
                                       "    inputFile$modelLoaded <- FALSE\n"
                                       "    for (i in 1:length(inputFile$fileNames)){\n"
                                       "      inputFileName <- inputFile$fileNames[i]\n"
                                       "      if (grepl('\\\\.cps$',inputFileName)){\n"
                                       "        inputFile$modelData <- CoRC::loadModel(inputFile$dataPaths[i])\n"
                                       "        inputFile$modelName <- inputFileName\n"
                                       "        inputFile$rootnode <- xmlTreeParse(inputFile$dataPaths[i])\n"
                                       "        inputFile$modelAttrs <- xmlAttrs(inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='Model']$Model)\n"
                                       "        inputFile$modelLoaded <- TRUE\n"
                                       "      }\n"
                                       "      else if (grepl('\\\\.xml$', inputFileName)){\n"
                                       "        inputFile$modelData <- CoRC::loadSBML(inputFile$dataPaths[i])\n"
                                       "        inputFile$modelName <- inputFileName\n"
                                       "      }\n"
                                       "    }\n"
                                       "    \n"
                                       "    if (is.null(inputFile$modelData)){\n"
                                       "      return(error())\n"
                                       "    }\n"
                                       "\n"
                                       "    inputFile$compartments <- CoRC::getCompartments(model=inputFile$modelData)\n"
                                       "    inputFile$species <- CoRC::getSpecies(model=inputFile$modelData)\n"
                                       "    inputFile$reactions <- CoRC::getReactions(model=inputFile$modelData)\n"
                                       "    inputFile$globalQuantities <- CoRC::getGlobalQuantities(model=inputFile$modelData)\n"
                                       "    inputFile$events <- CoRC::getEvents(model=inputFile$modelData)\n"
                                       "    inputFile$parameters <- CoRC::getParameters(model=inputFile$modelData)\n"
                                       "    inputFile$stoichiometry <- CoRC::getStoichiometryMatrix(model=inputFile$modelData)\n"
                                       "    inputFile$linkMatrix <- CoRC::getLinkMatrix(model=inputFile$modelData)\n"
                                       "    inputFile$settingsTC <- CoRC::getTimeCourseSettings(model=inputFile$modelData)\n"
                                       "    inputFile$settingsOpt <- CoRC::getOptimizationSettings(model=inputFile$modelData)\n"
                                       "    inputFile$settingsPE <- CoRC::getParameterEstimationSettings(model=inputFile$modelData)\n"
                                       "    inputFile$taskList <- c('Compartments', 'Species', 'Reactions'\n"
                                       "                            ,'Global Quantities', 'Events', 'Parameters'\n"
                                       "                            ,'Steady State', 'Stoichiometric Analysis','Mass Conservation'\n"
                                       "                            ,'Time Course', 'Metabolic Control Analysis','Optimization'\n"
                                       "                            ,'Parameter Estimation', 'Linear Noise Approximation')\n"
                                       "  })\n"
                                       "  \n"
                                       "  \n"
                                       "  ## Theme functions for the plots\n"
                                       "  theme_pm <- function () {\n"
                                       "    theme_bw(base_size=12) + #base_family='Arial Black'\n"
                                       "      theme(\n"
                                       "        panel.grid=element_line(linetype='dashed', color='light grey', size=0.2),\n"
                                       "        axis.ticks.length=unit(-0.15, 'cm'),\n"
                                       "        axis.text.x = element_text(margin=unit(c(0.25,0.25,0.25,0.25),'cm')),\n"
                                       "        axis.text.y = element_text(margin=unit(c(0.25,0.25,0.25,0.25),'cm'))\n"
                                       "      )\n"
                                       "  }\n"
                                       "  \n"
                                       "  output$modelInfo <- renderText({\n"
                                       "    if ( is.null(inputFile$modelData))\n"
                                       "      return()\n"
                                       "    selectedTask = selection()\n"
                                       "    if (selectedTask %in% inputFile$taskList ){\n"
                                       "      if (selectedTask == 'Parameter Estimation' ){\n"
                                       "        expfileName= ''\n"
                                       "        valfileName= ''\n"
                                       "        if (xmlSize(inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='ListOfTasks']$ListOfTasks[[6]][[2]][[9]]) >= 1){\n"
                                       "          xmlList= xmlChildren(inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='ListOfTasks']$ListOfTasks[[6]][[2]][[9]][[1]])\n"
                                       "          for (i in 1:xmlSize(xmlList)){\n"
                                       "            paramValue= xmlToList(xmlList[[i]])\n"
                                       "            if (paramValue[[1]] == 'File Name'){\n"
                                       "              expfileName= paramValue[[3]]\n"
                                       "              break\n"
                                       "            }\n"
                                       "          }\n"
                                       "          if (expfileName %in% inputFile$fileNames){\n"
                                       "            #file.copy(inputFile$dataPaths[inputFile$fileNames == expfileName], paste0(inputFile$dirName,'/',expfileName), overwrite = TRUE, recursive = FALSE,copy.mode = TRUE, copy.date = FALSE)\n"
                                       "          }\n"
                                       "          else\n"
                                       "            expfileName= paste(' <font color=','red','>  Please load a valid data file along with the model. File name: <b>', expfileName ,'</b> </font> ')\n"
                                       "        }\n"
                                       "          \n"
                                       "        if (xmlSize(inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='ListOfTasks']$ListOfTasks[[6]][[2]][[10]]) > 2){\n"
                                       "          xmlList= xmlChildren(inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='ListOfTasks']$ListOfTasks[[6]][[2]][[10]][[1]])\n"
                                       "          for (i in 1:xmlSize(xmlList)){\n"
                                       "            paramValue= xmlToList(xmlList[[i]])\n"
                                       "            if (paramValue[[1]] == 'File Name'){\n"
                                       "              valfileName= paramValue[[3]]\n"
                                       "              break\n"
                                       "            }\n"
                                       "          }\n"
                                       "          if (valfileName %in% inputFile$fileNames){\n"
                                       "            #file.copy(inputFile$dataPaths[inputFile$fileNames == valfileName], paste0(inputFile$dirName,'/',valfileName), overwrite = TRUE, recursive = FALSE,copy.mode = TRUE, copy.date = FALSE)\n"
                                       "          }\n"
                                       "          else\n"
                                       "            valfileName= paste(' <font color=','red','>  Please load a valid data file along with the model. File name: <b>', valfileName ,'</b> </font> ')\n"
                                       "        }\n"
                                       "        \n"
                                       "        strOut= paste('<h2>',selectedTask,'</h2>')\n"
                                       "        strOut= paste(strOut, '<pre><b> Experimental Data: </b>',expfileName,'<br> <br>')\n"
                                       "        strOut= paste(strOut, '<b>Validation Data: </b>',valfileName,'<br>')\n"
                                       "        strOut= paste(strOut, '<pre><b> Randomize Start Values: </b>',inputFile$settingsPE$randomize_start_values)\n"
                                       "        strOut= paste(strOut, '<b>  Calculate Statistics: </b>',inputFile$settingsPE$calculate_statistics, '</pre></pre>')\n"
                                       "        return(strOut)\n"
                                       "        \n"
                                       "      }\n"
                                       "      else if (selectedTask == 'Optimization' ){\n"
                                       "        strOut= paste('<h2>',selectedTask,'</h2>')\n"
                                       "        strOut= paste(strOut, '<pre><b> Expression: </b>',inputFile$settingsOpt$expression)\n"
                                       "        strOut= paste(strOut, '<pre><b> Maxmize: </b>',inputFile$settingsOpt$maximize, '</pre>')\n"
                                       "        strOut= paste(strOut, '<b>Subtask: </b>',inputFile$settingsOpt$subtask)\n"
                                       "        strOut= paste(strOut, '<pre><b> Randomize Start Values: </b>',inputFile$settingsOpt$randomize_start_values)\n"
                                       "        strOut= paste(strOut, '<b>  Calculate Statistics: </b>',inputFile$settingsOpt$calculate_statistics, '</pre></pre>')\n"
                                       "        return(strOut)\n"
                                       "      }\n"
                                       "      else\n"
                                       "        return(paste('<h2>',selectedTask,'</h2>'))\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Model' || inputFile$modelLoaded == T){\n"
                                       "      #strOut= paste('<h2>',selectedTask,'</h2>')\n"
                                       "      strOut= paste('<pre><b> Model: </b>',inputFile$modelAttrs[[2]],'<br>')\n"
                                       "      strOut= paste(strOut,'<pre><table><tr><th>Time Unit:</th><td>',inputFile$modelAttrs[[4]]\n"
                                       "                    ,'</td><th>Volume Unit:</th><td>',inputFile$modelAttrs[[5]],'</td></tr>')\n"
                                       "      strOut= paste(strOut,'<tr><th>Quantity Unit:</th><td>',inputFile$modelAttrs[[8]]\n"
                                       "                    ,'</td><th>Area Unit:</th><td>',inputFile$modelAttrs[[6]],'</td></tr>')\n"
                                       "      strOut= paste(strOut,'<tr><th>Avogadro Constant:</th><td>',inputFile$modelAttrs[[10]]\n"
                                       "                    ,'</td><th>Length Unit:</th><td>',inputFile$modelAttrs[[7]],'</td></tr></table></pre></pre>')\n"
                                       "      \n"
                                       "      return(strOut)\n"
                                       "    }\n"
                                       "  })\n"
                                       "  \n"
                                       "  output$selectedMethod<- renderText({\n"
                                       "    if (is.null(inputFile$rootnode))\n"
                                       "      return()\n"
                                       "    \n"
                                       "    selectedTask = selection()\n"
                                       "    if (selectedTask == 'Parameter Estimation' ){\n"
                                       "      methodSetting= inputFile$settingsPE$method\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Optimization' ){\n"
                                       "      methodSetting= inputFile$settingsOpt$method\n"
                                       "    }\n"
                                       "    else{\n"
                                       "      return()\n"
                                       "    }\n"
                                       "  \n"
                                       "    strOut= ''\n"
                                       "    namesMethod= paste0(toupper(substring(names(methodSetting),1,1)),substring(names(methodSetting),2))\n"
                                       "    strOut= paste('<pre><b>',namesMethod[[1]],'</b>:',methodSetting[[1]],'<br><pre>')\n"
                                       "    for (i in 2:length(namesMethod)){\n"
                                       "      strOut= paste(strOut, '<b>',namesMethod[[i]],'</b>:&nbsp ', methodSetting[[i]], '<br>')\n"
                                       "    }\n"
                                       "    return(paste(strOut,'</pre></pre>'))\n"
                                       "  })\n"
                                       "    \n"
                                       "  paramList <- function () {\n"
                                       "    if (is.null(inputFile$rootnode))\n"
                                       "      return()\n"
                                       "    \n"
                                       "    selectedTask = selection()\n"
                                       "    if (selectedTask == 'Parameter Estimation' ){\n"
                                       "      xmlList= inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='ListOfTasks']$ListOfTasks[[6]][[2]][[4]]\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Optimization' ){\n"
                                       "      xmlList= inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='ListOfTasks']$ListOfTasks[[5]][[2]][[6]]\n"
                                       "    }\n"
                                       "    else{\n"
                                       "      return()\n"
                                       "    }\n"
                                       "    \n"
                                       "    numParameters= xmlSize(xmlChildren(xmlList))\n"
                                       "    if (numParameters < 1)\n"
                                       "      return()\n"
                                       "    \n"
                                       "    resTable <- setNames(data.frame(matrix(ncol = 4, nrow = numParameters)), c('LowerBound', 'Parameter', 'UpperBound','StartValue'))\n"
                                       "    for (i in 1:numParameters){\n"
                                       "      xmlListIN <- xmlChildren(xmlList[[i]])\n"
                                       "      for (j in 1:xmlSize(xmlListIN)){\n"
                                       "        checkParam = names(xmlListIN) == 'Parameter'\n"
                                       "        if (checkParam[j]){\n"
                                       "          paramValue= xmlToList(xmlListIN[[j]])\n"
                                       "          if (paramValue[[1]] == 'LowerBound'){\n"
                                       "            resTable$LowerBound[i] = paramValue[[3]]\n"
                                       "          }\n"
                                       "          else if (paramValue[[1]]== 'ObjectCN'){\n"
                                       "            resTable$Parameter[i] = gsub(',Reference=','.',gsub('.*Vector=','',paramValue[[3]]))\n"
                                       "          }\n"
                                       "          else if (paramValue[[1]]== 'UpperBound'){\n"
                                       "            resTable$UpperBound[i] = paramValue[[3]]\n"
                                       "          }\n"
                                       "          else if (paramValue[[1]]== 'StartValue'){\n"
                                       "            resTable$StartValue[i] = paramValue[[3]]\n"
                                       "          }\n"
                                       "        }\n"
                                       "      }\n"
                                       "    }\n"
                                       "    return(resTable)\n"
                                       "  }\n"
                                       "  \n"
                                       "  constrList <- function () {\n"
                                       "    if (is.null(inputFile$rootnode))\n"
                                       "      return()\n"
                                       "    \n"
                                       "    selectedTask = selection()\n"
                                       "    if (selectedTask == 'Parameter Estimation' ){\n"
                                       "      xmlList= inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='ListOfTasks']$ListOfTasks[[6]][[2]][[5]]\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Optimization' ){\n"
                                       "      xmlList= inputFile$rootnode$doc$children$COPASI[names(inputFile$rootnode$doc$children$COPASI)=='ListOfTasks']$ListOfTasks[[5]][[2]][[7]]\n"
                                       "    }\n"
                                       "    else{\n"
                                       "      return()\n"
                                       "    }\n"
                                       "    \n"
                                       "    \n"
                                       "    numParameters= xmlSize(xmlChildren(xmlList))\n"
                                       "    if (numParameters < 1)\n"
                                       "      return()\n"
                                       "    resTable <- setNames(data.frame(matrix(ncol = 3, nrow = numParameters)), c('LowerBound', 'Parameter', 'UpperBound'))\n"
                                       "    \n"
                                       "    for (i in 1:numParameters){\n"
                                       "      xmlListIN <- xmlChildren(xmlList[[i]])\n"
                                       "      for (j in 1:xmlSize(xmlListIN)){\n"
                                       "        checkParam = names(xmlListIN) == 'Parameter'\n"
                                       "        if (checkParam[j]){\n"
                                       "          paramValue= xmlToList(xmlListIN[[j]])\n"
                                       "          if (paramValue[[1]] == 'LowerBound'){\n"
                                       "            resTable$LowerBound[i] = paramValue[[3]]\n"
                                       "          }\n"
                                       "          else if (paramValue[[1]]== 'ObjectCN'){\n"
                                       "            resTable$Parameter[i] = gsub(',Reference=','.',gsub('.*Vector=','',paramValue[[3]]))\n"
                                       "          }\n"
                                       "          else if (paramValue[[1]]== 'UpperBound'){\n"
                                       "            resTable$UpperBound[i] = paramValue[[3]]\n"
                                       "          }\n"
                                       "        }\n"
                                       "      }\n"
                                       "    }\n"
                                       "    return(resTable)\n"
                                       "  }\n"
                                       "  \n"
                                       "\n"
                                       "#### To execute different tasks ####\n"
                                       "  resTask <- eventReactive(input$runTask, {\n"
                                       "    modelData <- inputFile$modelData\n"
                                       "    selectedTask <- selection()\n"
                                       "    \n"
                                       "    # Create a Progress object\n"
                                       "    progress <- shiny::Progress$new()\n"
                                       "    # Make sure it closes when we exit this reactive, even if there's an error\n"
                                       "    on.exit(progress$close())\n"
                                       "    progress$set(message = paste('Running ', selectedTask), value = 0)\n"
                                       "    \n"
                                       "    \n"
                                       "    if (selectedTask == 'Steady State'){\n"
                                       "      res <- tryCatch(CoRC::runSS(calculate_jacobian = input$calculateJacobian,perform_stability_analysis =input$calculateJacobian,model=modelData), warning = function(warning_condition){return(warning_condition) }, error = function(error_condition){return(error_condition) })\n"
                                       "      resTask <- res\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Mass Conservation'){\n"
                                       "      \n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Time Course'){\n"
                                       "      res <- tryCatch(CoRC::runTC(duration=input$obsTime,dt=input$obsIntervalSize,start_in_steady_state=input$startSteady,method=input$timeCourseSelection,model=modelData,save_result_in_memory = T), warning = function(warning_condition){return(warning_condition) }, error = function(error_condition){return(error_condition) })\n"
                                       "      resTask <- res\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Metabolic Control Analysis'){\n"
                                       "      res <- tryCatch(CoRC::runMCA(perform_steady_state_analysis = input$mcaSelection, model=modelData), warning = function(warning_condition){return(warning_condition) }, error = function(error_condition){return(error_condition) })\n"
                                       "      resTask <- res\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Optimization'){\n"
                                       "      res <- tryCatch(CoRC::runOptimization(model=modelData), warning = function(warning_condition){return(warning_condition) }, error = function(error_condition){return(error_condition) })\n"
                                       "      resTask <- res\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Parameter Estimation'){\n"
                                       "      res <- tryCatch(CoRC::runParameterEstimation(model=modelData), warning = function(warning_condition){return(warning_condition) }, error = function(error_condition){return(error_condition) })\n"
                                       "      resTask <- res\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Linear Noise Approximation'){\n"
                                       "      res <- tryCatch(CoRC::runLNA(perform_steady_state_analysis = input$lnaSelection,model=modelData), warning = function(warning_condition){return(warning_condition) }, error = function(error_condition){return(error_condition) })\n"
                                       "      resTask <- res\n"
                                       "    }\n"
                                       "    else\n"
                                       "      resTask <- 'No Task found'\n"
                                       "    \n"
                                       "    return(resTask)\n"
                                       "  })\n"
                                       "  \n"
                                       "#### To download tables for different tasks ####  \n"
                                       "  ## For data download\n"
                                       "  output$downloadData<-downloadHandler(\n"
                                       "    filename = function() { \n"
                                       "      if (is.null(inputFile$dataPaths))\n"
                                       "        return(NULL)\n"
                                       "      paste(sub('\\\\..*$', '',inputFile$modelName) , '.csv', sep='')\n"
                                       "      },\n"
                                       "    content = function(file) {\n"
                                       "      if (is.null(file) || error() != '' || is.null(resTask()))\n"
                                       "        return(NULL)\n"
                                       "      selectedTask <- selection()\n"
                                       "      \n"
                                       "      if (selectedTask == 'Steady State'){\n"
                                       "        writeData <- resTask()$species[,c('name','concentration','rate','transition_time')]\n"
                                       "      }\n"
                                       "      else if (selectedTask == 'Stoichiometric Analysis'){\n"
                                       "        \n"
                                       "      }\n"
                                       "      else if (selectedTask == 'Time Course' && 'Time' %in% names(resTask()$result) && !is.null(input$columns)){\n"
                                       "        writeData <- resTask()$result[, c('Time',input$columns), drop = FALSE]\n"
                                       "      }\n"
                                       "      else if(selectedTask == 'Metabolic Control Analysis'){\n"
                                       "        writeData <- resTask()$elasticities_unscaled\n"
                                       "      }\n"
                                       "      else  if(selectedTask == 'Optimization'){\n"
                                       "        writeData <- resTask()$parameters\n"
                                       "      }\n"
                                       "      else if(selectedTask == 'Parameter Estimation'){\n"
                                       "        writeData <- resTask()$parameter\n"
                                       "      }\n"
                                       "      else if (selectedTask == 'Linear Noise Approximation'){\n"
                                       "        writeData <- resTask()$covariance_matrix\n"
                                       "      }\n"
                                       "      else\n"
                                       "        writeData <- 'No Data found'\n"
                                       "      \n"
                                       "      write.csv(writeData,file)\n"
                                       "      }\n"
                                       "  )\n"
                                       "  #content = function(file) { write.csv(resTask()[, c('Time',input$columns), drop = FALSE],file)\n"
                                       "  \n"
                                       "  \n"
                                       "#### To render output tables for different tasks ####\n"
                                       "  output$tableResults <- DT::renderDataTable({\n"
                                       "    if (error() != '' || is.null(resTask()))\n"
                                       "      return(NULL)\n"
                                       "    \n"
                                       "    selectedTask <- selection()\n"
                                       "    if (selectedTask == 'Time Course' && 'Time' %in% names(resTask()$result) && !is.null(input$columns)){\n"
                                       "      data <- resTask()$result[, c('Time',input$columns), drop = FALSE]\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Metabolic Control Analysis'){\n"
                                       "      data <- resTask()$elasticities_unscaled\n"
                                       "    }\n"
                                       "    else if(selectedTask %in% c('Optimization','Parameter Estimation')){\n"
                                       "      data <- t(as.data.frame(resTask()$main))\n"
                                       "      colnames(data) <- c('Value')  \n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Linear Noise Approximation'){\n"
                                       "      data <- resTask()$covariance_matrix\n"
                                       "    }\n"
                                       "    else\n"
                                       "      data <- NULL\n"
                                       "    \n"
                                       "    return(data)\n"
                                       "  },options = list(scrollX = TRUE, scrollY = '400px'))\n"
                                       "  \n"
                                       "  ## Output task-specific results\n"
                                       "  output$tableSS <- DT::renderDataTable({\n"
                                       "    if (error() != '' || is.null(resTask()))\n"
                                       "      return(NULL)\n"
                                       "    data <- resTask()$species[,c('name','concentration','rate','transition_time')]\n"
                                       "    return(data)\n"
                                       "  },options = list(scrollX = TRUE, scrollY = '400px'))\n"
                                       "  \n"
                                       "  output$tableJac <- DT::renderDataTable({\n"
                                       "    if (error() != '' || is.null(resTask()))\n"
                                       "      return(NULL)\n"
                                       "    colNames <- colnames(resTask()$jacobian_complete)\n"
                                       "    data <- data.frame(resTask()$jacobian_complete)\n"
                                       "    data <- formattable(data, list(area(col = colnames(data)) ~ color_tile('lightpink', 'lightgreen')))\n"
                                       "    colnames(data) <- colNames\n"
                                       "    return(as.datatable(data,options = list(scrollX = TRUE, scrollY = '400px')))\n"
                                       "  })\n"
                                       "  \n"
                                       "  output$tableLM <- DT::renderDataTable({\n"
                                       "    if (is.null(inputFile$modelData))\n"
                                       "      return()\n"
                                       "    colNames <- colnames(inputFile$linkMatrix)\n"
                                       "    data <- data.frame(inputFile$linkMatrix)\n"
                                       "    data <- formattable(data, list(area(col = colnames(data)) ~ color_tile('lightpink', 'lightgreen')))\n"
                                       "    colnames(data) <- colNames\n"
                                       "    return(as.datatable(data,options = list(scrollX = TRUE, scrollY = '400px')))\n"
                                       "  })\n"
                                       "  \n"
                                       "  output$tableStoich <- DT::renderDataTable({\n"
                                       "    if (is.null(inputFile$modelData))\n"
                                       "      return()\n"
                                       "    colNames <- colnames(inputFile$stoichiometry)\n"
                                       "    data <- data.frame(inputFile$stoichiometry)\n"
                                       "    data <- formattable(data, list(area(col = colnames(data)) ~ color_tile('lightpink', 'lightgreen')))\n"
                                       "    colnames(data) <- colNames\n"
                                       "    return(as.datatable(data,options = list(scrollX = TRUE, scrollY = '400px')))\n"
                                       "  })\n"
                                       "  \n"
                                       "  output$tablePEfit <- DT::renderDataTable({\n"
                                       "    if (error() != '' || is.null(resTask()))\n"
                                       "      return(NULL)\n"
                                       "    selectedTask <- selection()\n"
                                       "    if(selectedTask == 'Optimization'){\n"
                                       "      return(resTask()$parameters)\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Parameter Estimation'){\n"
                                       "      return(resTask()$parameter)\n"
                                       "    }\n"
                                       "  },options = list(scrollX = TRUE, scrollY = '400px'))\n"
                                       "  \n"
                                       "  output$tablePEexp <- DT::renderDataTable({\n"
                                       "    if (error() != '' || is.null(resTask()))\n"
                                       "      return(NULL)\n"
                                       "    data <- resTask()$experiments\n"
                                       "    return(data)\n"
                                       "  },options = list(scrollX = TRUE, scrollY = '400px'))\n"
                                       "  \n"
                                       "  \n"
                                       "  ## Display the selected parameters and constraints \n"
                                       "  output$tableParameterList <- DT::renderDataTable({\n"
                                       "    data = paramList()\n"
                                       "    if (!is.null(data)) return(data)\n"
                                       "  },options = list(scrollX = TRUE, scrollY = '200px'))\n"
                                       "  \n"
                                       "  output$tableConstraintList <- DT::renderDataTable({\n"
                                       "    data = constrList()\n"
                                       "    if (!is.null(data)) return(data)\n"
                                       "  },options = list(scrollX = TRUE, scrollY = '200px'))\n"
                                       "  \n"
                                       "  ## Display information of the loaded model\n"
                                       "  output$tableModel <- DT::renderDataTable({\n"
                                       "    if ( is.null(inputFile$modelData))\n"
                                       "      return()\n"
                                       "    selectedTask <- selection()\n"
                                       "    if (selectedTask == 'Compartments'){\n"
                                       "      tableCompartments <- inputFile$compartments\n"
                                       "      if (!is.null(tableCompartments)){\n"
                                       "        tableCompartments <- tableCompartments[,c(-1)]    \n"
                                       "      }\n"
                                       "      return(tableCompartments)\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Species'){\n"
                                       "      tableSpecies <- inputFile$species\n"
                                       "      tableSpecies <- tableSpecies[,c(-1,-7,-9,-11)]\n"
                                       "      return(tableSpecies)\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Reactions'){\n"
                                       "      tableReactions <- inputFile$reactions\n"
                                       "      if (!is.null(tableReactions)){\n"
                                       "        tableReactions <- tableReactions[,c('name','reaction','rate_law','flux')]\n"
                                       "        tableReactions$rate_law <- gsub('.*\\\\[|\\\\]', '', tableReactions$rate_law)        \n"
                                       "      }\n"
                                       "      return(tableReactions)\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Global Quantities'){\n"
                                       "      tableGlobalQuantities <- inputFile$globalQuantities\n"
                                       "      tableGlobalQuantities <- tableGlobalQuantities[,-1]\n"
                                       "      return(tableGlobalQuantities)\n"
                                       "    } \n"
                                       "    else if (selectedTask == 'Events'){\n"
                                       "      tableEvents <- data.frame(inputFile$events)\n"
                                       "      if (!is.null(tableEvents)){\n"
                                       "        tableEvents <- tableEvents[,-1]\n"
                                       "        tableEvents$assignment_target <- gsub('.*\\\\(|\\\\)', '', tableEvents$assignment_target)\n"
                                       "        tableEvents$assignment_expression <- gsub('.*\\\\(|\\\\)', '', tableEvents$assignment_expression)\n"
                                       "      }\n"
                                       "      #tableEvents <- tableEvents[,c(-1)]\n"
                                       "      return(data.frame(tableEvents))\n"
                                       "    } \n"
                                       "    else if (selectedTask == 'Parameters'){\n"
                                       "      tableParameters <- inputFile$parameters\n"
                                       "      if (!is.null(tableParameters)){\n"
                                       "        tableParameters <- tableParameters[,-1]\n"
                                       "        tableParameters$mapping <- gsub('.*\\\\[|\\\\]', '', tableParameters$mapping)  \n"
                                       "      }\n"
                                       "      return(tableParameters)\n"
                                       "    } \n"
                                       "  },options = list(scrollX = TRUE, scrollY = '400px'))\n"
                                       "  \n"
                                       "  \n"
                                       "#### To render UI and plots for different tasks ####\n"
                                       "  output$plotOverview <- renderPlot({\n"
                                       "    selectedTask <- selection()\n"
                                       "\n"
                                       "    if (selectedTask == 'Species'){\n"
                                       "      tableSpecies <- inputFile$species\n"
                                       "      if (!is.null(tableSpecies) && nrow(tableSpecies) !=0 ){\n"
                                       "        ylabel <- paste('Concentration (',tableSpecies$unit[1], ')')\n"
                                       "        barplot(tableSpecies$initial_concentration, main='Species overview',  ylab=ylabel, names.arg=tableSpecies$name, cex.names=0.8,las=2)\n"
                                       "      }\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Global Quantities'){\n"
                                       "      tableGlobalQuantities <- inputFile$globalQuantities\n"
                                       "      if (!is.null(tableGlobalQuantities) && nrow(tableGlobalQuantities) !=0 ){\n"
                                       "        barplot(tableGlobalQuantities$initial_value, main='Global Quantities overview', ylab= 'Initial value', names.arg=tableGlobalQuantities$name, cex.names=0.8,las=2)\n"
                                       "      }\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Parameters'){\n"
                                       "      tableParameters <- inputFile$parameters\n"
                                       "      if (!is.null(tableParameters) && nrow(tableParameters) !=0 && !all(is.na(tableParameters$value))){\n"
                                       "        ylabel <- paste()\n"
                                       "        barplot(tableParameters$value, main='Parameters overview', ylab='Value', names.arg=tableParameters$name, cex.names=0.8,las=2)\n"
                                       "      }\n"
                                       "    }\n"
                                       "    \n"
                                       "  })\n"
                                       "  \n"
                                       "  output$plot <- renderPlot({\n"
                                       "    if (error() != '' || is.null(resTask()) || is.null(input$columns))\n"
                                       "      return(NULL)\n"
                                       "    \n"
                                       "    selectedTask <- selection()\n"
                                       "    data <- resTask()$result\n"
                                       "    \n"
                                       "    if (selectedTask == 'Time Course' && 'Time' %in% names(data)){\n"
                                       "      data <- data[, c('Time',input$columns), drop = FALSE]\n"
                                       "      melted <- melt(data,id.vars='Time')\n"
                                       "      colnames(melted)[2:3] <- c('Species', 'Number')\n"
                                       "      plot <- ggplot(melted, aes(x=Time, y=Number, group=Species, color= Species)) + geom_line(size = 1) + theme_classic(base_size = 18) + ggtitle('Time-course of selected species') + ylab('#') + xlab('Time (s)') + theme_pm()\n"
                                       "      print(plot)\n"
                                       "    }\n"
                                       "    else{\n"
                                       "      textOutput('error')\n"
                                       "    }\n"
                                       "  })\n"
                                       "  \n"
                                       "  ## To load the output UI showing table/Plot\n"
                                       "  output$show_output<- renderUI({\n"
                                       "    selectedTask <- selection()\n"
                                       "    if (is.null(inputFile$modelData))\n"
                                       "      return(NULL)\n"
                                       "    if (selectedTask %in% c('Species','Global Quantities','Parameters')){\n"
                                       "      tabsetPanel(id = 'mdl'\n"
                                       "                  ,tabPanel('Table',DT::dataTableOutput('tableModel'))\n"
                                       "                  ,tabPanel('Overview', plotOutput('plotOverview'))\n"
                                       "      )\n"
                                       "    }\n"
                                       "    else if (selectedTask %in% c('Reactions','Compartments', 'Events')){\n"
                                       "        tabPanel('Table',DT::dataTableOutput('tableModel'))\n"
                                       "      }\n"
                                       "    else if (selectedTask == 'Time Course'){\n"
                                       "      tabsetPanel(id = 'TC'\n"
                                       "        ,tabPanel('Time Course',DT::dataTableOutput('tableResults'))\n"
                                       "        ,tabPanel('Plot', plotOutput('plot'))\n"
                                       "      )\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Steady State'){\n"
                                       "      tabsetPanel(id = 'SS'\n"
                                       "        ,tabPanel('Steady State', DT::dataTableOutput('tableSS'))\n"
                                       "        ,tabPanel('Jacobian', DT::dataTableOutput('tableJac'))\n"
                                       "      )\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Metabolic Control Analysis'){\n"
                                       "      tabPanel('Table',DT::dataTableOutput('tableResults'))\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Optimization'){\n"
                                       "      tabsetPanel(id = 'PE'\n"
                                       "                  ,tabPanel('Main',DT::dataTableOutput('tableResults'))\n"
                                       "                  ,tabPanel('Optimized Parameters',DT::dataTableOutput('tablePEfit'))\n"
                                       "      )\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Parameter Estimation'){\n"
                                       "      tabsetPanel(id = 'PE'\n"
                                       "                  ,tabPanel('Main',DT::dataTableOutput('tableResults'))\n"
                                       "                  ,tabPanel('Fitted Parameters',DT::dataTableOutput('tablePEfit'))\n"
                                       "                  ,tabPanel('Experiments', DT::dataTableOutput('tablePEexp'))\n"
                                       "      )\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Linear Noise Approximation'){\n"
                                       "      tabPanel('Table',DT::dataTableOutput('tableResults'))\n"
                                       "    }\n"
                                       "    else if(selectedTask == 'Mass Conservation'){\n"
                                       "      tabsetPanel(id = 'MC'\n"
                                       "        ,tabPanel('Stoichiometry',DT::dataTableOutput('tableStoich'))\n"
                                       "        ,tabPanel('Link Matrix',DT::dataTableOutput('tableLM'))\n"
                                       "      )\n"
                                       "    }\n"
                                       "    else{\n"
                                       "      \n"
                                       "    }\n"
                                       "  })\n"
                                       "  \n"
                                       "#### To choose species for table and plot output ** ONLY FOR TIME_COURSE ** ####\n"
                                       "  output$choose_columns <- renderUI({\n"
                                       "    # If missing input, return to avoid error later in function\n"
                                       "    if(error() != '' || is.null(resTask()))\n"
                                       "      return(NULL)\n"
                                       "    selectedTask <- selection()\n"
                                       "    data <- resTask()$result\n"
                                       "    output = tagList()\n"
                                       "    \n"
                                       "    if (selectedTask == 'Time Course' && 'Time' %in% names(data)){\n"
                                       "      # Get the data set with the appropriate name\n"
                                       "      melted <- melt(data,id.vars='Time')\n"
                                       "      colnames(melted)[2:3] <- c('Species', 'Number')\n"
                                       "      colnames <- unique(melted$Species)\n"
                                       "      \n"
                                       "      output[[1]] = actionButton('showAll', 'Show/Hide All')\n"
                                       "      # Create the checkboxes and select them all by default\n"
                                       "      output[[2]] = checkboxGroupInput('columns', '', \n"
                                       "                         choices  = colnames,\n"
                                       "                         selected = colnames,\n"
                                       "                         inline = T)\n"
                                       "    }\n"
                                       "    output\n"
                                       "  })\n"
                                       "  \n"
                                       "  observeEvent(input$showAll,{\n"
                                       "    if(error() != '' || is.null(resTask()))\n"
                                       "      return(NULL)\n"
                                       "    else {\n"
                                       "      data <- resTask()$result\n"
                                       "      melted <- melt(data,id.vars='Time')\n"
                                       "      colnames(melted)[2:3] <- c('Species', 'Number')\n"
                                       "      colnames <- unique(melted$Species)\n"
                                       "      \n"
                                       "      if (input$showAll %% 2 == 0){\n"
                                       "        updateCheckboxGroupInput(session=session,'columns',\n"
                                       "                                 choices  = colnames,\n"
                                       "                                 selected = colnames,\n"
                                       "                                 inline = T)\n"
                                       "      }\n"
                                       "      else {\n"
                                       "        updateCheckboxGroupInput(session=session,'columns',\n"
                                       "                                 choices  = colnames,\n"
                                       "                                 selected = NULL,\n"
                                       "                                 inline = T)\n"
                                       "      }\n"
                                       "      }\n"
                                       "  })\n"
                                       "\n"
                                       "#### To generate options interface for tasks ####\n"
                                       "  output$choose_options <- renderUI({\n"
                                       "    \n"
                                       "    # If missing input, return to avoid error later in function\n"
                                       "    if(length(get_selected(input$taskSelection))==0)\n"
                                       "      return(NULL)\n"
                                       "    else{\n"
                                       "      textOutput('selection')\n"
                                       "    }\n"
                                       "\n"
                                       "    output = tagList()\n"
                                       "    selectedTask <- selection()\n"
                                       "    if (selectedTask %in% c('Reactions','Species','Compartments', 'Global Quantities','Events','Parameters')){\n"
                                       "      output[[1]] = ''\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Steady State'){\n"
                                       "      output[[1]] = splitLayout(\n"
                                       "        checkboxInput('calculateJacobian','calculate Jacobian', value= T)\n"
                                       "        #,checkboxInput('performStabilityAnalysis','perform Stability Analysis', value= T)\n"
                                       "      )\n"
                                       "      output[[2]] = actionButton('runTask', 'Run Task',icon=icon('angle-double-right'))\n"
                                       "      output[[3]] = downloadButton('downloadData', 'Download Results')\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Mass Conservation'){\n"
                                       "      output[[1]] = ''\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Time Course'){\n"
                                       "      output[[1]] = splitLayout(\n"
                                       "        numericInput('obsTime', 'Duration [s]:', ifelse(is.null(inputFile$modelData), 10, inputFile$settingsTC$duration), min = 1, max = 1000),\n"
                                       "       numericInput('obsIntervalSize', 'Interval Size [s]:', ifelse(is.null(inputFile$modelData), 1, inputFile$settingsTC$dt), min = 0.1, max = 100)\n"
                                       "      )\n"
                                       "      output[[2]] = checkboxInput('startSteady','start in Steady State', value= ifelse(is.null(inputFile$modelData), F, inputFile$settingsTC$start_in_steady_state))\n"
                                       "      output[[3]] = selectInput('timeCourseSelection', 'Select a Method:', choices = c('Deterministic (LSODA)'='deterministic'\n"
                                       "                                                                                       ,'Stochastic (Gibson + Bruck) '='stochastic'\n"
                                       "                                                                                       ,'Stochastic (Direct method)'='directMethod'\n"
                                       "                                                                                       ,'Stochastic (Tau leap)'='tauLeap'\n"
                                       "                                                                                       ,'Stochastic (Adaptive SSA)'='adaptiveSA'\n"
                                       "                                                                                       ,'Hybrid (Runge-Kutta)'='hybrid'\n"
                                       "                                                                                       ,'Hybrid (LSODA)'='hybridLSODA'\n"
                                       "                                                                                       #,'Hybrid (RK45)'='hybridODE45'\n"
                                       "                                                                                       ,'SDE solver (RI5)'='stochasticRunkeKuttaRI5'\n"
                                       "                                                                                       ),selected = ifelse(is.null(inputFile$modelData), 'deterministic', inputFile$settingsTC$method$method))\n"
                                       "      output[[4]] = actionButton('runTask', 'Run Task',icon=icon('angle-double-right'))\n"
                                       "      output[[5]] = downloadButton('downloadData', 'Download Results')\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Metabolic Control Analysis'){\n"
                                       "      output[[1]] = checkboxInput('mcaSelection','perform Steady State Analysis',value = T)\n"
                                       "      output[[2]] = actionButton('runTask', 'Run Task',icon=icon('angle-double-right'))\n"
                                       "      output[[3]] = downloadButton('downloadData', 'Download Results')\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Optimization'){\n"
                                       "      output[[1]] = tabsetPanel(id = 'PE'\n"
                                       "                                ,tabPanel('Parameters', DT::dataTableOutput('tableParameterList'))\n"
                                       "                                ,tabPanel('Constraints', DT::dataTableOutput('tableConstraintList')) )\n"
                                       "      output[[2]] = htmlOutput('selectedMethod')\n"
                                       "      output[[3]] = actionButton('runTask', 'Run Task',icon=icon('angle-double-right'))\n"
                                       "      output[[4]] = downloadButton('downloadData', 'Download Results')\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Parameter Estimation'){\n"
                                       "      output[[1]] = tabsetPanel(id = 'PE'\n"
                                       "                                ,tabPanel('Parameters', DT::dataTableOutput('tableParameterList'))\n"
                                       "                                ,tabPanel('Constraints', DT::dataTableOutput('tableConstraintList')) )\n"
                                       "      output[[2]] = htmlOutput('selectedMethod')\n"
                                       "      output[[3]] = actionButton('runTask', 'Run Task',icon=icon('angle-double-right'))\n"
                                       "      output[[4]] = downloadButton('downloadData', 'Download Results')\n"
                                       "    }\n"
                                       "    else if (selectedTask == 'Linear Noise Approximation'){\n"
                                       "      output[[1]] = checkboxInput('lnaSelection','perform Steady State Analysis',value = T)\n"
                                       "      output[[2]] = actionButton('runTask', 'Run Task',icon=icon('angle-double-right'))\n"
                                       "      output[[3]] = downloadButton('downloadData', 'Download Results')\n"
                                       "    }\n"
                                       "    \n"
                                       "    output\n"
                                       "  })\n"
                                       "  \n"
                                       "  ### Tree structure for task selection\n"
                                       "  output$taskSelection <- renderTree({ \n"
                                       "    sss=list('Model'= structure(list('Compartments'= structure('1',sticon='')\n"
                                       "                                     ,'Species'= structure('2',sticon='')\n"
                                       "                                     ,'Reactions'= structure('3',sticon='')\n"
                                       "                                     ,'Global Quantities'= structure('4',sticon='')\n"
                                       "                                     ,'Events'= structure('5',sticon='')\n"
                                       "                                     ,'Parameters'= structure('6',sticon=''))\n"
                                       "                                , sticon='')\n"
                                       "      ,'Tasks'= structure(list('Steady State'= structure('1',sticon='')\n"
                                       "                               ,'Stoichiometric Analysis'= structure(list('Mass Conservation'= structure('1',sticon='')),sticon='')\n"
                                       "                               ,'Time Course'= structure('2',sticon='')\n"
                                       "                               ,'Metabolic Control Analysis'= structure('3',sticon='')\n"
                                       "                               ,'Optimization'= structure('4',sticon='')\n"
                                       "                               ,'Parameter Estimation'= structure('5',sticon='')\n"
                                       "                               ,'Linear Noise Approximation'= structure('6',sticon=''))\n"
                                       "                          , sticon='')\n"
                                       "      )\n"
                                       "    #attr(sss[[1]],'stopened')=TRUE \n"
                                       "    sss\n"
                                       "  })\n"
                                       "\n"
                                       "  \n"
                                       "}";
