#!/usr/bin/env bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

. "$(git rev-parse --show-toplevel)/gitTools/functions"

if [ -e ${GitTools}/checkout ]; then
  for f in `cat ${GitTools}/checkout`; do
    debug post-commit: checking out $f
    if [ -e "$f" ]; then
      rm $f
      git checkout -- $f
    fi
  done

  rm ${GitTools}/checkout
fi

if [ -e ${GitTools}/UpdateCopasiVersion ]; then
  ${GitTools}/UpdateCopasiVersion
fi



