/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Common_Message */

#ifndef _Included_Common_Message
#define _Included_Common_Message
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
