#!/bin/bash

GitTools="`git config copasi.gittools`"
if [ ! -e ${GitTools}/functions ]; then
  GitTools=$(cd `dirname $0` && pwd)
fi

. ${GitTools}/functions

GAWK=`gitTool gawk`
WGET=`gitTool wget`

remoteCommit=`git rev-parse origin/${branch} 2>/dev/null`

# We only register a build.
if [ "_$1" == "_--registerBuild" ]; then
  major=`${GAWK} -- '$2 ~ "VERSION_MAJOR" {print $3}' ${GitTools}/../copasi/CopasiVersion.h`
  minor=`${GAWK} -- '$2 ~ "VERSION_MINOR" {print $3}' ${GitTools}/../copasi/CopasiVersion.h`
  echo Version: `${WGET} -qO- "git.copasi.org/buildnumber/${major}.${minor}.${remoteCommit}"`

  exit
fi

# Load information about the last run.
if [ -e ${GitTools}/.UpdateCopasiVersion ]; then
  . ${GitTools}/.UpdateCopasiVersion
else
  lastCommit=
fi

localCommit=`git log -1 ${branch} --pretty=%H`
localChanges=`git status --untracked-files=no --short | wc -l`

# If nothing has changed we stop here.
if [ "_$lastCommit" == "_$localCommit" -a $localChanges == 0 -a "_$1" != "_--force" -a -e ${GitTools}/../copasi/CopasiVersion.h ]; then
  echo No changes detected, skipping update.
  exit
fi

# Save information about current run
echo lastCommit=$localCommit > ${GitTools}/.UpdateCopasiVersion

echo Updating ${GitTools}/../copasi/CopasiVersion.h

current_major=4
current_minor=9
current_build=45
current_comment=Source
current_commit=daa20f3198bf8bb44e098ceb862943b36448d596

commitList=`git log --pretty=%H $current_commit..HEAD`
buildList=`${WGET} -qO- "git.copasi.org/buildnumber/list" | \
           sed -e 's/<table>//g' \
               -e 's/<tr>//g' \
               -e 's/<td>//g' \
               -e 's?</table>??' \
               -e 's?</td></tr>?,?g' \
               -e 's?</td>? ?g'`

SAVEIFS=$IFS
IFS=','

echo $current_build > $$
                
compatibility="{"

for b in $buildList; do
  major=${b#major=}
  major=${major%% *}
  minor=${b#*minor=}
  minor=${minor%% *}
  build=${b#*build=}
  build=${build%% *}
  commit=${b#*commit=}
  
  if [ `echo $commitList | grep ${commit}` ]; then
    if [ $current_build == 45 ]; then 
      current_major=${major}
      current_minor=${minor}
      current_build=${build}
      current_commit=${commit}
    fi
	
    echo $build >> $$
  fi
done 

IFS=$SAVEIFS

compatible=all
previous=44
next=45

compatibility={

for b in `sort $$`; do
  # Remove Windows line ending
  b=$((${b//$'\r'}))

  if [ $next != $b ]; then
    compatibility="${compatibility}${previous}, "
    compatible=list
  fi
  
  previous=$((b))
  next=$((b+1))
  
  if [ $compatible == list -a $b != $current_build ]; then
    compatibility="${compatibility}${b}, "
  fi
done;  

compatibility="${compatibility}${current_build}}"

rm $$

if [ "`echo $buildList | grep ${localCommit}`" -a $localChanges == 0 ]; then
  creator=copasi.org
  modified=false
else
  creator=`git config user.email`
  modified=true
fi

IFS=$(echo -en "\n\b")

echo $buildList | grep ${localCommit}

if [ "`echo $buildList | grep ${localCommit}`" -a $localChanges == 0 ]; then
  creator=copasi.org
  modified=false
else
  creator=`git config user.email`
  modified=true
fi


sed -e 's/COPASI_VERSION_MAJOR.*/COPASI_VERSION_MAJOR '$current_major'/' \
    -e 's/COPASI_VERSION_MINOR.*/COPASI_VERSION_MINOR '$current_minor'/' \
    -e 's/COPASI_VERSION_BUILD.*/COPASI_VERSION_BUILD '$current_build'/' \
    -e 's/COPASI_VERSION_MODIFIED.*/COPASI_VERSION_MODIFIED '$modified'/' \
    -e 's/COPASI_VERSION_COMPATIBILITY.*/COPASI_VERSION_COMPATIBILITY '$compatibility'/' \
    -e 's/COPASI_VERSION_COMMENT.*/COPASI_VERSION_COMMENT "'$current_comment'"/' \
    -e 's/COPASI_VERSION_CREATOR.*/COPASI_VERSION_CREATOR "'$creator'"/' \
    ${GitTools}/../copasi/CopasiVersion.h.in > ${GitTools}/../copasi/CopasiVersion.h
    
IFS=$SAVEIFS
